### ISSUE TITLE
Maybe a stupid question, but how do I get the salt? 

### ISSUE THREAD

**Issue by ShubyDobyDo** [ExcessiveAmountsOfZombies/Croptopia#101]
**Version**
Which version of Croptopia are you using?
Croptopia-1.16.4-5-FABRIC-1.3.3.jar
**Platform**
Which platform are you using Croptopia on?
Fabric

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
How can I reproduce the issue?

**Screenshots**

**Other Mods**
What other mods are you using? Having a list might be helpful for me.

**Additional context**

**Comment by RDKRACZ** [comment]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=salt
