### ISSUE TITLE
Suggestion: Make the fruit tree crops into their own (achieveable) block.

### ISSUE THREAD

**Issue by FluffiKiki** [ExcessiveAmountsOfZombies/Croptopia#103]
Hello, I was wondering if, for future updates, you could make it so that the fruit leaves can be removeable and placable? I notice with the current versions (Currently playing 1.16.5 Forge, mod version 1.3.1), you can't shear the crops or get them from creative.

**Comment by ExcessiveAmountsOfZombies** [comment]
I only want the trees to be the only way to achieve the fruits, so that's why they don't and probably won't ever drop blocks
