### ISSUE TITLE
Forge 1.3.1 Minecraft 1.16.5 Pot Deleting itself when making Jam

### ISSUE THREAD

**Issue by litjohn50** [ExcessiveAmountsOfZombies/Croptopia#104]
**Version**
Which version of Croptopia are you using?
1.3.1

**Platform**
Which platform are you using Croptopia on? 
Forge

**Describe the issue**
A clear and concise description of what the issue is.
When Trying to make Jam it uses up the entire pot and only gives me 1 item. Trying to use this mod with cooking for blockheads

**To Reproduce**
How can I reproduce the issue?
Open cooking for block heads crafting. Craft a Croptopia Jam. Pot gets used up

**Screenshots**
https://gyazo.com/7fd71fda860c1de4a89018265b80f0e6

**Other Mods**
What other mods are you using? Having a list might be helpful for me.
Cooking for BlockHeads

**Additional context**
Can you add tools not use durability if in cooking for blockhead kitchen or not use durability at all. Or a config for people to choose to not use durability.

**Comment by ExcessiveAmountsOfZombies** [comment]
I ended up removing durability in 1.4.0 for other reasons and it still ate the item. Apparently the mod has an API to make it not consume items. In a future version this will be fixed.

**Comment by ExcessiveAmountsOfZombies** [comment]
ok, I didn't actually mean to close this at the time, but I've uploaded a new forge version that adds most of the features from fabric 1.17 to forge, 1.4.1 fixes this issue and should be live soon.
