### ISSUE TITLE
I am not finding any salt. 

### ISSUE THREAD

**Issue by sooprturtle** [ExcessiveAmountsOfZombies/Croptopia#105]
Does it spawn on the river surfaces or underground? Just how rare is it? It doesn't make much sense that it would be this rare as it is in so many recipes and it would make more sense just to harvest salt from ocean water.

**Comment by RDKRACZ** [comment]
omfg I can't believe this
https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=salt
https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=salt
https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=salt

and if this is too hard
https://github.com/ExcessiveAmountsOfZombies/Croptopia/wiki/World-Generation#salt

**Comment by ExcessiveAmountsOfZombies** [comment]
I might bump up the spawnrate again, but otherwise you just have to follow rivers until you find it
