### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'croptopia'!

### ISSUE THREAD

**Issue by maddoodles** [ExcessiveAmountsOfZombies/Croptopia#107]
**Version**
Croptopia-1.16.4-5-FABRIC-1.3.3.jar

**Platform**
Fabric

**Describe the issue**
I am getting a -1 Error when trying to start Minecraft, apparently caused by Croptopia. 
I have an error log [here.](https://pastebin.com/0aphZxc5)

**To Reproduce**
If needed I could upload the exact profile I'm currently using via Curseforge. 

**Other Mods**
It's a relatively long list, so refering to the error log may be best. 

**Additional context**
I have attempted to just run Croptopia on its own (with Fabric and Jumploader naturally) and it did load just fine, so this must be a mod incompatability right? Someone [here](https://www.reddit.com/r/fabricmc/comments/mvthle/croptopia_crash/) suggested:
> It looks like Croptopia is relying on a Mixin that is not getting applied.

Which I personally have no idea about but maybe it'll help.

Thank you for your time, please let me know if there's anything else you'd need to try and resolve this.

**Comment by ExcessiveAmountsOfZombies** [comment]
Uhh, hmm I do believe there is a mod incompatibility somewhere. With which mod I'm not sure. I just downloaded 1.3.3 from CF and loaded it into my 1.16.5 instance just fine. If any of the mods you're using changes villagers in some way, maybe try and remove them?

**Comment by maddoodles** [comment]
Yeah I can also confirm that croptopia on it's own works absolutely fine. The only mod I can think of that might affect villagers at this point is repurposed structures as that adds new villages I think? I'll go over the list again as something might be slipping my mind.

**Comment by maddoodles** [comment]
So here's a dumb update, I've reinstalled the modpack we're putting together bit by bit, just with croptopia in from the start, and before the [Optifine alternatives](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754) (we're not using all of them, and I still need to test if they work correctly regardless), it works perfectly fine, despite an identical previous vesion of our modpack pre-optfine alternatives _NOT_ working.

I'll edit this post when I discover if the above Optifine replacements cause this issue or not.

**Comment by ExcessiveAmountsOfZombies** [comment]
If it's not an incompatible mod perhaps croptopia didn't finish downloading in the first pack and was missing some information it needed for the mixin.

**Comment by maddoodles** [comment]
That appears to have been exactly it!

**Comment by ExcessiveAmountsOfZombies** [comment]
so https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/108 actually led me to believe that there was a refmap issue here rather than just a mod being incompatible, so in 1.3.4 I have renamed my refmap so it should be unique to Croptopia now.
