### ISSUE TITLE
Croptopia seed harvesting incompatible with vanillatweaks

### ISSUE THREAD

**Issue by MitztheKat** [ExcessiveAmountsOfZombies/Croptopia#109]
**Version**
Which version of Croptopia are you using?
1.3.3 FABRIC (1.16.5)

**Describe the issue**
A clear and concise description of what the issue is.
I am playing with several other people and it keeps crashing the server when someone (anyone) attempts to harvest grass with a hoe.
**To Reproduce**
How can I reproduce the issue?
1. get a dedicated server up and running.
2. get a hoe.
3. attack grass with hoe.
4. see crash.
**Screenshots**

**Other Mods**
What other mods are you using? Having a list might be helpful for me.
I have my modpack readied for multiMC right here: https://drive.google.com/file/d/16xJ4SsVsBLK21WQJh_Nm2UWnJ_9KVm86/view?usp=sharing
please ignore the name. I was getting frutrated at how it wouldn't load and that I had to keep reloading.
**Additional context**

**Comment by ExcessiveAmountsOfZombies** [comment]
Can you send logs as well?

**Comment by MitztheKat** [comment]
working on logs as I speak.

**Comment by MitztheKat** [comment]
[latest (2).log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/6411589/latest.2.log)
server log.
[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/6411592/latest.log)
client log.
I will look into the striker-rocker thing, but whenever it tries to drop a (croptopia?) seed when harvesting with a hoe, it crashes.
If I manage to fix this without your help I will let you know how I fixed it.

**Comment by MitztheKat** [comment]
Ok so Vanilla tweaks by striker rocker has an incompatible setting, you have to turn off hoes into scythes to prevent the crash.

**Comment by ExcessiveAmountsOfZombies** [comment]
I'll reopen this to see if I can fix it on my end sometime in the future
