### ISSUE TITLE
The Newest version missing half the items

### ISSUE THREAD

**Issue by calsef137** [ExcessiveAmountsOfZombies/Croptopia#110]
**Version**
Which version of Croptopia are you using?
The newest one that was just updated

**Platform**
Which platform are you using Croptopia on?
(Fabric, Forge)
fabric

**Describe the issue**
A clear and concise description of what the issue is.
I want to understand why the book was removed as well as half of the food recipes and items that i had previously made before i updated my server.

**To Reproduce**
How can I reproduce the issue?

**Screenshots**

**Other Mods**
What other mods are you using? Having a list might be helpful for me.
Oh the biomes you'll go
secret rooms
mob origins
origins
patchouli
origin classes
rosea sakura 

**Additional context**

**Comment by ExcessiveAmountsOfZombies** [comment]
uhhh, what? I just now downloaded 1.3.6 to make sure I didn't upload something incorrectly and when I take it into my world everything is there.

**Comment by calsef137** [comment]
So...it appears i somehow managed to download the wrong version.
Now that i have the correct one everything is there.
I am so sorry.

**Comment by ExcessiveAmountsOfZombies** [comment]
All good!
