### ISSUE TITLE
[feature request] hoes and fortune increases drop chance of seeds

### ISSUE THREAD

**Issue by JiroCab** [ExcessiveAmountsOfZombies/Croptopia#111]
hoes and fortune increases drop chance of seeds,
something like 
hoes:
> wood - +0.25%
> stone/gold +0.50%
> iron +0.75%
> diamond +1%
> netherite+1.25

fortune
> I - +0.50%
> II - +0.75%
> III - +1%

**Comment by JiroCab** [comment]
i forgat to mention this was meant for tall grass and Croptopia's seeds drop from them, seems kinda weird or op without that context, im sorry

**Comment by ExcessiveAmountsOfZombies** [comment]
not a bad idea, i'll see about implementing this

**Comment by ExcessiveAmountsOfZombies** [comment]
I ended up just making it work the same way as fortune does on ores, so you'll just get more when they drop.
