### ISSUE TITLE
Forge Croptopia Book Displaying As a Missing Texture, And Isn't Able To Be Opened

### ISSUE THREAD

**Issue by EasySneezy** [ExcessiveAmountsOfZombies/Croptopia#114]
**Version**
1.16.5

**Platform**
Forge

**Describe the issue**
I crafted the Croptopia recipe book, and it's shown up as a missing texture.  I can right click with it, but it doesn't open, and it just makes the "using" animation

**To Reproduce**
Use one plum, one pear, and one lemon, along with a book to create it.

**Screenshots**
https://user-images.githubusercontent.com/80299269/117422530-4f882b80-aee5-11eb-8ad3-1b8a289701fc.png

**Other Mods**
https://user-images.githubusercontent.com/80299269/117423109-f40a6d80-aee5-11eb-81aa-4acd8e01f1b0.png

**Additional context**
The mod was working absolutely fine beforehand, and everything else seems to be working alright, it's just the book is all.

**Comment by RDKRACZ** [comment]
![image](https://user-images.githubusercontent.com/43277609/117439373-0d85d680-af33-11eb-935b-ed16cb6a4242.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
I'm going to leave it like this, at least for now. Install patchouli as RDKRACZ has indicated
