### ISSUE TITLE
Is there a way to copy the fruit flowers or a way to make a tree spawn with more than 2?

### ISSUE THREAD

**Issue by nanakeese** [ExcessiveAmountsOfZombies/Croptopia#116]
Just looking for a way for a tree to have more than 2 harvestable leaves 'consistantly'

**Comment by ExcessiveAmountsOfZombies** [comment]
Sure! in 1.17 you will be able to take a fruit sapling and if you match the leaves the fruit grows on it will create another fruit flower.
