### ISSUE TITLE
Salt doesn't exist

### ISSUE THREAD

**Issue by PerfyNormal** [ExcessiveAmountsOfZombies/Croptopia#117]
**Version**
Croptopia-1.16.4-5-FABRIC-1.3.6

**Platform**
Which platform are you using Croptopia on?
Forge

**Describe the issue**
Salt is not spawning, there's no options.json file by default nor instructions as to where it is. Having no instructions on how to get salt besides in 'river biomes' says nothing. Dig up every river? No..
Someone said to look 'under the ocean', which also tells way too little.
Instructions on one version says that disabling and enabling salt is added to the options.json, but there is no options.json nor mention of if it is enabled or disabled by default.

**To Reproduce**
Search minecraft folder for options.json to try and figure out where this file is on server and there isn't one.

**Other Mods**
byg

**Additional context**
none

**Comment by Jacovii** [comment]
I've been having the same problem, glad to know it's not just me

**Comment by Brandobii** [comment]
Same here, searched for miles looking for salt ore but it just doesnt exist.

**Comment by ExcessiveAmountsOfZombies** [comment]
In 1.17 salt should spawn nearly as often as clay and you can use the water bottles I recently added to make salt too.
