### ISSUE TITLE
Issue: Tofu and Soy sauce have the same recipe

### ISSUE THREAD

**Issue by VortexEyes** [ExcessiveAmountsOfZombies/Croptopia#12]

**Comment by MechanosG** [comment]
To add to this..  if you use another mod to craft the tofu, such as tcrafting, the cooking pot and water bucket get consumed in the process too.  I haven't tested this with Polymorph or EasierCrafting yet, but I assume they might do the same.

Croptopia 1.0.4

**Comment by ExcessiveAmountsOfZombies** [comment]
Fixed in 1.0.5
