### ISSUE TITLE
Renewable Salt

### ISSUE THREAD

**Issue by Fourmisain** [ExcessiveAmountsOfZombies/Croptopia#120]
People not finding salt has become a [running gag](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=is%3Aissue+salt), "where doth thou aquire thine salt?"
It's impressive how many people run into this issue - me included, initially, I had to look it up too to make sure I'm searching at the right place. Once a deposit is found, it usually lasts a long time, so it's not a big issue in terms of rarity.

I was wondering though why there was no renewable way to 'craft' it, e.g. I thought it'd be perfectly reasonable to cook a water bucket to get a little salt - it's manual labor that may not be automatable (since the empty bucket needs to be removed from the furnace), but it'd be an easy albeit inefficient option.

I remember other mods having some kind of drying basin where you put water inside, wait a long while and come back to some salt (which could also be extracted via a hopper, so it's at least semi-automatic) - that option might be a bit too complex though.

Personally, when I know that something is limited, I tend to rarely if not at all use it, so simply the knowledge of salt being renewable, even if a little tedious would make me use it more.

**Comment by ExcessiveAmountsOfZombies** [comment]
In 1.17 the salt is going nearly as common as clay, though I might also just add a recipe for cooking water bottles in furnaces to give salt too.

**Comment by ExcessiveAmountsOfZombies** [comment]
ok, the water bottles I added will also allow you to cook them into salt once 1.17 is released.

**Comment by Fourmisain** [comment]
Will this eat the bottles?
Initially I thought about a smelting recipe that would leave the bucket (if that's even possible), so there's no loss of resources.

**Comment by ExcessiveAmountsOfZombies** [comment]
it will consume the bottle, but I think it's fair because for one bucket of water and three glass you can get 16 salt.
