### ISSUE TITLE
Game is Crashing 

### ISSUE THREAD

**Issue by soswi** [ExcessiveAmountsOfZombies/Croptopia#125]
Well the game is not even  starting.
[log.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/6478580/log.txt)

**Comment by soswi** [comment]
https://pastebin.pl/view/26f5e564
Same log but on the pastebin

**Comment by RDKRACZ** [comment]
Duplicate of #124

**Comment by soswi** [comment]
okay
