### ISSUE TITLE
Cinnamon not dropping in forge versions

### ISSUE THREAD

**Issue by agpk97** [ExcessiveAmountsOfZombies/Croptopia#131]
Hello i was wondering how to get cinnamon cause i got some saplings and i tried right clicking with empty hand or axe and i dont get cinnamon i just strip the wood with the axe

**Comment by ExcessiveAmountsOfZombies** [comment]
need to know which platform and version you're on so I can test and see where I need to fix it, right clicking the log with an axe should drop some cinnamon

**Comment by agpk97** [comment]
i am using forge-36.1.4 
and i am on better minecraft modpack v14.5
i am on pc

**Comment by agpk97** [comment]
Also right clicking with the axe just strips the log for me

**Comment by ExcessiveAmountsOfZombies** [comment]
Thank you

**Comment by agpk97** [comment]
How are you doing my dude i was wondering if you had any luck with the testing
