### ISSUE TITLE
Please add more languages) 1.16.5 (Forge) 

### ISSUE THREAD

**Issue by konstantinshelskiy** [ExcessiveAmountsOfZombies/Croptopia#132]
Hi, you need to expand the mod, namely to translate it into other languages. I just want to offer a translation of the mod into Russian, and if you like it, you can add it to the mod.

**Comment by konstantinshelskiy** [comment]
Here is my translation, please rate it.
https://drive.google.com/file/d/1SVTOojykUwpelfrLZYBZjKezvJp0mG7z/view?usp=sharing

**Comment by ExcessiveAmountsOfZombies** [comment]
If you want to be listed on the right side of the repository as a "contributor" you can turn this into a PR. If not, I can do it that's fine. Either way I'll probably merge this in when 1.17 releases

**Comment by Zetarro** [comment]
Hi! I could help with a translation to spanish! Where do i send it? Do i just link the drive here or what?

**Comment by konstantinshelskiy** [comment]
> If you want to be listed on the right side of the repository as a "contributor" you can turn this into a PR. If not, I can do it that's fine. Either way I'll probably merge this in when 1.17 releases

Yes, but I'm new to github, and I don't know how to turn "this" into a pull request. If you can do this I will be very grateful to you)

**Comment by ExcessiveAmountsOfZombies** [comment]
Yup, no problem! I will have it ready to go for when 1.17 comes out

> 
> 
> Hi! I could help with a translation to spanish! Where do i send it? Do i just link the drive here or what?

Yes you can send the file here too if you wish. The current translations are located here

https://github.com/ExcessiveAmountsOfZombies/Croptopia/tree/master/common/src/main/resources/assets/croptopia/lang
