### ISSUE TITLE
Crop leaves still "float" in the air

### ISSUE THREAD

**Issue by heyjudek** [ExcessiveAmountsOfZombies/Croptopia#135]
I do recall this issue from 5-6 months ago but I think it was fixed by adding leaf decay attribute to crop leaves. I tested it by cutting down an apple tree, one crop leaf block decayed while the other is still hanging there after a few minutes.
![2021-05-28_02 24 05](https://user-images.githubusercontent.com/74119394/119912698-40345500-bf5c-11eb-9118-47e230a7532e.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
It uses random ticks, similar to crops so could just be unlucky?

**Comment by heyjudek** [comment]
Well, as you can see from the picture, all the leaves decayed (I have an instant leaf decay mod) so you could immediately see the crop leaf block hanging there, not decaying after many minutes.

**Comment by ExcessiveAmountsOfZombies** [comment]
in 1.17 they'll act more like vanilla leaves, there is no persistence, however, once they're 7 distance away from the log they can decay.
