### ISSUE TITLE
Onions

### ISSUE THREAD

**Issue by Haziq4123** [ExcessiveAmountsOfZombies/Croptopia#137]
On All of fabric 3 Even when im breaking grass in the jungle onions dont drop

**Comment by ExcessiveAmountsOfZombies** [comment]
I'm in the AOF discord and people regularly talk about getting onion seeds, some of the modded biomes don't seem to be categorized correctly, so some jungle biomes aren't actually jungle biomes. I might be looking at changing this for 1.17 but I'm not sure what I'll do yet
