### ISSUE TITLE
Github Wiki Page Lacking Info

### ISSUE THREAD

**Issue by Zetarro** [ExcessiveAmountsOfZombies/Croptopia#138]
Hi! I was looking through the github page of the mod and realized that the wiki page was lacking Information. I was wondering how I could change that. How do i become an editor of the page? Thanks for reading.

**Comment by ExcessiveAmountsOfZombies** [comment]
What were you wanting to add to the wiki?

**Comment by devomaa** [comment]
probably how to make coffee

**Comment by gding3** [comment]
It is also unclear how to get black pepper
