### ISSUE TITLE
Crops dont work in composter

### ISSUE THREAD

**Issue by Nekohime89** [ExcessiveAmountsOfZombies/Croptopia#140]
**Version**
1.4.0

**Platform**
Which platform are you using Croptopia on?
Fabric...

**Describe the issue**
Crops dont work in composter

**To Reproduce**
i dont understand the question

**Other Mods**
All of Fabric 3

**Comment by koelle25** [comment]
Hi, I can reproduce it, too. But only with tree crops, so e.g. Oranges, Pears, Coconuts, Dates, etc. Farmland crops as well as any seed or sapling work fine.

**Comment by ExcessiveAmountsOfZombies** [comment]
Thank you, this will be fixed in the next 1.17 build
