### ISSUE TITLE
Croptopia seeds don't seem to drop in Terrestria biomes.

### ISSUE THREAD

**Issue by toErIpNid** [ExcessiveAmountsOfZombies/Croptopia#141]
Platform: Fabric latest 1.16.5.

Latest Log: 
[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/6581586/latest.log)

Issue: When playing in a terrestria biome (specifically the Oasis biome) seeds from croptopia don't seem to drop even when breaking tall grass with a stone hoe. 

Additional Info: Currently using Vanilla tweaks data and resource packs, **not** the Vanilla Tweaks mod.

**Comment by ExcessiveAmountsOfZombies** [comment]
i'm going to close this because I'm going to be making the crops generate in the world soon rather than from seeds you break with a hoe or your fist. It might work better for modded biomes too but I won't know until some more of the terrain gen mods update to 1.17
