### ISSUE TITLE
Croptopia foods don't cook in smokers

### ISSUE THREAD

**Issue by MaybeOzzie** [ExcessiveAmountsOfZombies/Croptopia#142]
**Version**
Croptopia 1.16.4-5 FABRIC-1.4.0.jar

**Platform**
Which platform are you using Croptopia on?
Fabric

**Describe the issue**
Croptopia foods that cook only cook in furnaces, and not in smokers.

**To Reproduce**
How can I reproduce the issue?
Put bread and fuel in a furnace to create toast. Then do it in a smoker.

**Screenshots**

**Other Mods**
What other mods are you using? Having a list might be helpful for me.

- Adorn-1.13.0+1.16.5
- antiqueatlas-5.4.4-fabric
- appleskin-mc1.16-fabric-1.0.11
- bettergraves-0.4.1
- blockus-2.1.4+1.16.5
- chat_heads-0.2.2+1.16.2
- cloth-config-4.11.14-fabric
- Controlling-For-Fabric-1.1.3
- cosmetic-armor-1.0.0
- curios-fabric-0.0.13-1.16.5
- DualRiders-1.0.5
- emotecraft-for-MC1.16.5-2.0.3-fabric
- Extra Origins 1.16.5
- Fabric API 1.16.5
- fabric-language-kotlin-1.5.0+kotlin.1.4.31
- HorizonRP1.0.3
- notenoughanimations-1.2.3
- OptiFabric 1.16.5
- OptiFine 1.16.5 G7
- Origins Classes 1.16.5
- Origins-1.16.5-0.7.0
- originsumbrellas-1.1.0
- Pehkui-1.10.0+21w14a
- RoughlyEnoughItems-5.10.184
- Slime Origin 1.16.5
- TRansliterationLib-1.0.4
- TransparentCosmetics-1.2.0
- Xaeros_Minimap_21.8.2_Fabric_1.16.5
- XaerosWorldMap_1.14.0_Fabric_1.16.5

**Additional context**
For easy access to the mods I used;
https://github.com/Alkiasan/HorizonSMP/wiki/Downloads

PS.
This is less important to me, but it seems that vegetarian origins from the origins mod can eat croptopia foods with meat, such as the bacon sandwich.

**Comment by verlixis** [comment]
This should've been implemented in the mod, I hope it's added soon in newer versions.

**Comment by ExcessiveAmountsOfZombies** [comment]
I believe most foods that were cooked in furnaces can now be cooked in smokers and campfires in 1.7.0
