### ISSUE TITLE
Chickens and parrots cant be bred with custom seeds

### ISSUE THREAD

**Issue by Nekohime89** [ExcessiveAmountsOfZombies/Croptopia#144]
**Version**
1.4.0

**Platform**
Fabric

**Describe the issue**
Seeds don't seem to work with chickens and parrots.

**To Reproduce**
Grab some seeds, find a bird, try to feed it.  Fail

**Other Mods**
All of Fabric 3 (2.7.4)

**Comment by ExcessiveAmountsOfZombies** [comment]
This will be fixed in the next 1.17 version I release
