### ISSUE TITLE
SALT

### ISSUE THREAD

**Issue by Musclebounde** [ExcessiveAmountsOfZombies/Croptopia#145]
I have no idea how to get salt. There is no tutorials or anything on how the FUCK to get salt. How THE FUCK DO YOU GET SALT?

**Comment by ExcessiveAmountsOfZombies** [comment]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/wiki/World-Generation#salt

**Comment by ExcessiveAmountsOfZombies** [comment]
if you use the very latest 1.17 version you can also smelt the water bottles that were added.

**Comment by Musclebounde** [comment]
What exactly do you mean the 1.17 version?

**Comment by Musclebounde** [comment]
Like minecraft or version of croptopia

**Comment by ExcessiveAmountsOfZombies** [comment]
https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric/files/3342562 is the version that includes water bottles giving salt

**Comment by Musclebounde** [comment]
How do I get salt naturally? I understand it spawns in rivers but I have been looking for salt for 2 days in many rivers and still haven't found any. How do I get it naturally on a younger version.

**Comment by ExcessiveAmountsOfZombies** [comment]
You need to keep searching in rivers, it's just not as common in versions before 1.17
