### ISSUE TITLE
Little confusing instructions.

### ISSUE THREAD

**Issue by Musclebounde** [ExcessiveAmountsOfZombies/Croptopia#146]
I am confused when it says to cook water bottles to make salt. Does it mean in a furnace, in a cauldron or in some other way? Could I get more straight forward answers? Thank you!

**Comment by ExcessiveAmountsOfZombies** [comment]
get a bucket of water and then 3 glass and then make the recipe for glass bottles but put the bucket in the middle, then you get 16 water bottles you can put into a furnace to get salt
