### ISSUE TITLE
How to get salt ore without crafting.

### ISSUE THREAD

**Issue by Musclebounde** [ExcessiveAmountsOfZombies/Croptopia#148]
I do not know how to get salt without crafting it with prismarine shards and making the ore. How do I get it normally? I know it spawns near rivers but that is very broad.

**Comment by TechnoSparks** [comment]
It is very hard to find it in rivers too. Maybe the rarity could be decreased. I do see that the [current as of writing version](https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric/files/3349484), this is addressed by allowing to create by using stacks of water bottles

**Comment by ExcessiveAmountsOfZombies** [comment]
In 1.4.1 on CF (both fabric and forge) it can spawn as often as clay in RIVER biomes only. minecraft:river and minecraft:cold/frozen_river whichever the frozen one is called. There is also the ability to craft it manually using the water bottles we added.
