### ISSUE TITLE
Consuming stacked Oatmeal replaced the entire stack with one bowl

### ISSUE THREAD

**Issue by Leaf-Forest** [ExcessiveAmountsOfZombies/Croptopia#149]
v1.4.0 Fabric

Consuming stacked items that are in a bowl replace the whole stack with one bowl. For example, eating a stack of 10 Oatmeal would be replaced with one bowl after eating from the stack.

**Comment by ExcessiveAmountsOfZombies** [comment]
thank you, this will be fixed soon

**Comment by ExcessiveAmountsOfZombies** [comment]
Currently uploading the fix, thanks!
