### ISSUE TITLE
[1.16.4-FORGE-1.4.1] Forge tags error 'Couldn't read item tag list'

### ISSUE THREAD

**Issue by Ritzumi** [ExcessiveAmountsOfZombies/Croptopia#152]
**Version**
Croptopia: 1.16.4-FORGE-1.4.1

**Platform**
Forge: 36.1.30

**Describe the issue**
The current version break some of forge:tags/ tags (Mostly related to crop and seed). Problem possibly caused by incorrect typo or deprecated tags. This problem cause some mods that rely on these tags to go haywire and result in unable to create a world due to datapack error.

**To Reproduce**
1. Launch a game with mod installed
2. Create a world
3. See error in log

**Log**
Error log: https://gist.github.com/Ritzumi/228ef74694fd1205b81da1d580850aff

**Other Mods**
None. The tag error was tested on isolated environment.

Thank you~

**Comment by ExcessiveAmountsOfZombies** [comment]
ok, woops, I had looked through the jar a bit to see if the dependant tag got changed to forge and was happy with what I saw and even created a new world and it was fine. i've archived the file on CF for now and will post a fix soon. Thanks

**Comment by ExcessiveAmountsOfZombies** [comment]
Uploading a new 1.4.1 to curseforge at the moment, the dependant tags look like they were transformed into forge tags this time.
