### ISSUE TITLE
Croptopia crashes entire game

### ISSUE THREAD

**Issue by ninjalol5** [ExcessiveAmountsOfZombies/Croptopia#155]
**Version**
Which version of Croptopia are you using?
Croptopia-1.16.4-FORGE-1.4.1

**Platform**
Which platform are you using Croptopia on?
(Fabric, Forge)
Forge
**Describe the issue**
A clear and concise description of what the issue is.
As soon as I open my world the game crashes

**To Reproduce**
How can I reproduce the issue?
N/A
**Screenshots**

**Other Mods**
What other mods are you using? Having a list might be helpful for me.
[modsbeingused.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/6644760/modsbeingused.txt)

**Additional context**
No additional context

**Comment by ninjalol5** [comment]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 6/13/21 4:02 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Multiple entries with same key: artichoke=1 and artichoke=1
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359) ~[guava-21.0.jar:?] {}
	at me.thonk.croptopia.CroptopiaForge.modifyVillagerFoodItems(CroptopiaForge.java:268) ~[?:1.4.1] {re:mixin,re:classloading}
	at me.thonk.croptopia.CroptopiaForge.onWorldLoad(CroptopiaForge.java:282) ~[?:1.4.1] {re:mixin,re:classloading}
	at me.thonk.croptopia.CroptopiaForge$$Lambda$9894/1604956462.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2975/1455581985.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2573/115104953.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:379) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endlessoceans.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:308) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endlessoceans.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:86) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endlessoceans.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endlessoceans.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$18793/443162720.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1870186712 bytes (1783 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.31.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.31.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.31.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.31.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.31.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.31
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		astralsorcery-1.16.4-1.13.9.jar                   |Astral Sorcery                |astralsorcery                 |1.16.4-1.13.9       |DONE      |Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		UnionLib-1.16.5-3.2.4.jar                         |UnionLib                      |unionlib                      |3.2.4               |DONE      |Manifest: NOSIGNATURE
		tea_kettle-0.1.jar                                |Tea Kettle                    |tea_kettle                    |0.1                 |DONE      |Manifest: NOSIGNATURE
		aiotbotania-1.16.4-1.7.6.jar                      |AIOT Botania                  |aiotbotania                   |1.7.6               |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.16.5-2.0.1.8.jar                   |Doggy Talents 2               |doggytalents                  |2.0.1.8             |DONE      |Manifest: NOSIGNATURE
		MCreator Link 1.3 [1.16.5].jar                    |MCreator Link                 |mcreator_link                 |1.3                 |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		MoreMobGriefingOptions-1.16.5-1.0.0.jar           |More MobGriefing Options      |moremobgriefingoptions        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		CookingForBlockheads_1.16.5-9.3.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.3.2               |DONE      |Manifest: NOSIGNATURE
		citadel-1.6.2.jar                                 |Citadel                       |citadel                       |1.6.2               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |Manifest: NOSIGNATURE
		ftb-gui-library-1604.1.1.26.jar                   |FTB GUI Library               |ftbguilibrary                 |1604.1.1.26         |DONE      |Manifest: NOSIGNATURE
		potionsmaster-0.1.34-1.16.4-35.1.13.jar           |Potions Master                |potionsmaster                 |0.1.34-1.16.4-35.1.1|DONE      |Manifest: NOSIGNATURE
		culinaryconstruct-forge-1.16.5-4.0.0.3.jar        |Culinary Construct            |culinaryconstruct             |1.16.5-4.0.0.3      |DONE      |Manifest: NOSIGNATURE
		Bookshelf-1.16.5-10.1.11.jar                      |Bookshelf                     |bookshelf                     |10.1.11             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.16.5.1.2.4.jar                   |Guard Villagers               |guardvillagers                |1.2.4               |DONE      |Manifest: NOSIGNATURE
		Axolotl+1.16.x.jar                                |Axolotl                       |axolotl_12                    |V4 1.12.2           |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.3-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.3               |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		VTweaks-1.16.4-3.5.0.jar                          |V-Tweaks                      |vtweaks                       |3.1.9               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.4-0.12.0.104.jar         |Just Enough Resources         |jeresources                   |0.12.0.104          |DONE      |Manifest: NOSIGNATURE
		shetiphiancore-1.16-3.8.4.jar                     |ShetiPhian-Core               |shetiphiancore                |3.8.4               |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.13.0.jar                 |Supplementaries               |supplementaries               |1.16.5-0.13.0       |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-1.0.5-mc1.16.5-4.jar                  |Macaw's Bridges               |mcwbridges                    |1.0.5               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.4.3.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.3        |DONE      |Manifest: NOSIGNATURE
		fd_cookbook-1.2.jar                               |Farmers Delight Cookbook      |fd_cookbook                   |1.2                 |DONE      |Manifest: NOSIGNATURE
		customizableelytra-1.16.4-1.2.1.jar               |Customizable Elytra           |customizableelytra            |1.2.1               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.469-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.469   |DONE      |Manifest: NOSIGNATURE
		Beekeeper-1.16.2-1.0.0.3.jar                      |Beekeeper                     |bk                            |1.0.0.3             |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.2-mc1.16.5.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.2               |DONE      |Manifest: NOSIGNATURE
		extcaves-2.4.jar                                  |Extended Caves                |extcaves                      |2.4                 |DONE      |Manifest: NOSIGNATURE
		simplefarming-1.16.5-1.3.7.jar                    |Simple Farming                |simplefarming                 |1.16.4-1.3.7        |DONE      |Manifest: NOSIGNATURE
		Botania-1.16.5-416.jar                            |Botania                       |botania                       |1.16.5-416          |DONE      |Manifest: NOSIGNATURE
		fairylights-4.0.5-1.16.5.jar                      |Fairy Lights                  |fairylights                   |4.0.5               |DONE      |Manifest: NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.1.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.4.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.4.0      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |DONE      |Manifest: NOSIGNATURE
		carrotslib-mc1.16.5-3.0b5.jar                     |Carrots Lib                   |carrots                       |3.0b5               |DONE      |Manifest: NOSIGNATURE
		vanillafoodpantry-mc1.16.5-6.0b5.jar              |Vanilla Food Pantry           |vanillafoodpantry             |6.0b5               |DONE      |Manifest: NOSIGNATURE
		ExtraSpace+1.0.1+1.16.5.jar                       |extraspace                    |extraspace                    |1.0.1               |DONE      |Manifest: NOSIGNATURE
		TacoBell-1.16.4-1.1.1.jar                         |Taco Bell                     |tacobell                      |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Gobber2-Forge-1.16.5-2.3.46.jar                   |Gobber 2                      |gobber2                       |2.3.46              |DONE      |Manifest: NOSIGNATURE
		obfuscate-0.6.0-mc1.16.4.jar                      |Obfuscate                     |obfuscate                     |0.6.0               |DONE      |Manifest: e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		giacomos_fishing_net1.7.1-1.16.3.jar              |Giacomo's fishing net mod     |giacomos_fishing_net          |1.7.1               |DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.0.1-mc1.16.5-4.jar                    |Macaw's Roofs                 |mcwroofs                      |2.0.1               |DONE      |Manifest: NOSIGNATURE
		sapience-1.16.4-1.1.1.jar                         |Sapience                      |sapience                      |1.1.1               |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0-pre19-mc1.16.3.jar                      |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |Manifest: NOSIGNATURE
		afaoe2019-0.1.16.46.jar                           |Amazing FoodStuffs            |afaoe2019                     |0.1.16.46           |DONE      |Manifest: NOSIGNATURE
		observerlib-1.16.4-1.5.1.jar                      |ObserverLib                   |observerlib                   |1.16.4-1.5.1        |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |DONE      |Manifest: NOSIGNATURE
		BobaCraft-1.16.3-1.0.2.jar                        |BobaCraft                     |bobacraft                     |1.16.3-1.0.2        |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.16.5-0.10.0-Beta14.jar             |Dynamic Trees                 |dynamictrees                  |1.16.5-0.10.0-Beta14|DONE      |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.8.jar                   |GeckoLib                      |geckolib3                     |3.0.8               |DONE      |Manifest: NOSIGNATURE
		SaveMyStronghold-1.16.4-1.0.jar                   |Save My Stronghold!           |savemystronghold              |1.16.4-1.0          |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |DONE      |Manifest: NOSIGNATURE
		pamhc2trees-1.16.3-1.0.0.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.0               |DONE      |Manifest: NOSIGNATURE
		mining-helmet-1.16.4-2.0.0.jar                    |Mining Helmet                 |mining_helmet                 |2.0.0               |DONE      |Manifest: NOSIGNATURE
		someassemblyrequired-1.16.5-1.3.4.jar             |Some Assembly Required        |someassemblyrequired          |1.16.5-1.3.4        |DONE      |Manifest: NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.1.0.jar                   |Abnormals Core                |abnormals_core                |3.1.0               |DONE      |Manifest: NOSIGNATURE
		environmental-1.16.5-1.0.0.jar                    |Environmental                 |environmental                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |Manifest: NOSIGNATURE
		gempire-indev-0_0_5.jar                           |Gempire                       |gempire                       |1.0                 |DONE      |Manifest: NOSIGNATURE
		WAWLA-1.16.5-8.0.1.jar                            |WAWLA                         |wawla                         |8.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |DONE      |Manifest: NOSIGNATURE
		Fallingleaves-1.16.3-1.0.2.jar                    |Falling Leaves                |fallingleaves                 |1.0.2               |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.1-mc1.16.5.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.5-1.8.6        |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |DONE      |Manifest: NOSIGNATURE
		LibX-1.16.3-1.0.76.jar                            |LibX                          |libx                          |1.16.3-1.0.76       |DONE      |Manifest: NOSIGNATURE
		gardentools-1.16.4-1.1.0.jar                      |Garden Tools                  |gardentools                   |1.16.4-1.1.0        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |DONE      |Manifest: NOSIGNATURE
		BotanyPots-1.16.5-7.0.17.jar                      |BotanyPots                    |botanypots                    |7.0.17              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BotanyTrees-1.16.5-3.0.5.jar                      |BotanyTrees                   |botanytrees                   |3.0.5               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		fantasy-forge-1.1.1.jar                           |Fantasy Mounts                |fantasy                       |1.0                 |DONE      |Manifest: NOSIGNATURE
		CrockPot-1.16.3-1.5.2-release.jar                 |Crock Pot                     |crockpot                      |1.5.2-release       |DONE      |Manifest: NOSIGNATURE
		TinyMobFarm-1.16.3-1.1.1.jar                      |Tiny Mob Farm                 |tinymobfarm                   |1.1.1               |DONE      |Manifest: NOSIGNATURE
		mapperbase-1.16.4-2.3.0.0.jar                     |Mapper Base                   |mapperbase                    |1.16.4-2.3.0.0      |DONE      |Manifest: NOSIGNATURE
		embellishcraft-1.16.4-3.3.0.0.jar                 |EmbellishCraft                |embellishcraft                |1.16.4-3.3.0.0      |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.16.4-1.10.6.jar                     |Ars Nouveau                   |ars_nouveau                   |1.10.6              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.31-universal.jar                |Forge                         |forge                         |36.1.31             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Farmers_Extra_Foods_1.2.jar                       |Farmer's Extra Foods          |farmers_extra_foods           |1.0.0               |DONE      |Manifest: NOSIGNATURE
		MoreCraftingTables+-+1.16.5.jar                   |More Crafting Tables Mod      |mctb                          |1.16.5 - 1.0.0      |DONE      |Manifest: NOSIGNATURE
		scuba-gear-1.16.5-1.0.3.jar                       |Scuba Gear                    |scuba_gear                    |1.0.3               |DONE      |Manifest: NOSIGNATURE
		neapolitan-1.16.4-2.0.1.jar                       |Neapolitan                    |neapolitan                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		MythicBotany-1.16.4-1.3.15.jar                    |MythicBotany                  |mythicbotany                  |1.16.4-1.3.15       |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.31-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.0.1.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.1               |DONE      |Manifest: NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.16-3.1.4.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.4          |DONE      |Manifest: NOSIGNATURE
		titanium-1.16.4-3.2.5.jar                         |Titanium                      |titanium                      |3.2.5               |DONE      |Manifest: NOSIGNATURE
		pamhc2crops-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |DONE      |Manifest: NOSIGNATURE
		EndlessOcean-1.0.4-1.16.x.jar                     |Endless Oceans                |endlessoceans                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.103.jar                         |Mantle                        |mantle                        |1.6.103             |DONE      |Manifest: NOSIGNATURE
		Inspirations-1.16.5-1.2.3.32.jar                  |Inspirations                  |inspirations                  |1.2.3.32            |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.10.0.3_Forge_1.16.5.jar         |Xaero's Minimap               |xaerominimap                  |21.10.0.3           |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.16.4-FORGE-1.4.1.jar                  |Croptopia                     |croptopia                     |1.4.1               |DONE      |Manifest: NOSIGNATURE
		multibeds-1.16-1.7.7.jar                          |Multi-Beds                    |multibeds                     |1.7.7               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-312.jar                                |Quark                         |quark                         |r2.4-312            |DONE      |Manifest: NOSIGNATURE
		charm-forge-1.16.5-2.3.2.jar                      |Charm                         |charm                         |2.3.2               |DONE      |Manifest: NOSIGNATURE
		abnormals_delight-1.16.5-1.0.1.jar                |Abnormals Delight             |abnormals_delight             |1.0.1               |DONE      |Manifest: NOSIGNATURE
		[1.16.5]+SecurityCraft+v1.8.21.1.jar              |SecurityCraft                 |securitycraft                 |v1.8.21.1           |DONE      |Manifest: NOSIGNATURE
		ToughAsNails-1.16.5-4.0.1.23-universal.jar        |Tough As Nails                |toughasnails                  |1.16.5-4.0.1.15     |DONE      |Manifest: NOSIGNATURE
		simplytea-1.16.5-2.3.4.jar                        |Simply Tea                    |simplytea                     |2.3.4               |DONE      |Manifest: NOSIGNATURE
		PizzaCraft-1.16.5-3.0.4.jar                       |PizzaCraft                    |pizzacraft                    |3.0.4               |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.16.5-2.1.19.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.19       |DONE      |Manifest: NOSIGNATURE
		SpawnEggRecipes+-+1.5.0+(Zombified+Piglin+Bug+Fix)|Spawn Egg Recipes Mod         |spawn                         |1.16.4-1.2.0        |DONE      |Manifest: NOSIGNATURE
		Food-N-Plants-1.2.3-Release.jar                   |Food N Plants                 |food_n_plants                 |1.3.10              |DONE      |Manifest: NOSIGNATURE
		flowerseeds-1.16.5-1.2.jar                        |Flower Seeds                  |flowerseeds                   |version             |DONE      |Manifest: NOSIGNATURE
		farmerstea-1.0.0.jar                              |Farmer's Tea                  |farmerstea                    |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Avaritia_furnace-1.2.2-1.16.4.jar                 |Avaritia Furnace              |avaritiafurnace               |1.2.2               |DONE      |Manifest: NOSIGNATURE
		farmersreplant-1.16.5-1.0.jar                     |Farmers Replant               |farmersreplant                |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: dea42519-b8d1-4e6e-b8f7-4cf569f1bed8
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:astralsorcery, mod:unionlib (incompatible), mod:tea_kettle, mod:aiotbotania (incompatible), mod:doggytalents (incompatible), mod:bettercaves (incompatible), mod:moremobgriefingoptions, mod:cookingforblockheads (incompatible), mod:citadel (incompatible), mod:yungsapi, mod:ftbguilibrary (incompatible), mod:potionsmaster, mod:culinaryconstruct (incompatible), mod:bookshelf, mod:guardvillagers, mod:mcwdoors, mod:waila, mod:vtweaks (incompatible), mod:jeresources, mod:shetiphiancore, mod:mcwbridges, mod:farmersdelight, mod:fd_cookbook, mod:customizableelytra, mod:biomesoplenty, mod:bk, mod:mcwtrpdoors (incompatible), mod:extcaves, mod:simplefarming, mod:botania, mod:fairylights, mod:pamhc2foodextended (incompatible), mod:curios, mod:patchouli (incompatible), mod:carrots, mod:vanillafoodpantry, mod:extraspace, mod:tacobell, mod:gobber2, mod:obfuscate (incompatible), mod:giacomos_fishing_net, mod:mcwroofs, mod:sapience, mod:cfm (incompatible), mod:afaoe2019 (incompatible), mod:observerlib, mod:mcwfurnitures, mod:bobacraft, mod:dynamictrees, mod:bettermineshafts, mod:geckolib3 (incompatible), mod:savemystronghold, mod:quarkoddities (incompatible), mod:pamhc2trees (incompatible), mod:mining_helmet (incompatible), mod:someassemblyrequired, mod:jei, mod:abnormals_core, mod:environmental, mod:buzzier_bees, mod:gempire, mod:wawla, mod:extraboats, mod:mcwpaintings (incompatible), mod:naturescompass (incompatible), mod:sereneseasons, mod:libx, mod:gardentools (incompatible), mod:botanypots, mod:botanytrees, mod:fantasy, mod:crockpot, mod:tinymobfarm (incompatible), mod:mapperbase (incompatible), mod:embellishcraft (incompatible), mod:ars_nouveau, mod:forge, mod:farmers_extra_foods, mod:mctb, mod:scuba_gear (incompatible), mod:neapolitan, mod:mythicbotany, mod:upgrade_aquatic, mod:endergetic, mod:theoneprobe, mod:titanium (incompatible), mod:pamhc2crops (incompatible), mod:endlessoceans, mod:savageandravage, mod:mantle (incompatible), mod:inspirations (incompatible), mod:xaerominimap, mod:pamhc2foodcore (incompatible), mod:multibeds, mod:autoreglib (incompatible), mod:quark (incompatible), mod:charm, mod:abnormals_delight, mod:toughasnails, mod:simplytea (incompatible), mod:pizzacraft (incompatible), mod:aquaculture (incompatible), mod:spawn, mod:flowerseeds, mod:farmerstea, mod:avaritiafurnace, mod:farmersreplant, mod:securitycraft (incompatible), mod:mcreator_link (incompatible), mod:axolotl_12, mod:supplementaries, mod:fallingleaves, mod:decorative_blocks, mod:croptopia, mod:food_n_plants, mod:dsurround
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.01pre2.zip
	OpenGlVersion: 4.6.0 NVIDIA 466.47
	OpenGlRenderer: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by ExcessiveAmountsOfZombies** [comment]
not sure how this happened, I guess you somehow reinitalized the mod? imo that'd be the only way this could happen
