### ISSUE TITLE
I can't find salt

### ISSUE THREAD

**Issue by HiIAmACyst** [ExcessiveAmountsOfZombies/Croptopia#158]
I don't know if I'm looking for it right but no matter how hard I look for the salt mineral I can't find it. In the guidebook it appears that this material appears in the river biome but I am not able to see it anywhere. I'm using in the 1.16.5 versión. I know it's not common to find it, but how can I make your search easier?

**Comment by atlastheunliving** [comment]
i've noticed the salt that spawns in river biomes are under some sand, not typically in the first layer of sand. the salty sand is easier to find, i think, in the salty ponds that spawn occasionally through your world. i'm not sure if that's their technical term but it's just a lake with cobblestone, sand and salty sand around it. i got over a stack and a half of salt just from looting one of them.

**Comment by ExcessiveAmountsOfZombies** [comment]
There is not any way for me to make it any more common, you just have to run along biomes that are marked as minecraft:river or minecraft:ice_river. that or update to versions 1.4.1 on either forge or fabric. Those versions have salt that spawns nearly as commonly as clay.

**Comment by HiIAmACyst** [comment]
I was using the 1.4.0 version, i downloaded 1.4.1 and finally i could see salt. Thanks for the help
