### ISSUE TITLE
Consuming soy milk does not return bottles, despite the crafting recipe requiring bottles.

### ISSUE THREAD

**Issue by tariqk** [ExcessiveAmountsOfZombies/Croptopia#16]
Using v1.0.4-1.16.3-FABRIC, installed in [All of Fabric 3](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3), version 2.3.4

Expected behavior should be that consuming soy milk bottles should return bottles, since bottles are consumed in the crafting recipe.

**Comment by ExcessiveAmountsOfZombies** [comment]
This is fixed in 1.0.5 on my end so will probably be fixed in the next version of AOF that comes out
