### ISSUE TITLE
Can't right click trees to gather crops 1.17

### ISSUE THREAD

**Issue by spstansberry** [ExcessiveAmountsOfZombies/Croptopia#160]
Can't right click trees to gather crops 1.17

**Comment by Vampiee** [comment]
You can right click the stuff off the trees, it's just that they don't grow naturally or they grow EXTREMELY slowly; also bonemeal makes the stuff on the trees grow.

**Comment by ExcessiveAmountsOfZombies** [comment]
being uploaded at the moment
