### ISSUE TITLE
Seeds do not drop, tree crops do not mature. [1.17, Fabric]

### ISSUE THREAD

**Issue by cuiffo** [ExcessiveAmountsOfZombies/Croptopia#161]
**Version**
Croptopia-1.17-rc2-FABRIC-1.4.1

**Platform**
Which platform are you using Croptopia on?
Fabric

**Describe the issue**
No seeds can be obtained from grass, and tree crops do not age over time.

**To Reproduce**
1. Start a fresh "custom" modpack w/ fabric in Curseforge.
2. Add Croptopia as the only mod (other than fabric API by default)
3. Start game in creative, get bonemeal to make tall grass and break away in survival.

**Comment by cuiffo** [comment]
Just to clarify: tree crops indeed do appear in the world, but they will stay at 0 maturity.

**Comment by AlwaysSoren** [comment]
I will add that I am having the same issue. I can find the trees with the leaves, but you cannot harvest them as they never mature. Every tree I come across has a growth of 0%. No amount of grass clearing will produce seeds.

**Comment by cuiffo** [comment]
Ah using hoe does it! No mention in documentation, would probably make sense to add. I don't think I've ever seen higher maturity on trees, even after speeding up time, but bonemeal works well enough. Will close, thanks!

**Comment by olee** [comment]
I can confirm that using a hoe makes it possible to get seeds, however fruits do indeed not grow on trees.
The new server has been running for days and the fruits were still on 0% growth.

**Comment by ExcessiveAmountsOfZombies** [comment]
update to 1.5.0 and this will be fixed
