### ISSUE TITLE
Crafting any pizza destroys the frying pan

### ISSUE THREAD

**Issue by ThePhantomPig791** [ExcessiveAmountsOfZombies/Croptopia#162]
**Version**
Which version of Croptopia are you using?
v1.3.1
**Platform**
Which platform are you using Croptopia on?
(Fabric, Forge)
Fabric
**Describe the issue**
A clear and concise description of what the issue is.
When crafting a pizza, instead of using durability, it uses the entire frying pan
**To Reproduce**
How can I reproduce the issue?
Craft a pizza and observe the frying pan disappear 
**Screenshots**

**Other Mods**
What other mods are you using? Having a list might be helpful for me.

**Additional context**
I don't know if it's intended, but it seems like it is a bug.

**Comment by ExcessiveAmountsOfZombies** [comment]
could you test this on a later version? I'm pretty sure it's fixed now
