### ISSUE TITLE
[Feature request] config seed drops

### ISSUE THREAD

**Issue by JiroCab** [ExcessiveAmountsOfZombies/Croptopia#163]
To fit some play styles and setting, Would be nice if crops can be configured to drop seeds when:
-Default (drop seeds on harvest & break)
-OnBreak (only drops seeds on break, only mature drops more)
-NoSeeds (no seeds)
-HoeHravest (drop seeds when harvested with hoe)
-HoeBreak (drop seeds when broken with hoe)
-HoeAll (drop seeds on harvest & break with hoe)

ps harvest is right click, have a good day

**Comment by ExcessiveAmountsOfZombies** [comment]
originally I wasn't sure if i wanted to implement this, I'm kinda wary of configs, especially if there is a way to do it with datapacks. I believe most of the stuff listed here could be done with a datapack and in 1.7.0 I will have moved away completely from the hoe method of gathering crops in favor of them just generating in the world.

**Comment by GrasshopperFK** [comment]
It's a pity that nothing has changed in this regard. Since you can create the seeds from the fruits, an extra drop when harvesting or finding bushes etc. is superfluous. It would still be great if you could disable the seed drop (at least optionally).
