### ISSUE TITLE
Cant find cinnamon or harvest cinnamon from trees

### ISSUE THREAD

**Issue by Anettei** [ExcessiveAmountsOfZombies/Croptopia#164]
**1.16.5 v1.4.1**

**Forge** 

No matter where I look, On my multiplayer world and singleplayer world. I just cannot find cinnamon trees. Ive searched for hours on both single and multi and haven't found one tree. I've also tried going into creative mode and placing down a sapling and harvesting it but it doesn't harvest at all. Is this a bug?

**Comment by toto11xd** [comment]
I saw a cinamon tree in a jungle (mod for 1.17), only one across the ocean.
With a simple axe, destroy leaves give me leaves, log give me log
No craft know by Roughly Enough Items

When you destroy all log, leaves are poping (no need silk touch!)

**Comment by sethjlogan** [comment]
In Fabric 1.17, I've found a cinnamon tree in world gen, but can confirm that breaking the leaves by hand/non-Silk-Touch tool, or just via leaf decay, gives a jungle leaf block for every cinnamon leaf block broken, instead of dropping cinnamon saplings or cinnamon leaf blocks.

**Comment by ExcessiveAmountsOfZombies** [comment]
uploading new fabric/forge versions that should fix their respective issues
