### ISSUE TITLE
New Support for Serene Seasons

### ISSUE THREAD

**Issue by SharkieTV** [ExcessiveAmountsOfZombies/Croptopia#167]
Hi in this [Github](https://github.com/Glitchfiend/SereneSeasons/pull/325#issuecomment-869631690) you added support but now its changed and was wondering if you can add support again?

**Comment by ExcessiveAmountsOfZombies** [comment]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/commit/b9de5fb9dd4356c8c107c78c1dee5ab6bea62061 uploading soon, also includes some small fixes

**Comment by OneShot313** [comment]
Is there a fabric version of this?

**Comment by HawaiiLife745** [comment]
Any update on this?

**Comment by Victorucci** [comment]
Any update?
