### ISSUE TITLE
can't create cinnamon tree in fabric 1.17 version

### ISSUE THREAD

**Issue by Eahegstad** [ExcessiveAmountsOfZombies/Croptopia#168]
**Version**
Which version of Croptopia are you using?

**Platform**
Which platform are you using Croptopia on?
(Fabric, Forge)

**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
How can I reproduce the issue?

**Screenshots**

**Other Mods**
What other mods are you using? Having a list might be helpful for me.

**Additional context**

**Comment by Eahegstad** [comment]
I am using the fabric 1.17 version of Croptopia
Fabric version
I found and harvested cinnamon off the tree by right clicking the bark with my axe and ended up with pieces of cinnamon. But when I try to combine two pieces with a sapling ... I don't get a cinnamon tree. When I cut down the cinnamon tree, the leaves just drop as leaves and dont give any saplings ... even if broken by hand or with a fortune tool ... the leaves drop as leaf blocks
I can reproduce the problem every time I try to combine two pieces of cinnamon with a sapling ... no cinnamon sapling is ever able to be crafted
I have assembled a small modpack that also includes: Adorn, Architectury, Bedspreads, Blockus, Carrier, Cloth-config, Easier vilalger trading, Elytra Trinket, Glass Doors, Invisible Frames, Light overlay, Litematica, Mini Hud, Mining Dimensions, Optifabric, Overpowered Mending, Patchouli, Rings of Ascension, Roughly Enough items, Shulker Box Tooltips, Trinkets, Upgraded Shulkers, Xaeros Minimap, Xaeros World Map

**Comment by ExcessiveAmountsOfZombies** [comment]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/commit/a4d138ebd0262e74126a6b3be7fc20d4aa4adbf7 this fixes the issue, i'll have a new release out soon
