### ISSUE TITLE
Buckets and other container items being used up?

### ISSUE THREAD

**Issue by AythaAquaheart** [ExcessiveAmountsOfZombies/Croptopia#17]
I don't know if it's supposed to happen or not, but using up the iron bucket whenever I want to craft some dough for example seems a little expensive. Mostly an issue for buckets really. Though bowls and bottles would also be nice to get back after use.

**Comment by ExcessiveAmountsOfZombies** [comment]
if you're on 1.0.4 i fixed this in 1.0.5

**Comment by AythaAquaheart** [comment]
Oh okay, I think I just missed the update then, sorry about that!
Works fine now indeed.
