### ISSUE TITLE
Retrogen? [enhancement]

### ISSUE THREAD

**Issue by iamnotauser** [ExcessiveAmountsOfZombies/Croptopia#171]
Does this mod have retrogeneration? The plants don't show up on pre-generated chunks on my world. And it's a bit tedious to find stuff on new chunks. 
(I'm also using 1.17 and fabric.)
Sorry for not knowing how to add labels to this issue report.

**Comment by ExcessiveAmountsOfZombies** [comment]
I think this sounds unsafe and kinda out of scope for croptopia. 

It'd probably be better for a standalone mod to be developed that could look at the list of features currently registered and then with a command process all the currently generated chunks and go back through them and place those features. I don't even know if that's feasible though.

I'd recommend going to the nether, picking a direction and going out some distance to get some new world generation if that's what you can do.
