### ISSUE TITLE
Having issues finding Peppercorn.

### ISSUE THREAD

**Issue by Spiritbloodz** [ExcessiveAmountsOfZombies/Croptopia#172]
**Version**
Which version of Croptopia are you using?
1.3.1
**Platform**
Which platform are you using Croptopia on?
(Fabric, Forge)
Cursed Forge
**Describe the issue**
A clear and concise description of what the issue is.
I cannot find any "Pepper" ingredient anywhere
**To Reproduce**
How can I reproduce the issue?
I cannot find any "pepper" for the seasoning of dishes
**Screenshots**
N/A
![unknown (2)](https://user-images.githubusercontent.com/86869505/124346015-6af07980-dbaa-11eb-9a9f-e552b102a92d.png)

**Other Mods**
What other mods are you using? Having a list might be helpful for me.
Origin - smp, From Curseforge beta
**Additional context**
I have been looking through the different spices needed to be able to make dishes, however i haven't found either a seed Nor block to extract the "pepper" element, the salt was underwater, shovel harvested

**Comment by ExcessiveAmountsOfZombies** [comment]
I didn't actually make pepper obtainable until Forge 1.4.0 when I added recipes inspired from the UK, so you might want to update

**Comment by Spiritbloodz** [comment]
I'll let the server owner know, as it's his server and not mine, Thank you very much!

**Comment by ExcessiveAmountsOfZombies** [comment]
Glad to help!
