### ISSUE TITLE
[enhancement/request/suggestion] Adding support for Farmer's Delight?

### ISSUE THREAD

**Issue by viedemarli** [ExcessiveAmountsOfZombies/Croptopia#175]
Hello, I love this mod and I love Farmer's Delight; I noticed that Croptopia has support for other Fabric mods, like Dehydration (which I also use, and love, so that's awesome!), and I wasn't sure where to add a suggestion label so I put it in my title. I'm basically asking what the title suggests; is there a possibility in the future (no matter how long, I understand how hard modders work and how busy they are, but I thought I'd ask) that Croptopia could add Farmer's Delight support? Both have cabbage, tomatoes, onions, and rice, but I learned the hard way that the aforementioned items aren't interchangeable between mods.

If there was a way I could quickly do it myself I would, so as not to bother, but I'm not a modder and I know very, very little about how tags work, especially when it comes to Fabric.

Otherwise, this mod is absolutely incredible and I love everything about it! It's a great alternative to other crop and food adding mods from Forge. 

Thank you for taking the time to read this if you do, and I apologize about bothering you—if I knew how to tag this as a request and not an issue, I would. Take your time as this is something super small and really it doesn't even need to be done, and thank you also for creating such a wonderful quality-of-life mod!

**Comment by IanQB** [comment]
^ This tbh

**Comment by ExcessiveAmountsOfZombies** [comment]
I believe this was fixed in a recent version where I took at look at their tags and tried to make some of mine match
