### ISSUE TITLE
Croptopia crops are level 2 trades, not level 1 trades.

### ISSUE THREAD

**Issue by Angular-Angel** [ExcessiveAmountsOfZombies/Croptopia#177]
**Version**
Croptopia-1.17-FABRIC-1.5.0.jar

**Platform**
Fabric

**Describe the issue**
Croptopia trades show up as level 2 trades, which makes it harder to get other level 2 trades, such as apples, for making golden apples, when using villagers during a nether survival run.

**To Reproduce**
Start a new game with Croptopia, and level a farmer up to level 2.

**Other Mods**
appleskin-fabric-mc1.17-2.0.0.jar
architectury-2.0.16-fabric.jar
better-nether-5.1.0-1.17.jar
charm-fabric-1.17-3.2.2-beta.jar
cloth-config-5.0.34-fabric.jar
comforts-fabric-0.0.4-1.17.jar
dawn-2.0.3.jar
elytratrinket-fabric-2.0.1-1.17.jar
EnchantmentDescriptions-fabric-1.17-3.0.11.jar
environmentalcreepers-fabric-1.17.0-1.6.0.jar
fabric-api-0.36.0+1.17.jar
fabric-tree-chopper-0.7.0.jar
immersive-portals-0.05-mc1.17-fabric.jar
lithium-fabric-mc1.17-0.7.2.jar
morevillagers-FABRIC-1.17-2.0.1.jar
mostructures-1.2.1-1.17.jar
repurposed_structures_fabric-2.0.2+1.17.0.jar
RoughlyEnoughItems-6.0.260-alpha-fabric.jar
stoneholm-1.3.jar
trinkets-3.0.0.jar
universal_ores-1.0.jar
vanillaplusbiomes-0.3.2.jar
veinmining-fabric-0.0.10-1.17.jar
wraith-waystones-2.0.1.jar
wthit-fabric-3.6.1.jar
Xaeros_Minimap_21.12.2_Fabric_1.17.jar
XaerosWorldMap_1.14.4_Fabric_1.17.jar

Charm and MoreVillagers are the ones that seem most relevant, but here's the whole list.

**Comment by ExcessiveAmountsOfZombies** [comment]
This will be fixed next time I update the mod https://github.com/ExcessiveAmountsOfZombies/Croptopia/commit/1920e748fc48131e44bb3f4b75103557c0167024 eventually there might just be a specific Croptopia villager that only trades items from the mod
