### ISSUE TITLE
Crashing, Appears to be an issue related to Croptopia

### ISSUE THREAD

**Issue by Daviel2** [ExcessiveAmountsOfZombies/Croptopia#179]
**Version**
Which version of Croptopia are you using?
1.16.5
**Platform**
Which platform are you using Croptopia on?
(Fabric, Forge)
Fabric
**Describe the issue**
A clear and concise description of what the issue is.
Upon Starting MC, I am Greeted with this Error
**To Reproduce**
How can I reproduce the issue?
I am unsure, As it had suddenly started, And Even Upgrading to the most recent Version of Croptopia Occured
**Screenshots**
![image](https://user-images.githubusercontent.com/82469049/125005524-ef6b4e00-e029-11eb-95a6-0d396649cef0.png)

**Other Mods**
What other mods are you using? Having a list might be helpful for me.
The Other Mods I am currently Using Are
Betterend
Voxelmap
Mob-origins
Origins
RoughlyEnoughItems
Patchouli (Recipe-Book)
Fabric-API (Required for Fabric to Work)
Optifine
**Additional context**

**Comment by ExcessiveAmountsOfZombies** [comment]
I'll need the latest.log use this https://paste.gg/ to send it

**Comment by Daviel2** [comment]
The Latest.Log?

**Comment by RDKRACZ** [comment]
> The Latest.Log?

https://minecrafthopper.net/help/guides/getting-minecraft-latest-log/

**Comment by Daviel2** [comment]
Thanks, and For some reason, it isn't showing up, but the crash log is showing up

**Comment by Daviel2** [comment]
I can get an SS Of the crash log, or a pastebin of it

**Comment by ExcessiveAmountsOfZombies** [comment]
that's fine, I just need something that has a stacktrace pointing to why it crashed

**Comment by Daviel2** [comment]
Alright, I can do that

**Comment by Daviel2** [comment]
Sorry for the delay, had some issues

**Comment by Daviel2** [comment]
[crash-2021-07-19_14.04.13-client.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/6843019/crash-2021-07-19_14.04.13-client.txt)
Crash Log.

**Comment by ExcessiveAmountsOfZombies** [comment]
Did you modify the config file? perhaps delete the file and let it regenerate

**Comment by Daviel2** [comment]
I'll try that

**Comment by Daviel2** [comment]
So Just Delete the Config File, Start MC Up and see what happens?

**Comment by Daviel2** [comment]
Like- the Config folder for croptopia?

**Comment by ExcessiveAmountsOfZombies** [comment]
yes

**Comment by Daviel2** [comment]
Alright, I'll try that, thanks

**Comment by Daviel2** [comment]
oop- Looks like The Launcher made it past the crashing startup point, should be good

**Comment by Daviel2** [comment]
Problem, It's crashing as soon as I Create a World or Join a Server

**Comment by ExcessiveAmountsOfZombies** [comment]
Send the log for that then

**Comment by ExcessiveAmountsOfZombies** [comment]
Actually, update Croptopia to 1.4.0, which is the last version for 1.16.5 and see if the issue persists
 https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric/files/3309414

**Comment by Daviel2** [comment]
Alright, I'll update to 1.4.0 To see if it persists.

**Comment by Daviel2** [comment]
I wouldn't say a crashing issue is the problem now, but one of the problems I am experiencing is when I Attempt to make a world, It causes The World Generation % To remain at 0, Unchanging
![image](https://user-images.githubusercontent.com/82469049/126213499-5d7028ce-5228-481f-91d5-ca1032556e5c.png)
MC Isn't frozen either.

**Comment by ExcessiveAmountsOfZombies** [comment]
Can you send more logs

**Comment by Daviel2** [comment]
Sure

**Comment by Daviel2** [comment]
[crash-2021-07-19_14.29.51-server.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/6843447/crash-2021-07-19_14.29.51-server.txt)

**Comment by ExcessiveAmountsOfZombies** [comment]
`	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$3(CardinalEntityInternals.java:101)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals$$Lambda$5480/41776164.apply(Unknown Source)`

That's not croptopia, that's Cardinal Components

`croptopia: Croptopia 1.3.1` also still using 1.3.1

Pretty sure this isn't an issue with Croptopia at all, other than the mangled config at the beginning which I could probably handle better to either not crash the game or tell the user exactly what is wrong and then let it crash still.

**Comment by Daviel2** [comment]
Hm, What should I do with the 'Loading Stuck' Issue?

**Comment by ExcessiveAmountsOfZombies** [comment]
Well the log you sent me would indicate that Cardinal Components is keeping the level from loading, I'd make sure all your mods are updated to the appropriate version before making an issue on their repo though

**Comment by Daviel2** [comment]
Alright, So Basically update all of the mods to the newest Released version for 1.16.5?

**Comment by ExcessiveAmountsOfZombies** [comment]
Yes, and if the issue persists with the same error as you just sent me, make an issue on the Cardinal Components github repo if they have one

**Comment by Daviel2** [comment]
Alright, Thank you
