### ISSUE TITLE
[Feature Request] Disabling tree worldgen in config

### ISSUE THREAD

**Issue by Kaperios** [ExcessiveAmountsOfZombies/Croptopia#180]
So, according to the wiki, the mod is only supposed to spawn the trees in vanilla biomes. I had created custom ones and the fruit trees still do spawn there as if these were regular plains biomes. The feature request is: Would you mind adding an option in the config file to disable tree worldgen in the mod? It never hurts to give more configuration options.

**Comment by ExcessiveAmountsOfZombies** [comment]
1.7.0 will add a tree config that lets you define as many biomes (or none) as you want for trees to spawn in
