### ISSUE TITLE
Jitpack build not working

### ISSUE THREAD

**Issue by MerchantPug** [ExcessiveAmountsOfZombies/Croptopia#182]
**Version**
FABRIC-1.5.0

**Platform**
Fabric

**Describe the issue**
I was planning on making the mod have compatibility with my own Fabric mod and I needed to get the mod into my modding environment via Jitpack for this.
The Jitpack build didn't work as it couldn't get artifacts because the plugin with the id maven couldn't be found.

**To Reproduce**
Add the mod as a dependency through Jitpack and try to build it.

**Other Mods**
Every mod included in each build.gradle

**Additional context**
Link to log from Jitpack.
https://jitpack.io/com/github/ExcessiveAmountsOfZombies/Croptopia/a004c55f73/build.log

**Comment by ExcessiveAmountsOfZombies** [comment]
> * What went wrong:
An exception occurred applying plugin request [id: 'fabric-loom', version: '0.8-SNAPSHOT']
> Failed to apply plugin 'fabric-loom'.
   > You are using an outdated version of Java (8). Java 16 or higher is required.
     The JAVA_HOME environment variable is currently set to (/usr/lib/jvm/java-8-openjdk-amd64).

fix this first, the maven plugin was removed in gradle 7 and it became maven-publish so maybe updating java to 16 will fix it

**Comment by MerchantPug** [comment]
Thank you for responding.
