### ISSUE TITLE
Cinnamon not harvesting in latest Fabric version

### ISSUE THREAD

**Issue by Muffintiem** [ExcessiveAmountsOfZombies/Croptopia#183]
I'm using Croptopia-1.17-FABRIC-1.5.0 and Cinnamon is not harvesting when I right click with any axe.

My current roster of mods is:
Terrarian Slimes
Entity Banners
Earth 2 Java
Mooblooms
Outvoted
Emerald Tools and More
Gobber 2
Bosses of Mass Destruction
New Caves
Better Nether
Better End
Magic Mirror
Nature's Compass
Bumblezone
All Stackable
Beeinfo
Biome Info
Low Fire
Mod Menu
Music Duration Reducer
Pettable
Roughly Enough Items
Stackable Potions
Status Effect Timer
Toro Health Damage Indicators
Totems Plus
Trinkets
VoxelMap
Plus all the necessary APIs and Libraries needed to run them

Also unrelated to this issue but I don't think salt comes as an ore in real life. Maybe you could rename it to Salt Block?

**Comment by ExcessiveAmountsOfZombies** [comment]
This worked for me when I tested it. Perhaps it was already harvested once?
