### ISSUE TITLE
Cant get any seeds

### ISSUE THREAD

**Issue by Razeeeeee** [ExcessiveAmountsOfZombies/Croptopia#186]
**Version**
Croptopia 1.16.4 1.3.6

**Platform**
Fabric
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
I'm not sure how to explain it, but i've been breaking tall grass in a plains biome for hours and havent gotten any other seeds besides seeds involved in the bewitchment mod. The trees are working + everything else, but i cannot find seeds

**Screenshots**
None

**Other Mods**
All of these are fabric
( I'm also listing the ones that are only add ons to help other mods run )
Flight rings
Adventurez
Architectury
Bewitchment
Cloth config
Dualriders
Editsign
Extraalchemy
Geckolib
Gravestones
Impersonate
Moborigins
Naturescompass
Optifabric
4 different origin mods (Mob, Classes, Enhanced, and the regular one)
Patchouli
Pehkui
Shelf
Ratsmischief
Sit
Somnus
Trinkets
Voidz
Xp storage

**Additional context**
None

**Comment by Razeeeeee** [comment]
Should've added i checked a cpl other biomes to see if that made a difference, it didn't

**Comment by ExcessiveAmountsOfZombies** [comment]
in older versions like that you need to be holding a hoe while breaking the grass

**Comment by yeete183** [comment]
maybe write that in the description please so others know

**Comment by backspa900** [comment]
Thank goodness someone else asked this already, I was losing my mind. Any tips how to get fruit out of the trees? I tried the hoe and an axe (and my fist, many many times), but nothing is dropping?

**Comment by ExcessiveAmountsOfZombies** [comment]
You would right click a fully grown fruit bearing leaf block and the fruit will pop off and the growth will be reset @backspa900
