### ISSUE TITLE
[Suggestion] Add Avocado Toast and Chocolate Ice Cream

### ISSUE THREAD

**Issue by IanQB** [ExcessiveAmountsOfZombies/Croptopia#188]
There's toast, there's avocado. Avocado + Toast = Avocado Toast

Also, you should be able to make chocolate ice cream, following the same recipe for all ice cream. (Sugar + Chocolate + Milk + Egg + Cooking Pot)

![ice cream maybe](https://user-images.githubusercontent.com/87546696/126002976-d5ac652f-1853-4afc-ba2c-16555c9dbdbf.png)
![avocado toast maybe](https://user-images.githubusercontent.com/87546696/126003078-f76dbb07-1781-4256-9ca4-4d5718972f1e.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
Very soon now!
