### ISSUE TITLE
composting

### ISSUE THREAD

**Issue by lovehernice** [ExcessiveAmountsOfZombies/Croptopia#190]
can't compost any seeds or fruits / veggies! I think this should be something def added

**Comment by ExcessiveAmountsOfZombies** [comment]
seeds, saplings, fruits and vegetables have been able to be composted for a while now, you may be on an older version of the mod

**Comment by kingstairs** [comment]
Actually, there is an issue with composting.

Minecraft = 1.17.1 Creative (Fabric) with MultiMC launcher

**Installed mods**

- Architectury 2.2.21
- BetterF3 1.1.5
- Croptopia 1.5.0
- Fabric API 0.37.1
- Mod Menu 2.0.3
- Patchouli 54

My minimal modded setup.

**Steps to reproduce:**

1. Enter world :-)
2. Create a composter
3. Give yourself some vanilla crops/seeds
4. Compost them - all get composted as expected
5. Give yourself some Croptopia crops/seeds
6. Compost them - the crops _do_ get composted, but there is no reaction from the seeds (no sound, visual effects, etc.). I forgot to test this with saplings.

Hope that helps.

**Comment by ExcessiveAmountsOfZombies** [comment]
The sound doesn't play if it doesn't add to the level in the composter, but either way it's working on my current testing environment so if it's broken now it shouldn't be in the next build

**Comment by kingstairs** [comment]
To clarify, when I try to compost a "valid" crop, there is a sound, and the animation (green sparks, hand movement, etc.), and inventory count changes. With Croptopia seeds, nothing happens at all (no animation, no inventory change, etc.)
