### ISSUE TITLE
[Issue/Help] Extending Dependant Tags

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [ExcessiveAmountsOfZombies/Croptopia#191]
I'm working on a mod to bridge between sandwichable and croptopia and i see that there is a "dependant" thing that includes item tags like salts.json. I think I'm completely lost on how to extend them, as i've put a file in the same relative place but it doesn't work.  

I'm not sure if this is a me problem or a minecraft problem. Any help would be appreciated.

**Comment by ExcessiveAmountsOfZombies** [comment]
{dependant} items get changed to the appropriate tag type when the jar is built, so anything marked with {dependant} turns to "c" since that's fabric's common tag. This is so I can make the common tags also be forge

**Comment by TheDrawingCoder-Gamer** [comment]
ah, i'm inexperienced with forge and fabric. so i would change the class path to c?

**Comment by ExcessiveAmountsOfZombies** [comment]
You shouldn't have to change anything? since I believe sandwichable is only fabric you can just assume that the "c" base tag is present and go from there

**Comment by TheDrawingCoder-Gamer** [comment]
cool

**Comment by TheDrawingCoder-Gamer** [comment]
well looking at the fabric jar apparently it uses "forge" as its thing
which is really janky.
when i use "forge" tag it doesn't work for me

**Comment by TheDrawingCoder-Gamer** [comment]
and it doesn't even compile correctly
```
"ingredients": [
    {
      "item": "croptopia:cooking_pot"
    },
    {
      "tag": "croptopia:milks"
    },
    {
      "item": "croptopia:salt"
    }
  ]
  ```

**Comment by TheDrawingCoder-Gamer** [comment]
i'm reopening this because it's not a me problem and something needs to be done to get around this awfulness

**Comment by ExcessiveAmountsOfZombies** [comment]
are you building the mod? check out the 1.17-Fabric branch and then build it with `gradlew :fabric:build -Plaunch_mod=c` 

https://github.com/ExcessiveAmountsOfZombies/Croptopia/tree/1.17-Fabric/common/src/main/resources/data/croptopia/tags/items 

there is no croptopia:milks tag, but there is a c:milks tag

https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/1.17-Fabric/common/src/main/resources/dependants/platform/tags/items/milks.json

**Comment by TheDrawingCoder-Gamer** [comment]
I'm not building from source, i'm using fabric 1.16.5 version
but i'll try building 1.16 branch

**Comment by TheDrawingCoder-Gamer** [comment]
i guess this is fixed in 1.17 but i'd have to update all my mods to 1.17. If this is fixed on 1.17 you can close this but it won't have solved _my_ problem

**Comment by ExcessiveAmountsOfZombies** [comment]
1.17 is when i improved on the tag system, before that each item was just `c:item` rather than `c:category/item` so if you look in the last fabric jar I posted `Croptopia-1.16.4-5-FABRIC-1.4.0.jar` on CF, you'll see all the items are in the `data/c/tags/items` folder and I believe the recipes all use the common tags

**Comment by TheDrawingCoder-Gamer** [comment]
Yep that would explain it, it seems the version in my mods folder is 1.4.0. Thank you for helping!

**Comment by TheDrawingCoder-Gamer** [comment]
* 1.3.0 i mean
