### ISSUE TITLE
Can't manage to get crops from tall grass (1.17 - Fabric)

### ISSUE THREAD

**Issue by loanenems** [ExcessiveAmountsOfZombies/Croptopia#192]
**Version**
Croptopia-1.5.0

**Platform**
Fabric

**Describe the issue**
As mentionned in the patchouli's doc, I tried hard to get seeds from tall grass (with and without hoe), but I never got anything apart from standard wheat seeds. I do found some seeds on the ground, but need to go really far from the spawn point to find these, since the world is already advanced. So I was looking forward to get them from tall grass :D 
I had the same issue on my server and on local world.

**To Reproduce**
Install the mod with fabric, start a world, and try to get seeds from tall grass.

**Screenshots**
I don't have any to describe usefuly the issue

**Other Mods**
![image](https://user-images.githubusercontent.com/35499448/126394673-bac94f1c-3f7b-4f37-9166-0979596506c0.png)

**Additional context**
Here's the server modlist (which is pretty much the same as my local config)
![image](https://user-images.githubusercontent.com/35499448/126394801-771da9cf-0aca-41a8-ba00-8b61fc355ede.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
does the croptopia config on the server have any of the crops populated in there?

**Comment by loanenems** [comment]
here's my croptopia config on the server.
![image](https://user-images.githubusercontent.com/35499448/126399044-9fa6bf65-42f1-4385-bb36-2e4fb3a5310f.png)
This is the default one. I tried to tweak the "use hoe" boolean but it didn't make any changes after server restart.

**Comment by ExcessiveAmountsOfZombies** [comment]
https://pastebin.com/vz1GZGz6
the seeds thing might be something I need to look into, but here is what you can replace the "seeds" category with to get them to drop

**Comment by loanenems** [comment]
Hello @ExcessiveAmountsOfZombies
Giving you a feedback about your pastebin config. It's working well now :) thank you !
