### ISSUE TITLE
[suggestion] Appleskin compatability

### ISSUE THREAD

**Issue by sarcoptid** [ExcessiveAmountsOfZombies/Croptopia#193]
**Version**
Which version of Croptopia are you using?
fabric 1.5.0
**Platform**
Which platform are you using Croptopia on?
(Fabric, Forge)
fabric

Not an issue, but not sure how to submit suggestions otherwise :0c Anyway, love the mod! It'd be great if it were compatible with Appleskin (a mod that shows the saturation and hunger values of food), so we know which foods suit the situation! Other quality of life changes that would be nice are allowing use of seeds or crops in composters, and maybe allowing animals to eat them? seeds for chickens, berries for foxes, sweet potatoes and yams for pigs, and other grains for cows and sheep, etc? 

Anyway, thanks for reading, and my apologies if I'm not using this correctly!

**Comment by ExcessiveAmountsOfZombies** [comment]
Croptopia should already be compatible with AppleSkin actually, the seeds and crops can be used in composters, and I've already made seeds work with chickens and parrots. Good idea for the rest though.
