### ISSUE TITLE
using croptopia with sandwhichable and putting croptopia tomato gives other mods seeds

### ISSUE THREAD

**Issue by yeete183** [ExcessiveAmountsOfZombies/Croptopia#196]
**Version**
1.16.4 fabric 1.4.0
**Platform**
Which platform are you using Croptopia on?
fabric

**Describe the issue**
putting croptopia tomato to make seeds instead gives sandwhichable seeds instead of the croptopia seeds

**To Reproduce**
get croptopia and sandwhichable and put croptopia tomato into crafting grid and will give sandwhichable seeds 

**Screenshots**
![Screenshot 2021-07-24 174007](https://user-images.githubusercontent.com/84253595/126861451-84a8cf86-031a-4f6f-b280-eb90f29b6dda.png)
![Screenshot 2021-07-24 174014](https://user-images.githubusercontent.com/84253595/126861452-5124bee3-125a-4e1e-afb2-97a8401df621.png)

**Other Mods**
![Screenshot 2021-07-24 174655](https://user-images.githubusercontent.com/84253595/126861501-7d78fd94-3748-4fbf-a10c-3fd23052d71a.png)
(scribbled out mods are my own custom mods i use personally)

**Additional context**

**Comment by ExcessiveAmountsOfZombies** [comment]
I don't think there is anything I can really do about it, but you can install polymorph if you want and then you can select my seeds or theirs https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric

**Comment by yeete183** [comment]
ah ok thx that will help :)
