### ISSUE TITLE
CROPTOPIA cinnamon is not working at all

### ISSUE THREAD

**Issue by ReSendIT** [ExcessiveAmountsOfZombies/Croptopia#198]
Croptopia-1.17-FABRIC-1.5.0
Fabric

Cinnamon trees can grow, but cant seem to produce cinnamon, and the leaves dont register as a block

Grow a cinnamon tree and the leaves dont display properly

![image](https://user-images.githubusercontent.com/87950829/126913857-3ca89ac2-646a-4d2b-b608-f852a8f4080a.png)

![image](https://user-images.githubusercontent.com/87950829/126913867-d45d606a-ba31-4ea7-a7ae-e1f994c75eb4.png)

I grew the tree with bonemeal and cannot rightclick the trunk w bonemeal or hand.

Thanks in advance!

**Comment by ExcessiveAmountsOfZombies** [comment]
Strip the tree with an axe and it should drop cinnamon

**Comment by ReSendIT** [comment]
> a

Well. It does work! Thank you for anserwing my ridiculous request! much appreciated.

**Comment by ExcessiveAmountsOfZombies** [comment]
all good!
