### ISSUE TITLE
Crafting Recipe Issues

### ISSUE THREAD

**Issue by tydapo1** [ExcessiveAmountsOfZombies/Croptopia#20]
Cherry Pie, Tuna Sandwich, Cheese Cake, Snicker Doodle, and Banana Nut Bread do not have recipes in-game. (The Cherry Pie recipe exists in the code, but it results in an Apple Pie, and also seems to be using cheese instead of cherry... kinda funny, but probably not intentional). Also, Vanilla currently seems to be unobtainable, so several Banana Cream Pie, Vanilla Ice Cream, and Yam Jam cannot be crafted in Survival.

EDIT: Just found out that Banana Smoothies and Strawberry Smoothies cannot be crafted due to Fruit Smoothies using an all-inclusive tag that INCLUDES Bananas and Strawberries. Trying to make a Banana or Strawberry Smoothie results in a generic Fruit Smoothie.

**Comment by ExcessiveAmountsOfZombies** [comment]
these are fixed now except for the ones in 67. thanks
