### ISSUE TITLE
coffe drops fully processed coffee

### ISSUE THREAD

**Issue by yeete183** [ExcessiveAmountsOfZombies/Croptopia#200]
**Version**
1.4.0

**Platform**
fabric

**Describe the issue**
coffee when harvested drops fully processed coffee

**To Reproduce**
harvest coffe

**Screenshots**

https://user-images.githubusercontent.com/84253595/126943032-75cad1a3-5652-43cd-a55e-b445d2d18979.mp4

**Other Mods**
![Screenshot 2021-07-24 174655](https://user-images.githubusercontent.com/84253595/126942473-c05c984a-b476-4ef1-b2dd-f114bc892624.png)

**Additional context**

**Comment by ExcessiveAmountsOfZombies** [comment]
I don't really plan on updating the 1.16 fabric version at this point, but if you want you can make a datapack following
data/croptopia/loot_tables/blocks/coffee_crop.json

and have the contents be the contents of this file https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/1.17-Fabric/shared/src/main/resources/data/croptopia/loot_tables/blocks/coffee_crop.json

that will fix the issue
