### ISSUE TITLE
Book issues

### ISSUE THREAD

**Issue by VoidLock92** [ExcessiveAmountsOfZombies/Croptopia#202]
**Version**
1.5.0

**Platform**
Fabric

**Describe the issue**
The frying pan and cooking pot in the book are flipped. Clicking Frying pan leads to cooking pot and vice versa.

**To Reproduce**
Search in the book for cooking equipment

**Screenshots**
![image](https://user-images.githubusercontent.com/21327041/127728403-39f744f4-79a4-45bb-be9c-a460e4a13d13.png)

**Other Mods**
Patchouli books

**Comment by VoidLock92** [comment]
Also even with disable salt ore in the config salt ore is still enabled and required.

**Comment by ExcessiveAmountsOfZombies** [comment]
Thank you, both issues will be fixed in a future release
