### ISSUE TITLE
Am uh weird png file included.

### ISSUE THREAD

**Issue by RDKRACZ** [ExcessiveAmountsOfZombies/Croptopia#203]
Probably a joke but 118 KB is kinda big for a useless image.

https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/master/common/src/main/resources/assets/croptopia/icon.PNG

**Comment by ExcessiveAmountsOfZombies** [comment]
Herobrine is essential to the development of croptopia, but he can be compressed
