### ISSUE TITLE
Food with no recipes?

### ISSUE THREAD

**Issue by SOUTHERNCLASSIST** [ExcessiveAmountsOfZombies/Croptopia#204]
How do you not have recipes for green beans, cauliflower and asparagus? These are just the ones I found from what I had in my inventory. Why just add clutter to inventories for useless items?

**Comment by RDKRACZ** [comment]
Just eat them?

**Comment by HadariYao** [comment]
Dish suggestions: Green Bean Casserole(onions, green beans, cheese(use cooking pot)) Roasted Cauliflower(cauliflour, furnace), Grilled Asparagus( black pepper, lemon, asparagus(use pan))

**Comment by ExcessiveAmountsOfZombies** [comment]
33 new items will be added in 1.7.0 that focused on unused crops!
