### ISSUE TITLE
[Suggestion] A way to disable crops/seed drops in the config

### ISSUE THREAD

**Issue by Raithion** [ExcessiveAmountsOfZombies/Croptopia#206]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Croptopia is currently incompatible with a few popular cooking mods, due to having duplicate crops that can't be disabled on either end. Rather than asking multiple other mod authors to add config options for their crops, I figured it'd be easier to just ask here, since this is the "big food mod" among the ones I use.

I'd love to be able to disable some of Croptopia's crops to avoid duplicates in a modpack. This mod has lots of potential with Farmer's Delight's cooking system for example, but they can't be used together since they both have 4 of the same crop.

**Comment by ExcessiveAmountsOfZombies** [comment]
What I would recommend is using datapacks to achieve what you're looking for. Lets take the [cabbage loot table](https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/foreign/shared/src/main/resources/data/croptopia/loot_tables/blocks/cabbage_crop.json) as an example. You also have Farmer's Delight installed and don't want my items to drop (😢) what you can do is edit
`"name": "croptopia:cabbage"` -> to `"name": "farmersdelight:cabbage"` and the block now drops farmers delight cabbage.
Edit the two places where `"name": "croptopia:cabbage_seed"` appears ``"name": "farmersdelight:cabbage_seeds"`` and now whenever your harvest my crops only Farmer's delight items will drop. This also works in reverse, so you could edit their loot tables to only drop my crops if you wanted.

Only thing you need to know how to do is how to set up a [datapack](https://minecraft.fandom.com/wiki/Data_Pack), you can follow the file structure for the cabbage loot table to see how it should be set up as well as this datapack wiki entry.
