### ISSUE TITLE
[BUG] Drinkable Items Do Not Restore Hunger/Saturation

### ISSUE THREAD

**Issue by tydapo1** [ExcessiveAmountsOfZombies/Croptopia#21]
It seems that any of the drinkable items do not restore ANY hunger/saturation whatsoever when consumed. This is odd because AppleSkin acknowledges the amount of hunger and saturation that the item should restore, but upon consumption, nothing happens. The gif below demonstrates this in effect.

No gameplay-altering mods were enabled while this was occuring.
![CroptopiaDrinkingBug](https://user-images.githubusercontent.com/16727719/99343087-328a6e00-285b-11eb-87c3-8d2b03ae9af4.gif)

**Comment by ExcessiveAmountsOfZombies** [comment]
This will be fixed in the next version, interestingly it works if you have them stacked

**Comment by ExcessiveAmountsOfZombies** [comment]
ok i've released 1.0.6 now and this is fixed.
