### ISSUE TITLE
Composting does not accept Croptopia seeds

### ISSUE THREAD

**Issue by kingstairs** [ExcessiveAmountsOfZombies/Croptopia#212]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.6.0

### What happened?

Reported previously for 1.5.0 (#190) but closed. Easy to repeat with current release:

1. Creative mode (Windows, MultiMC) - only mods are Fabric API & Croptopia - minimum required
2. Create a composter
3. Pick up some vanilla seeds and fruits - e.g., wheat seeds, apples
4. Compost them - both seeds and fruits are composted, with appropriate visuals and sounds.
5. Collect some Croptopia crops and seeds - whatever is handy in the biome
6. Compost them - the crops (e.g., peppers, oranges) compost normally. With seeds, nothing happens at all.

Since the crops work but not the seeds, I'm guessing there is a tag or flag missing on the seed item definition(s).

Mods were downloaded directly from CurseForge.

### Relevant log.

Here is the _minimal_ mod list demonstrating the issue (Fabric API + Croptopia):
[15:50:57] [main/INFO]: Loading for game Minecraft 1.17.1
[15:50:58] [main/INFO]: [FabricLoader] Loading 49 mods:
	- croptopia@1.6.0
	- fabric@0.37.1+1.17
	- fabric-api-base@0.3.0+a02b446318
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.2+a02b446318
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.12+6cefd57718
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.6.0+a02b446318
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
	- fabricloader@0.11.6
	- java@16
	- minecraft@1.17.1

There is nothing else in the log of value - nothing is output when I am composting.

### Additional information.

Let me know if you need any system/Java-level information.

**Comment by ExcessiveAmountsOfZombies** [comment]
Can you upload a video to streamable or something? is there a specific seed that isn't working or is it all of them? I can't reproduce this

**Comment by kingstairs** [comment]
So far, any seed seems to reproduce it. Let me try creating a new MC instance from scratch, in case this issue is related to mod updating - something MC is caching at the instance level.

I created a new 1.17.1 MC instance (in MultiMC), added Fabric, Fabric API and Croptopia - all current versions. Created a new random seed Creative world. Problem still exists.

Found something new from my testing:
Chile peppers, ginger and vanilla do not compost (the crops, not the seeds). That may apply to other crops, but those are the ones I found from a few minutes testing. Note that I have not checked if this is an issue in my other instances - just happened to discover it as chile plants spawned next to me. Other crops (soybeans, yellow peppers, banana sapling) compost normally. Again, no Croptopia seeds will compost.

Attaching full log from the run: [minecraft-log-2021-08-05.zip](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/6942058/minecraft-log-2021-08-05.zip)

I'll see if I can record a video to demonstrate.

**Comment by kingstairs** [comment]
Okay, I made a brief video demonstrating the issue, using the same steps from my original report: https://youtu.be/0060yOldpXU
This is a new world in the same test environment I documented and logged above.
Again, this is completely reproducible in my environment - I just create a new world and the problem exists. 

I am puzzled that you still cannot reproduce this (as a developer myself I know reproducibility is key to identifying an resolving any issue). It suggests this could be something _environmental_ - maybe something about the MultiMC environment, or even the Java version I use? I'm not a MC modder, so I don't know how those might interact with a mod.

Let me know what else you need

**Comment by ExcessiveAmountsOfZombies** [comment]
63c465b20ebc338f08bbab61e1cca3362c68ce87 is where it broke

**Comment by ExcessiveAmountsOfZombies** [comment]
new version is uploading right now, sorry about that, composting was registered after the config was read, and the config didn't have any seeds in it because of the above commit removing it for whatever reason, so only people with older installations would be able to compost seeds. That won't be the case any more

**Comment by kingstairs** [comment]
Yay! Thank you. Glad I could contribute to the project in a little way,
