### ISSUE TITLE
[1.17.1] Add cinnamon leaves to Minecraft logs tag

### ISSUE THREAD

**Issue by kwpugh** [ExcessiveAmountsOfZombies/Croptopia#213]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Hi,

Can you please add cinnamon_leaves to the Minecraft leaves tag so that it can be leveraged by items using the leaves block tag logic?   

thank you.

**Comment by ExcessiveAmountsOfZombies** [comment]
I'll close this now since 1.7.0 is releasing soon. thank you!

**Comment by kwpugh** [comment]
Thanks.
