### ISSUE TITLE
Plum (other?) tree does not generate fruit 

### ISSUE THREAD

**Issue by mnsnownutt** [ExcessiveAmountsOfZombies/Croptopia#214]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.6.0

### What happened?

I created an orchard and planted one of every sapling I had gathered.  I planted a plum sapling and when it grew there were no plum leaf blocks.  I then opened a creative world and tested it and it seems like 1 out of 5 or 6 plum trees grow without the plum leaf blocks.  I did not test any other trees.

### Additional information.

[modlist.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/6950985/modlist.txt)

**Comment by ExcessiveAmountsOfZombies** [comment]
closing this as 1.7.0 is coming soon
