### ISSUE TITLE
Place Recipe Book On Lectern

### ISSUE THREAD

**Issue by ajsayko** [ExcessiveAmountsOfZombies/Croptopia#215]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Love the mod in general, latest patch works great as of 8/8/21.

The only ask so far would be to be able to place the Croptopia guide onto the Lectern like any other written-in book.

Cheers!

**Comment by ExcessiveAmountsOfZombies** [comment]
This is probably better suited as a suggestion to [Patchouli](https://github.com/VazkiiMods/Patchouli), since it's their documentation mod that I am using.
