### ISSUE TITLE
Cinnamon and Salt not generating anymore

### ISSUE THREAD

**Issue by Muffintiem** [ExcessiveAmountsOfZombies/Croptopia#216]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17

### Croptopia version.

1.6.1

### What happened?

Cinnamon and Salt not generating. Could possibly be a conflict with Terralith since I updated Croptopia at the same time as I added Terralith but it could also just be Croptopia by itself. All the other crops are still generating including fruit trees. The fruit trees could stand to be a bit more common but at least they are generating.

**Comment by Muffintiem** [comment]
I tested it without Terralith and salt still didn't generate but Cinnamon did so at least Cinnamon is an incompatibility with Terralith. Salt there's an alternate way to obtain it so it's not as big a deal it's not generating but there's no way to obtain Cinnamon without Cinnamon trees. If the seedlings were chest loot I'd be able to at least grow the trees.

**Comment by lambdalegend** [comment]
Could you tell me the alternate way to obtain salt? It's not generating for me in rivers anymore.

**Comment by ExcessiveAmountsOfZombies** [comment]
get a bucket of water and put 3 glass around it like you're making glass bottles and you'll get water bottles that you can put into a furnace to turn into salt

**Comment by lambdalegend** [comment]
> get a bucket of water and put 3 glass around it like you're making glass bottles and you'll get water bottles that you can put into a furnace to turn into salt

Thank you!

**Comment by Wululululu** [comment]
I have this same issue. Just plain Minecraft 1.17.1 + Fabric 0.40.1 + Croptopia 1.6.1 for Fabric. Nothing else. 
Walnut Trees generate in Jungles (I guess instead of Cinnamon) and there are no salt deposits in any rivers.
Then I retested with Croptopia 1.6.0 which seemes to introduce this issue. 
Going back to 1.5.0 fixes the issue and generates salt in rivers, cinnamon in jungles, and no walnut trees in jungles.

**Comment by ExcessiveAmountsOfZombies** [comment]
I'll probably release a minor version (1.6.3) that has fixes for this.

**Comment by ExcessiveAmountsOfZombies** [comment]
definitely will be fixed in 1.7.0
