### ISSUE TITLE
Tree Fruits do not Respect Graphic Settings

### ISSUE THREAD

**Issue by milkev** [ExcessiveAmountsOfZombies/Croptopia#217]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.6.1

### What happened?

Turned my graphic settings to fast, croptopia tree fruits were still transparent. only tested with the nectarine crop, but i imagine its the same for all of them.

### Additional information.

![2021-08-11_15 54 12](https://user-images.githubusercontent.com/22010128/129108520-70115ddf-b323-4736-8926-843d40143b28.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
![image](https://user-images.githubusercontent.com/30448663/130369191-3f89dd21-beab-4f3a-bf7e-fafcd67b01e9.png)
Because the fruit textures are overlaid onto the leaves the result ends up looking kinda ugly. I don't think I'll be implementing this fix
