### ISSUE TITLE
Salt Ore Not Generating?

### ISSUE THREAD

**Issue by krelios** [ExcessiveAmountsOfZombies/Croptopia#22]
I've been playing with this mod for a couple of weeks but have yet to see any salt ore generate in the world. I did a quick glance through the source and don't see anything adding it to world gen either. Is it just not in yet? There are lots of recipes that need it.

**Comment by ExcessiveAmountsOfZombies** [comment]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/master/src/main/java/me/thonk/croptopia/mixin/DiskMixin.java they're added here. there is an option to disable the ore generation of salt but it's set to false by default. You can check in the options.json in the croptopia config folder

**Comment by krelios** [comment]
Hmm. I wonder why I’m not seeing any then. What Y level should they be found?

________________________________

**Comment by ExcessiveAmountsOfZombies** [comment]
They generate in river beds similar to clay
