### ISSUE TITLE
[Suggestion]More uses for seeds

### ISSUE THREAD

**Issue by HadariYao** [ExcessiveAmountsOfZombies/Croptopia#220]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

I think it would be a welcomed change to make seeds compostable. Other usages could be taming Parrots or breeding chickens.

**Comment by ExcessiveAmountsOfZombies** [comment]
Seeds can already be composted, they can also be used for chicken and parrot breeding.

**Comment by HadariYao** [comment]
I got it working after installing a newer version
