### ISSUE TITLE
Tree Crop Blocks Have no Item Forms

### ISSUE THREAD

**Issue by milkev** [ExcessiveAmountsOfZombies/Croptopia#221]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.6.1

### What happened?

There is no way to obtain the tree crop blocks. 

The main issue seems to be that theres no item variant of them in the game, thus making them unobtainable even though creative or rei. the only way a player can obtain them is with the /setblock or /fill commands.

From my little knowledge of modding, it shouldnt be super hard to add all of them as items, and just make them drop if you use shears or a silk touch item on them. I think it would a great addition, especially for anyone looking to make a more customized farmland area with tree crops... or just a tree crop thats reasonable to harvest from

Sorry if this should have been a feature request, kinda seeing it as a bug its pretty much 'block unobtainable'.

**Comment by ExcessiveAmountsOfZombies** [comment]
This is intentional, I might be willing to add them to the creative menu so they could be place from creative, but they don't behave like normal leaves as it is, there is no persistence (and as a design choice I don't want to add persistence) so they'll decay if they aren't attached to logs
