### ISSUE TITLE
Seeds Not Spawning In Other Biomes

### ISSUE THREAD

**Issue by FireRRabbit** [ExcessiveAmountsOfZombies/Croptopia#223]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.16.5

### Croptopia version.

1.4.2

### What happened?

So, I spawned in a plains biome, where all the seeds for that biome spawned normally. However, when I went to go harvest some taiga seeds, none of them ever spawned when I broke ferns. 

I don't know if this is a config issue, but it should be at default because I never touched it since I downloaded the mod.

### Relevant log.

[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/6985020/latest.log)

### Additional information.

![image](https://user-images.githubusercontent.com/88907745/129415054-c1759ea4-2b46-40cf-806d-924496b01fec.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
No seeds are configured to drop in taiga type biomes, they are, however configured to drop in biomes with these types https://github.com/ExcessiveAmountsOfZombies/Croptopia/wiki/Crops
