### ISSUE TITLE
Crops not spawn with biome ùpd

### ISSUE THREAD

**Issue by Cabouunymous** [ExcessiveAmountsOfZombies/Croptopia#224]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.16.5

### Croptopia version.

1.4.0

### What happened?

I'm using Oh The Biomes You'll Go and no crops spawn in the world and i wanna know if it's possible to resolve this or it's impossible ?

**Comment by ExcessiveAmountsOfZombies** [comment]
All biomes are supposed to take a category that I use to determine where seeds should spawn, I believe BYG has a ton of biomes so perhaps you just aren't in the right category. Crops also don't spawn in 1.4.0, you have to use a hoe on grass to drop them

**Comment by Cabouunymous** [comment]
mb im in 1.2.0 version but always i try to tp in a lot of biome nothing so maybe really not lucky but apparently i did something wrong idk what but thx for ur anwser

**Comment by Cabouunymous** [comment]
Ok i've get out all mods and only let fabric api croptopia and patchouli and i still have nothing sounds like i've the wrong version ? But idk which version i need so for the 1.16.5

**Comment by ExcessiveAmountsOfZombies** [comment]
the actual crop spawning in the world wasn't added until the 1.17 version, if you're on 1.16.5 you need to use a hoe on grass in certain biome categories https://github.com/ExcessiveAmountsOfZombies/Croptopia/wiki/Crops

**Comment by Cabouunymous** [comment]
Perfect thx
