### ISSUE TITLE
Trouble eating the produced food in Medieval Minecraft Fabric

### ISSUE THREAD

**Issue by CyberMk56** [ExcessiveAmountsOfZombies/Croptopia#225]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.6.1

### What happened?

i have made multiple types of food including apple juice and toast but unable to consume them. i have been able to eat vanilla foods like porkchops and cooked mutton.

**Comment by ExcessiveAmountsOfZombies** [comment]
I'm sorry I'm unsure what would prevent you from eating toast and apple juice. seems like a one off kind of deal
