### ISSUE TITLE
Salt recipe doesn't exist Forge 1.16.5

### ISSUE THREAD

**Issue by BradMcChad** [ExcessiveAmountsOfZombies/Croptopia#226]
Salt recipe doesn't exist Forge 1.16.5

**Comment by ExcessiveAmountsOfZombies** [comment]
Older forge versions don't have a salt recipe, you have to find it in rivers. No version was specified

**Comment by Klyuchtxc** [comment]
@ExcessiveAmountsOfZombies But man.. I'm playing version 1.16.5 and after walking KILOMETERS I didn't find a single block of salt. Why should Netherite be less common than salt? As I understand it, this is a bug, but when can we expect its fix for forge 1.16.5?

**Comment by ExcessiveAmountsOfZombies** [comment]
@Klyuchtxc use version 1.4.2 and it has been fixed there. Salt is also renewable in that version
