### ISSUE TITLE
Can't place Cooking Pot

### ISSUE THREAD

**Issue by GrumpyGrama** [ExcessiveAmountsOfZombies/Croptopia#227]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.17

### What happened?

Am using All of Fabric 4- 0.00.9 modpack in CurseForge. I crafted the Cooking Pot, but can't place it on any surface to craft recipes. There's no wiki or step-by-step instructions that I can find, so I'm unsure if I'm just doing it wrong or it's a bug. mod pack

### Additional information.

I'm using all the mods in the All of Fabric 4- 0.00.9 modpack.

**Comment by ExcessiveAmountsOfZombies** [comment]
The cooking pot is just used in the crafting table for recipes. AOF4 I believe has REI so it should show you recipes that make use of the cooking pot

**Comment by GrumpyGrama** [comment]
I've tried placing the pot on/in/and holding while using the crafting table and am still unable to make any food item from Croptopia. I am able to access the recipes, just not use them.  Not sure how to use REI to make what requires the cooking pot. Am trying really hard not to use a cheat.

**Comment by ExcessiveAmountsOfZombies** [comment]
I believe the default key to see the usages of an item with REI is 'u'
