### ISSUE TITLE
Apple

### ISSUE THREAD

**Issue by Shiplipt** [ExcessiveAmountsOfZombies/Croptopia#228]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.6.1

### What happened?

if i do right click in a leave that contains an apple it crash my game.

**Comment by ExcessiveAmountsOfZombies** [comment]
You'll need to send a crash log because I can't replicate this.
