### ISSUE TITLE
Fruit trees are not guaranteed to have fruits

### ISSUE THREAD

**Issue by Brun333rp** [ExcessiveAmountsOfZombies/Croptopia#229]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.16.5

### Croptopia version.

1.4.2

### What happened?

When trying to grow a fruit tree, it may generate with no fruits at all, wich might be a problem if you have few or just a single sapling(s)

**Comment by ExcessiveAmountsOfZombies** [comment]
Hmm, I've ended up increasing the chances trees will spawn with fruit and you can also right click with saplings on the proper leaves to turn them into fruit bearing leaves. not sure if 1.4.2 had that feature. 1.7.0 will have the former.
