### ISSUE TITLE
Incompatible with Minegate - Moreblocks

### ISSUE THREAD

**Issue by Alkiasan** [ExcessiveAmountsOfZombies/Croptopia#231]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.6.1

### What happened?

Currently, worlds will not be able to be created/loaded with both Croptopia and Minegate installed. Relevant logs are attached.
Seems to be similar to the issue stated in this report:
https://github.com/MrFantiVideo/MineGate/issues/5
Disabling mixins on Minegate's side does work, but needs to be done both clientside and serverside so it isn't very practical..

### Relevant logs

https://gist.github.com/Alkiasan/4e82604084f7707883006b63f5359b04

**Comment by ExcessiveAmountsOfZombies** [comment]
i'm removing the json config files in the next version i upload so it might not even be an issue. seems like it causes problems with other mods though
