### ISSUE TITLE
1.6.1 forge version right clicking fruit on fruit trees and nothing happens

### ISSUE THREAD

**Issue by Tolbin** [ExcessiveAmountsOfZombies/Croptopia#234]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.17.1

### Croptopia version.

Croptopia-1.17-FORGE-1.6.1.jar

### What happened?

Can't right click fruit on trees to get it to drop anymore. Breaking the block drops the fruit (tested apples).
Went back to version Croptopia-1.17-FORGE-1.6.0.jar and right clicking to get drops work again.
I have other mods as well so might be one of them that messes with it. Just wanted to log this in case it's relevant.

**Comment by ExcessiveAmountsOfZombies** [comment]
Uploading 1.6.2 and that fixes right click harvesting
