### ISSUE TITLE
I suggest adding cooking stations not in the form of crafting

### ISSUE THREAD

**Issue by MaksymKurny** [ExcessiveAmountsOfZombies/Croptopia#236]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Why not make a frying pan that you need to put on a smoke lance for cooking, or a cooking pot. The all purpose food press will need to be placed in a cauldron with lava (well, or craft this cauldron)

**Comment by RDKRACZ** [comment]
I hate food mods that add new blocks just to make food. It doesn't make any sense if **vanilla lets you make a cake in a crafting table**. Imo even a frying pan is bad unless you remade whole Minecraft's food processing system to make it more realistic, then frying pans are a good idea.

**Comment by ExcessiveAmountsOfZombies** [comment]
If I do this it would probably be in the form of an addon mod, rather than built into Croptopia

**Comment by Entralia** [comment]
Having blocks serves an aesthetic purpose, sort of like the workstations in 'farmer's delight'
It's much less about just making the food, but having the decoration blocks to add to the vibes~

On that note, would it be possible to have the tools (frying pan, cooking pot, mortar & pestle, all-purpose food press) be place-able (even if you havent figured out their mechanics)?
