### ISSUE TITLE
game unable to load patchouli books

### ISSUE THREAD

**Issue by TobiPeterG** [ExcessiveAmountsOfZombies/Croptopia#238]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.6.1

### What happened?

I had a look at the log, found that patchouli can't load the books from craftopia

(e.g. Failed to load croptopia:patchouli_books/guide/en_gb/entries/utensils/mortar_and_pestle.json. Switching to fallback.)

### Relevant log.

[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/7111454/latest.log)

**Comment by RDKRACZ** [comment]
This happens when you don't have Patchouli installed - Croptopia doesn't bundle it.

**Comment by RDKRACZ** [comment]
However looking at your log, you have installed Patchouli

**Comment by TobiPeterG** [comment]
> However looking at your log, you have installed Patchouli.
> Your log also indicates patchouli books cannot be loaded from ither mods so this probably isn't croptopia issue.
> 
> ```
> Failed to load betterend:patchouli_books/guidebook/en_gb/entries/rituals/infusion_ritual.json. Switching to fallback.
> Failed to load totemicoverhaul:patchouli_books/tutorialbook/en_gb/categories/activators_category.json. Switching to fallback.
> ```

Humm OK, thank you!

Or might it be that patchouli changed its api? 🤔

**Comment by williewillus** [comment]
In Patchouli 1.17, all identifiers have to be fully qualified. I see that a lot of the things in your book aren't.

We have documentation about this, see [here](https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-117#fully-qualified-names). FYI at the time of writing Github Pages is being really slow at building so that link might 404 for an hour or so.

**Comment by ExcessiveAmountsOfZombies** [comment]
Thank you for the information willie.

This will be fixed in the next version I upload
