### ISSUE TITLE
No info on jerky

### ISSUE THREAD

**Issue by TheWarlike** [ExcessiveAmountsOfZombies/Croptopia#239]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.16.5

### Croptopia version.

1.16.4

### What happened?

Looking in the recipes and found jerky with no information on how to make it. Not sure if it's something obvious or not, but didn't seem right since it must be a food item that's made not found.

**Comment by ExcessiveAmountsOfZombies** [comment]
jerky has no recipe right now, I've removed it from the patchouli book for now as well.
