### ISSUE TITLE
Unable to harvest fruit on tree leaves

### ISSUE THREAD

**Issue by bryann5646** [ExcessiveAmountsOfZombies/Croptopia#24]
Tried clicking on them with an open hand and tools. The blocks only break and nothing else. There is also no HUD information shown when hovering the cursor over one. I realize this mod is still in beta but did you include a way to get the fruit? At the moment, only way I can is by going in creative mode.

**Comment by ExcessiveAmountsOfZombies** [comment]
Not sure what would be up, it works for me... are you right clicking on them when they're fully grown?

**Comment by bryann5646** [comment]
(sigh) I feel somewhat dumb now.... since there was no hud info displayed, I had no way of knowing there were growth stages. Tested with bonemeal and it worked. Sorry, closing issue.
