### ISSUE TITLE
[Question/Suggestion] Can you make it clear how we could add our own recipes?

### ISSUE THREAD

**Issue by Raavea** [ExcessiveAmountsOfZombies/Croptopia#240]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Rather than myself and others coming in here and requesting modifications to recipes or additional recipes, if there was a clear template and guide on adding them ourselves in your Wiki, I'm sure I wouldn't be the only one to use it! So, forgive me, I know there's a built in way to add recipes to Minecraft, but I'm not super familiar with it + as I'd want to re-use icons that you already have in the mod for the final foodstuffs (but don't know how/what they're called/where they're stored) it'd be nice to have a clear template to work from in the wiki.

I love cooking, but some of the recipes in the mod are either a bit off (bearing in mind I am from the UK and grew up eating British-Indian and British-Chinese fusion food, and that is what I cook now) or missing. Like, you have black beans, chilli, garlic, ginger... But I can't make black bean sauce! Or the croptopia chicken and rice recipe has olive oil in it, and if I used olive oil in chicken and rice (even just to fry the chicken) my mother would come back from the dead to HAUNT me. :')

So yeah there's a BUNCH of recipes I'd want to add, and I could + would happily use existing icons for them, I just don't know how exactly. I'm sure with a bit of digging through your .jar I could maybe figure it out but a guide would mean that I, and others, could maybe do our own thing rather than continuously bothering you.

**Comment by ExcessiveAmountsOfZombies** [comment]
I can give you some resources for modifying the recipes

here is how you can create a datapack
https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack

and here is all the data I use in croptopia on github
https://github.com/ExcessiveAmountsOfZombies/Croptopia/tree/master/shared/src/main/resources/data
everything you'd want is in the croptopia folder, so you'll have to copy that structure in your datapack. then you can go to the recipes folder and look at what I have there.

If you enable advanced tooltips (F3+H) you can see the internal names of the croptopia items that you'd use for the recipes.

Hope this helps!

**Comment by ExcessiveAmountsOfZombies** [comment]
made a wip wiki page for this too https://github.com/ExcessiveAmountsOfZombies/Croptopia/wiki/Modifying-Recipes-(WIP)

**Comment by Raavea** [comment]
Thank you! <3
