### ISSUE TITLE
Can't find some trees.

### ISSUE THREAD

**Issue by damaster17** [ExcessiveAmountsOfZombies/Croptopia#241]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.16.5

### Croptopia version.

1.4.2

### What happened?

I can't seem to find Cinnamon trees, Cashew, Pecan, and Almonds. All the dark oak trees are walnuts. I have searched a lot of biomes. I have biomes o plenty on.

**Comment by ExcessiveAmountsOfZombies** [comment]
generally i'm not working on forge 1.16.5 anymore. I've been considering porting things back once 1.7.0 is released though. we'll see.

**Comment by ExcessiveAmountsOfZombies** [comment]
I didn't think I'd take this long for 1.7 so I'm actually going to focus on 1.17.1 and 1.18 going forward, don't think I really want to deal with the java 8 -> 16 bump
