### ISSUE TITLE
Pumpkin Spice Latte returns only One Glass Bottle when consumed

### ISSUE THREAD

**Issue by cassowarycasper** [ExcessiveAmountsOfZombies/Croptopia#242]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.17

### Croptopia version.

1.17 Fabric

### What happened?

When you make coffee you use one water bottle. When you make a pumpkin spice latte, it requires an additional water bottle. Drinking a pumpkin spice latte only returns one water bottle instead of two.

**Comment by ExcessiveAmountsOfZombies** [comment]
this'll be fixed soon
