### ISSUE TITLE
Smelting Water Bottles Consumes Them

### ISSUE THREAD

**Issue by cassowarycasper** [ExcessiveAmountsOfZombies/Croptopia#243]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17

### Croptopia version.

1.17

### What happened?

When smelting croptopia water bottles to obtain salt, the bottle itself becomes permanently consumed.

**Comment by ExcessiveAmountsOfZombies** [comment]
this is actually a design choice. You get 16 water bottles for 3 glass, if I gave glass bottles back it'd be a better method for crafting glass bottles. I guess if you want to make a head canon you could say that putting the heat from the furnace just damages the bottle and you discard it after
