### ISSUE TITLE
Way too many bottles...

### ISSUE THREAD

**Issue by ItsNilin** [ExcessiveAmountsOfZombies/Croptopia#244]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

So to make croptopia's recipes you need to use the specific bottle by crafting it with a bucket. But when consumed it turns into a normal minecraft bottle leading to a huge stackup of normal glass bottles that i cant refill and use.

Id love a feature to just use normal water bottles or make some way to obtain the croptopia ones without ending up having to make more every single time i want to craft something.

**Comment by ExcessiveAmountsOfZombies** [comment]
I looked through the git history and I don't think the croptopia bottles that get crafted have ever returned an empty bottle. If you really want vanilla water bottles to work I'd recommend making a datapack and changing the waterbottles tag to include `minecraft:potion`
https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/master/shared/src/main/resources/dependants/platform/tags/items/water_bottles.json
