### ISSUE TITLE
Cannot plant seeds in Aquaculture 2 Farmland blocks

### ISSUE THREAD

**Issue by DragosIvan** [ExcessiveAmountsOfZombies/Croptopia#246]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.17.1

### Croptopia version.

1.6.2

### What happened?

Hello,

I am not sure if this is a bug, so my apologies in advance. I am trying to plant seeds in a Farmland block from the Aquaculture 2 mod - it's a Farmland that stays wet. I *think* it's a bug because seeds from other mods do work with those blocks, but not seeds from Croptopia, which made me think maybe the seed entities are missing some kind of property or whatnot.

Thank you for an amazing mod!

**Comment by ExcessiveAmountsOfZombies** [comment]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/pull/258 this PR which I ported to the forge version should fix this in 1.7.0 when it's released. Assuming that the aquaculture block extends the Farmland block of course.
