### ISSUE TITLE
Picking Fruit Causes Game Crash

### ISSUE THREAD

**Issue by RedRowBoat** [ExcessiveAmountsOfZombies/Croptopia#248]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.6.3

### What happened?

On my server, a player tried to right-click the fruit tree to pick the fruit and it crashed their game. We tried it again together and both of our games crashed.

### Relevant logs

Error: java.lang.IllegalArgumentException: Cannot get property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{croptopia:apple_crop}
Exit Code: -1

### Additional information

we are using a mod pack so there are around 50+ other mods in use but none conflict with croptopia or its functions

**Comment by ExcessiveAmountsOfZombies** [comment]
Meh, I should've asked for more logs so I could've seen the stacktrace sooner and then fixed this when I had more time. If you still have them laying around that'd be great but understandable if not.
