### ISSUE TITLE
Cannot Use Blast Furnace For Salt Smelting

### ISSUE THREAD

**Issue by cassowarycasper** [ExcessiveAmountsOfZombies/Croptopia#249]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17

### Croptopia version.

1.17 Fabric

### What happened?

You cannot smelt water bottles in a blast furnace to get salt. Only regular furnaces can be used.

**Comment by ExcessiveAmountsOfZombies** [comment]
will be added in 1.7.0. Thanks
