### ISSUE TITLE
Compatibility issue: Croptopia and Astromine

### ISSUE THREAD

**Issue by cooke-cookie-co** [ExcessiveAmountsOfZombies/Croptopia#25]
Compatibility issue:
Croptopia-1.0.5-1.16.X-FABRIC.jar and astromine-1.11.4+fabric-1.16.3.jar

Creative menu not displaying vanilla blocks and items

This problem happens only when both mods are installed, and regardless of other mods.

**Comment by RDKRACZ** [comment]
Since it's Astromine's (dependency, now fixed but not yet updated in Astromine) fault can you close this issue?

**Comment by cooke-cookie-co** [comment]
> Since it's Astromine's (dependency, now fixed but not yet updated in Astromine) fault can you close this issue?

I don't understand what you're saying, can you please explain?

**Comment by cooke-cookie-co** [comment]
I fixed this problem by downloading Roughly Enough Items, but I thought the developer would like to know anyways.
