### ISSUE TITLE
Croptopia seems to get weird when paired with other food/farming mods

### ISSUE THREAD

**Issue by scarfapalooza** [ExcessiveAmountsOfZombies/Croptopia#254]
I don't know if this seems annoying or idk but I at least want to know if there are mods that specifically don't gel together? I know that some recipes from other mods end up making croptopia items but that's not too bad, my big issue is that it doesn't seem to let me pick other fruits aside from apples, I tried picking an orange and nothing would drop no matter what I do. I'm using 1.16.5 for this so this is based on 1.16.5 croptopia.

**Comment by ExcessiveAmountsOfZombies** [comment]
I mean there are some bugs in some 1.16.5 versions of croptopia that a bit weird, but I don't know of any mods specifically that croptopia doesn't work well with (other than world gen)
