### ISSUE TITLE
Vanilla crop villager trades seem to have been removed

### ISSUE THREAD

**Issue by astocky** [ExcessiveAmountsOfZombies/Croptopia#255]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.17.1

### Croptopia version.

1.6.2

### What happened?

I have cycled a farmer villager trades over and over and while the croptopia crop trades seem to repeat, i can't get a single bread/beet/potato/carrot/wheat trade. Is there a bug that has remove vanilla villager trades?

**Comment by ExcessiveAmountsOfZombies** [comment]
1.7.0 will remove Croptopia trades from villagers, so you'll probably have farmers that still have Croptopia trades but any new villagers will be back to vanilla. Wasn't really a bug, it's just that there are so many crops it kinda ruins the chances of ever seeing a vanilla trade. It'll eventually be re-implemented when we add our own villager type.
