### ISSUE TITLE
Pepper confusion in recipes

### ISSUE THREAD

**Issue by Venaf** [ExcessiveAmountsOfZombies/Croptopia#259]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Not sure if this counts as a feature/enhancement or a bug, but Pepper and Chile Peppers seem to be reversed in several recipes (Chile Peppers in chicken and dumplings, tofu and dumplings, spaghetti squash, lemon chicken, chicken and rice, chicken and noodles, fried chicken, possibly pepperoni, though that could use both and still be accurate (can have cayenne pepper in it)).  Pepper is being used in Tamales, Stuffed Poblanos, Chili Relleno, and Refried Beans, when it should probably be Chile Peppers.

**Comment by ExcessiveAmountsOfZombies** [comment]
the ones with pepper were messed up, they should've had chile peppers like you mentioned. the rest are good
