### ISSUE TITLE
[Mod compat] drinks from Croptopia should fill thirst bar from Dehydration.

### ISSUE THREAD

**Issue by RDKRACZ** [ExcessiveAmountsOfZombies/Croptopia#26]
Reported to Dehydration too - https://github.com/Globox1997/Dehydration/issues/7

**Comment by RDKRACZ** [comment]
Guys please
"Can be done very easily.
Croptopia dev just have to add the drinks to the hydrating_drinks tag"

**Comment by ExcessiveAmountsOfZombies** [comment]
This will be added in the next version I publish on CurseForge.
https://github.com/ExcessiveAmountsOfZombies/Croptopia/commit/26fa0b2dfa6b1624a3512eeff38a6602779a6dae
