### ISSUE TITLE
Alternative guide

### ISSUE THREAD

**Issue by andres19992** [ExcessiveAmountsOfZombies/Croptopia#261]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Will it be possible to have an alternative, not patchouli guide for this mod? I can't have access to the book because the forge version of patchouli hasn't been updated to 1.17.1

**Comment by ExcessiveAmountsOfZombies** [comment]
There will eventually be an actual wiki, but it's low priority given the options already present (patchouli in some cases and recipe mods like JEI)
