### ISSUE TITLE
not a actual feature

### ISSUE THREAD

**Issue by numberCRUSHER** [ExcessiveAmountsOfZombies/Croptopia#262]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

well my computer is a potatoe so i cant play on 1.16 or 1.17 soo you can make a version for 1.12? that will help me a lot

**Comment by ExcessiveAmountsOfZombies** [comment]
I cannot, I won't even support 1.16 anymore because of Java 8, don't feel very inclined to support a version that requires java 8 and hasn't been supported by anyone for many years.
