### ISSUE TITLE
Can't run 'Main' process because of errors from Croptopia

### ISSUE THREAD

**Issue by pumknboy** [ExcessiveAmountsOfZombies/Croptopia#263]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1.6.3

### What happened?

I have been working on my server, and I went to update to 1.17.1 Croptopia when I was greeted with, The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'croptopia'!
Exit Code: -1
Please Help!

### Relevant logs

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/20/21, 12:12 AM
Description: Rendering Particle

java.lang.NullPointerException: Cannot invoke "exm.h()" because "this.E" is null
	at ema.c(SourceFile:23)
	at eln.a(SourceFile:62)
	at elf.renderParticles(ParticleEngine.java:574)
	at elf.a(ParticleEngine.java:506)
	at eng.a(LevelRenderer.java:2110)
	at enb.a(GameRenderer.java:1531)
	at enb.a(GameRenderer.java:1153)
	at dvp.f(SourceFile:1112)
	at dvp.e(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ema.c(SourceFile:23)
	at eln.a(SourceFile:62)

-- Particle being rendered --
Details:
	Particle: ekg, Pos (1550.6442321039349,102.75,-5516.803573574774), RGBA (1.0,1.0,1.0,0.060000584), Age 110
	Particle Type: PARTICLE_SHEET_TRANSLUCENT
Stacktrace:
	at elf.renderParticles(ParticleEngine.java:574)
	at elf.a(ParticleEngine.java:506)
	at eng.a(LevelRenderer.java:2110)
	at enb.a(GameRenderer.java:1531)

-- Affected level --
Details:
	All players: 2 total; [emm['pumkn_gamer'/42, l='ClientLevel', x=1476.60, y=112.00, z=-5510.44], emn['Tanjiro_Kamado_'/3485, l='ClientLevel', x=1475.63, y=112.00, z=-5510.54]]
	Chunk stats: 625, 399
	Level dimension: minecraft:overworld
	Level spawn location: World: (1256,84,-2548), Section: (at 8,4,12 in 78,5,-160; chunk contains blocks 1248,0,-2560 to 1263,255,-2545), Region: (2,-5; contains chunks 64,-160 to 95,-129, blocks 1024,0,-2560 to 1535,255,-2049)
	Level time: 14604584 game time, 156568 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at eji.a(ClientLevel.java:476)
	at dvp.c(SourceFile:2399)
	at dvp.e(SourceFile:747)
	at net.minecraft.client.main.Main.main(SourceFile:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1194665744 bytes (1139 MiB) / 2013265920 bytes (1920 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 4.10
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon HD 7700 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x683d
	Graphics card #0 versionInfo: DriverVersion=27.20.21002.112
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 27047.48
	Virtual memory used (MB): 22884.74
	Swap memory total (MB): 10765.71
	Swap memory used (MB): 447.65
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.17.1-OptiFine_HD_U_G9_pre26
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon HD 7700 Series GL version 3.2.14830 Compatibility Profile Context 21.4.1 27.20.21002.112, ATI Technologies Inc.
	Window size: 1360x715
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
	OptiFine Version: OptiFine_1.17.1_HD_U_G9_pre26
	OptiFine Build: 20210709-223930
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.14830 Compatibility Profile Context 21.4.1 27.20.21002.112
	OpenGlRenderer: AMD Radeon HD 7700 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

### Additional information

It still does it with no other mods.
Croptopia-1.17.1-FABRIC-1.6.3.jar
fabric-api-0.41.3+1.17.jar
My Fabric version is 0.11.7, 1.17.1

**Comment by ExcessiveAmountsOfZombies** [comment]
strange, not sure why a particle would point to croptopia. Are you sure the game was initializing? because it looks like you were on a server when it happened

**Comment by pumknboy** [comment]
nope, it just crashes on startup

**Comment by pumknboy** [comment]
my pc bluescreened and now it didnt work
idk
