### ISSUE TITLE
Unable to open the book 

### ISSUE THREAD

**Issue by ExodusR** [ExcessiveAmountsOfZombies/Croptopia#267]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.17.1

### Croptopia version.

1.6.2

### What happened?

Hello guy's,

With my friend we install the ModPack BetterMinecraft for the 1.17.1, in this modpack we have Croptopia but Patchouli was not installed, so we put it on the modpacks (Patchouli-1.17.1-57.jar) and now we see the book ! But.. we can't open the book, any ideas on what's going on?

**Comment by ExcessiveAmountsOfZombies** [comment]
I'm uploading a new version that adds support for this right now (1.7.0)
