### ISSUE TITLE
Cannot trade with unlocked Farmer Villager

### ISSUE THREAD

**Issue by itkminer** [ExcessiveAmountsOfZombies/Croptopia#269]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.17.1

### Croptopia version.

1.7.0

### What happened?

I cannot trade with a "fresh" farmer villager when using the latest release 1.7.0. They just shake their head similar to workers without any profession, and there will not be a trade window. Other professions are unaffected. Older farmer villagers with locked trades are also unaffected, I can still trade with them.

When I load the the same world without croptopia all farmers trade with me like normal.

When I go back to version 1.6.2 in the same world there's also no problem, I can trade with all farmers including those without locked trades (and they will buy croptopia items).

**Comment by amykins13** [comment]
I have found this bug in the 1.18 version as well.

**Comment by FosterGrime-Heymynameslouie** [comment]
This issue also exists in 1.18

**Comment by Secondbreakfastpip** [comment]
Also experiencing this bug in 1.18

**Comment by ExcessiveAmountsOfZombies** [comment]
If you make them unemployed and then re-employ them as farmers do they still not work? in my old test world they open and just don't have the trades. removing their job and re-adding it gives them new trades

**Comment by Secondbreakfastpip** [comment]
> If you make them unemployed and then re-employ them as farmers do they still not work? in my old test world they open and just don't have the trades. removing their job and re-adding it gives them new trades.
> 
> Either way this isn't something I can fix unless I just add their trades back, which won't be happening because it hides too many of the vanilla trades

No, they still don't work. They just nod their head as if they didn't have a job.  The only way I could get them to work was to use console commands and command blocks to spawn in a farmer villager with normal vanilla trades.

**Comment by ExcessiveAmountsOfZombies** [comment]
mind sending me your world?

**Comment by Secondbreakfastpip** [comment]
Its a bit big and has other mods (but tested without too) What file do you need from the save folder?

**Comment by ExcessiveAmountsOfZombies** [comment]
ah, nevermind, I don't think I can fix it anyways.  I think it's just how villagers are when their trades go missing. They'll be back soon when we add our own villager type

**Comment by Secondbreakfastpip** [comment]
Ah, alright, thanks anyway

**Comment by itkminer** [comment]
You can reproduce it easily in 1.17.1 :Create a new world with only mod Croptopia, spawn a villager, put a composter in front, let him turn to farmer and try to trade with him, he just shakes his head, no trade window.


On Monday, December 13, 2021, 9:20 PM, Thonk ***@***.***> wrote:




mind sending me your world?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by UdoMorgenstern** [comment]
same on 1.18.1, forge 39
used Croptopia-1.18-FORGE-1.7.3.jar
new spawned villager, becomes farmer, but does not show/open trade menu

**Comment by ExcessiveAmountsOfZombies** [comment]
ok this is fixed now in 1.7.4 ty everyone

**Comment by WitheredHope** [comment]
There doesn't seem to be a 1.7.4 version for Minecraft 1.17.1
