### ISSUE TITLE
Seeds to be used in composter or fed to chickens

### ISSUE THREAD

**Issue by h0ney-p0t** [ExcessiveAmountsOfZombies/Croptopia#270]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

I get a big influx of seeds when I harvest the crops, and I can't do anything with them, because the composter doesn't accept them, and they can't be fed to chickens, so I just either end up hoarding a bunch of seeds, or throwing them in lava to get rid of them. It would be nice if there could be a way to put them to use.

**Comment by ExcessiveAmountsOfZombies** [comment]
Seeds can be composted, perhaps you are on an older version

**Comment by ElectroArtifex** [comment]
Seeds still cannot be composted on version 2.2.2 of croptopia (fabric 1.19.2) 
Is this as intended?
