### ISSUE TITLE
Can't place blocks off crops

### ISSUE THREAD

**Issue by staridiot** [ExcessiveAmountsOfZombies/Croptopia#273]
This mod cancels the place block events called when placing off of a crop block. Simply try to place a block on top of some wheat seeds and you can replicate this.

Minecraft: 1.17.1
Forge: 37.0.109
Croptopia: 1.7.0

[Video example](https://www.youtube.com/watch?v=AQUcDA35YDc)

**Comment by ExcessiveAmountsOfZombies** [comment]
uploading a fix, also fixed in 1.18 thank you
