### ISSUE TITLE
Trees not showing up after config change

### ISSUE THREAD

**Issue by Muffintiem** [ExcessiveAmountsOfZombies/Croptopia#275]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18

### Croptopia version.

1.7.0

### What happened?

I tried to set dates and figs to generate in the Desert biome using the config file since I've always felt they were more appropriate there. Unfortunately when I went to a Desert there were none.

**Comment by ExcessiveAmountsOfZombies** [comment]
kind of a bug but also not a bug. If you had grass blocks that would spawn in the desert biomes then you could get the trees to spawn, but because the saplings can't be placed on sand the trees also won't grow on sand
