### ISSUE TITLE
tall grass does not drop any seeds besides wheat

### ISSUE THREAD

**Issue by fantasystaples** [ExcessiveAmountsOfZombies/Croptopia#277]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18

### Croptopia version.

Croptopia-1.18-pre5-FABRIC-1.7.0.jar

### What happened?

I added the mod to my game in fabric. It showed up on the mod list, and fruit trees spawn, as well as grapes, kale, all the stuff that is supposed to spawn. But grass or tall grass does not drop anything besides wheat seeds. I've tested it with all other mods removed besides croptopia and fabric api with a brand new world, same result, so it is the mod.

**Comment by ExcessiveAmountsOfZombies** [comment]
this is an intentional change, only way to get the crops now is breaking the wild ones that spawn in the world.

**Comment by fantasystaples** [comment]
> this is an intentional change, only way to get the crops now is breaking the wild ones that spawn in the world.

yup, thanks for getting back to me quickly
