### ISSUE TITLE
Book not working with Patchouli

### ISSUE THREAD

**Issue by ChopTV** [ExcessiveAmountsOfZombies/Croptopia#278]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18

### Croptopia version.

1.18 pre 5

### What happened?

In testing the mod the book won't open. Gave myself the book in creative, won't seem to open in Patchouli (1.18-60). Patchouli makes a "patchouli-books" directory on the server, but there is nothing in it. And I haven't seen any documentation to find a file to add it to the directory. The "book's" contents are definitely in the .jar file, but don't seem to be connecting with Patchouli. I tried resetting the world and crafting the book this time, still isn't opening in the game.

**Comment by ChopTV** [comment]
I isolated the two mods: So I made a new instance in MMC and only installed Fabric, Fabric API, Croptopia, and Patchouli. The goal was to remove interference from other mods from the situation. Still getting the same result. Can craft book. Right clicking just swings it around.

**Comment by ExcessiveAmountsOfZombies** [comment]
I'm uploading 1.7.1 that re-adds patchouli support. Patchouli wasn't out when I originally uploaded the mod so I had to comment the code out.
