### ISSUE TITLE
Mod not showing

### ISSUE THREAD

**Issue by Dromoka245** [ExcessiveAmountsOfZombies/Croptopia#279]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18

### Croptopia version.

1.18 Fabric 1.17.2

### What happened?

I just updated frabric api to the latest and installed the recent fabric croptopia and other mods for 1.18 version when I loaded up all other mods were showing up except for croptopia even though in the 1.17 it showed up

### Relevant logs

[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/7658912/latest.log)

**Comment by ExcessiveAmountsOfZombies** [comment]
```
        - com_typesafe_config 1.4.1 via confabricate
	- confabricate 2.2.0-SNAPSHOT+4.1.1 via croptopia
	- croptopia 1.7.2```
it shows in your mod list that it's loading?
