### ISSUE TITLE
Salt still doesnt generate

### ISSUE THREAD

**Issue by PocketAlex** [ExcessiveAmountsOfZombies/Croptopia#283]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.0

### Croptopia version.

1.7.2

### What happened?

i went into new chunks to find rivers but theres still no salt

**Comment by OdessaCubbage** [comment]
Haven't been having this issue myself, just tested on a new world, did you make sure they were truly new chunks? They can generate a fair distance out.

**Comment by AlexMishto99** [comment]
Maybe I'm wrong,but I've tested it in 3 different instances and i found
salt in neither. I'm convinced that at least the second and third time they
were new chunks.. but I've seen that salt looks really really similar to
sand so maybe I've missed it? I'm glad to have discovered that you can make
salt out of water bottles though;

Thank you for your reply and sorry for the possible inconvenience

**Comment by OdessaCubbage** [comment]
It's alright, I would recommend making a creative world and zipping around a bit to see if salt spawns in this fresh new world. If it does then it's just chunks already being generated for you.

Also make sure you're on the latest version if you haven't already.

**Comment by AlexMishto99** [comment]
I will try just that,thank you very much!

**Comment by ExcessiveAmountsOfZombies** [comment]
are you using terralith by chance? if you are the biomes *need* to be minecraft:river or minecraft:frozen river for the salt to generate.
