### ISSUE TITLE
Reference map could not be read

### ISSUE THREAD

**Issue by cpm9** [ExcessiveAmountsOfZombies/Croptopia#285]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.1

### Croptopia version.

1.7.2

### What happened?

Started server with croptopia included, got warning in server console & latest.log, expected there to be noe warning from croptopia

### Relevant log.

Entire latest.log not needed, here is the line in question

[09:19:22] [main/WARN]: Reference map 'croptopia.refmap.json' for croptopia.mixins.json could not be read. If this is a development environment you can ignore this message

**Comment by hacheraw** [comment]
Same here, thanks.

```
[main/WARN]: Reference map 'croptopia.refmap.json' for croptopia.mixins.json could not be read. If this is a development environment you can ignore this message
```

**Comment by Souldealer1962** [comment]
Same issue.
1.18.1 - Minecraft
39.0.19 - Forge
Croptopia-1.18-FORGE-1.8.3.jar
