### ISSUE TITLE
Stripped Cinnamon Log Mining Bug

### ISSUE THREAD

**Issue by OdessaCubbage** [ExcessiveAmountsOfZombies/Croptopia#286]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.1

### Croptopia version.

1.7.0

### What happened?

Stripped Log, as well as the wood variant, are not mined more quickly by axes. Fists are equally fast. The unstripped version work as intended though.

Also not sure if intended, but Cinnamon logs & wood, stripped or not, also cannot be used as fuel or turned into charcoal.

**Comment by ExcessiveAmountsOfZombies** [comment]
Thank you this will be fixed in the next version I publish.

**Comment by Nicolas-GE** [comment]
sorry for necroing, but i would add that at least composting the stripped logs would be nice, or using them as fuel, or planks maybe? it's not my mod, but they're litteraly useless as of 1.7.3 (forge)

**Comment by OdessaCubbage** [comment]
Oh yeah cinnamon planks and doors and such would be awesome, but I figured it might be outside the scope of this mod. Fuel and/or composting would be nice though.

**Comment by Nicolas-GE** [comment]
> but I figured it might be outside the scope of this mod.

that's what i thought too, but i still think it's not unreasonable to make them work like normal logs

**Comment by Nicolas-GE** [comment]
i was just throwing random ideas for things to do with the "waste" logs

charcoal is enough tho
