### ISSUE TITLE
Recipes not there

### ISSUE THREAD

**Issue by Transsanguine** [ExcessiveAmountsOfZombies/Croptopia#287]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18

### Croptopia version.

1.18

### What happened?

I cant seem to craft anything in your mod. I cant find the recipes for the book, the saplings, the mortar and pestle, any of it. The recipe isnt in my book and I cant craft the things if I put them in the grid. 

Otherwise, love the mod! I have fields of crops I cant cook with lol

### Additional information.

Long list, patchouli is in there

**Comment by ExcessiveAmountsOfZombies** [comment]
The recipes are there, they just haven't had the mechanisms that make them appear. https://github.com/ExcessiveAmountsOfZombies/Croptopia/pull/296 adds that so even if you don't have patchouli or REI/JEI installed you will get the recipes in your green book as you collect the items. #296 will be merged soon so I'll close this
