### ISSUE TITLE
Seeds drop in creative mode

### ISSUE THREAD

**Issue by JDLENL** [ExcessiveAmountsOfZombies/Croptopia#289]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18

### Croptopia version.

FORGE-1.7.3

### What happened?

Seeds are dropping from breaking tall grass in creative mode. This is counter to vanilla Minecraft behavior and should be removed.

![image](https://user-images.githubusercontent.com/29065768/146560308-b8e015ad-3ad0-4f7f-b02f-a82200888543.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
Thank you this will be fixed in the next release
