### ISSUE TITLE
Cinnamon tree not spawning

### ISSUE THREAD

**Issue by HawiTreeMan** [ExcessiveAmountsOfZombies/Croptopia#290]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.17.1

### Croptopia version.

1..7.0

### What happened?

i have been searching in the jungle for a while and i have found every crop/sapling that is added with croptopia but still have not found any cinnamon. i am playing on better minecraft mod pack 1.17.1. pls help.

### Additional information.

i saw the other post about the same issue and saw the responses in which it said the bug would get fixed with 1.7.0. i looked in my mod folder and saw that my croptopia was in 1.7.0.

**Comment by ExcessiveAmountsOfZombies** [comment]
This might've been fixed, but either way I wasn't really supporting 1.17 at the time this issue was made
