### ISSUE TITLE
[1.18] Cant Trade With Villager that have Farmer job

### ISSUE THREAD

**Issue by VoleExE** [ExcessiveAmountsOfZombies/Croptopia#291]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18

### Croptopia version.

1.7.2

### What happened?

when u right click to trade,inventory to trade do not appear

**Comment by ExcessiveAmountsOfZombies** [comment]
update to 1.7.4, it's fixed now
