### ISSUE TITLE
Seeds not dropping

### ISSUE THREAD

**Issue by AmbrozXD** [ExcessiveAmountsOfZombies/Croptopia#292]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.1

### Croptopia version.

FABRIC 1.7.3

### What happened?

I tried to get some seeds in my survival world but they weren't dropping from destroyed grass (i used a hoe). However vanilla wheat seeds dropped normally. This also happends in creative mode.

### Additional information.

Mods i use besides Croptopia:
Sodium 0.4.0
REI 7.1.356
Patchouli 61
Origins 1.3.1
Origins Classes 1.2.4
Lithium 0.7.6
Iris 1.1.3
Fabric language kotlin 1.5.0 + kotlin 1.4.31
Fabric API 0.44.0
Effective 1.0
Dragonloot 1.0.9
Bedspreads 1.5.0
Auto-clicker-fabric 1.3.0
Architectury 3.2.52

**Comment by ExcessiveAmountsOfZombies** [comment]
The crops will now spawn in the world, if you are using the same world you will have to generate new chunks.
