### ISSUE TITLE
Croptopia integration with Supplementaries Planters

### ISSUE THREAD

**Issue by East113** [ExcessiveAmountsOfZombies/Croptopia#293]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

I am currently using this mod through the Modpack Better Minecraft for 1.18.1 (Forge). It seems that you are unable to plant any crops from the Croptopia mod into the the planter from Supplementaries.

**Comment by ExcessiveAmountsOfZombies** [comment]
Will be fixed in 1.8.0. Thank you!

**Comment by superon** [comment]
was this unfixed?  currently running 
Croptopia-1.19.2-FORGE-2.1.0
and
supplementaries-1.19.2-2.2.3
and i've been unable to plant croptopia seeds in supplementaries planters

**Comment by Solbright** [comment]
I'm also not able to plant croptopia crops in supplementaries planeters. Fabric, latest versions of both mods.
