### ISSUE TITLE
Croptopia meats being labeled as meats 

### ISSUE THREAD

**Issue by Chaosticloki** [ExcessiveAmountsOfZombies/Croptopia#297]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

So ive been playing the origins mods and have noticed that all crops are labeled as a plant 
Ie: the bee origin I have cannot eat meat, but it is able to eat the Croptopia meats and fruits and vegetables 
While the Wolf origins I have (from the mod pack as the Bee) can only eat meats but we have found out they can't eat any thing that would be  meat (Bacon, fried chicken ect) 
so what im thinking is the meats are labeled as fruits or vegetables and not as meats, bc a bee that cant eat meats can and the wolf that cant can and i was wondering if in the future or at some point you would be able to separate them and label meat products as meats and not

**Comment by MasterSquinch** [comment]
I'm having the exact same issue, not sure where in the mod the items are tagged.
