### ISSUE TITLE
Iron Knife Recipe for Croptopia Missing, No Advancement

### ISSUE THREAD

**Issue by gwydion75** [ExcessiveAmountsOfZombies/Croptopia#299]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.1

### Croptopia version.

0.2.6

### What happened?

If you browse to Iron Knife recipe in the book, its blank. If you look for it in JEI, it isn't there. The farmer's delight Iron Knife doesn't advance the advancement tree.

**Comment by ExcessiveAmountsOfZombies** [comment]
AOF disables the croptopia knife

**Comment by gwydion75** [comment]
Right, but the croptopia advancement for the knife is still there and you
can't complete it.
