### ISSUE TITLE
Speedy Startup Crash: "Exception while loading entries for entrypoint 'preLaunch' provided by 'advanced_runtime_resource_pack'"

### ISSUE THREAD

**Issue by yelldow** [ExcessiveAmountsOfZombies/Croptopia#30]
I had to go through my mods one by one to see which one was causing this crash, as there was no clear marker.
This was on a newly created modpack, so no config changes were made as of yet. The only differing factors from a vanilla Minecraft install of 1.16.4 were the installation of Fabric 0.10.8, the inclusion of the modlist in the included paste (along with the disabling of two mods; Ars Thurgia, which was disabled long before from an unrelated crash, and Croptopia), and the game being launched from GDLauncher.

https://pastebin.com/4EbWeF4i

Let me know if you need more information.

**Comment by ExcessiveAmountsOfZombies** [comment]
My guess is that the config got mangled somehow and didn't turn into a JsonObject. that or it's my need to create the config before the mod has loaded in so I can modify the mixins. Could you paste what is in the options.json in the croptopia folder?
