### ISSUE TITLE
Ravoli

### ISSUE THREAD

**Issue by Chaosticloki** [ExcessiveAmountsOfZombies/Croptopia#300]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.1

### Croptopia version.

1.7.4

### What happened?

cant eat ravioli 
i have hunger, i have ravioli, cannot eat it

**Comment by BerkeBat** [comment]
Ravioli is not edible, this isn't a bug. But could be a suggestion to make it edible.

**Comment by Chaosticloki** [comment]
> Ravioli is not edible, this isn't a bug. But could be a suggestion to make it edible.

Ohhh that makes sense but if its not edible than whats it used for/why is it in the pack and craftable? kinda seems a tad pointless to be here if you cant do anything with it?

**Comment by BerkeBat** [comment]
Probably wi

> > Ravioli is not edible, this isn't a bug. But could be a suggestion to make it edible.
> 
> Ohhh that makes sense but if its not edible than whats it used for/why is it in the pack and craftable? kinda seems a tad pointless to be here if you cant do anything with it?

Will probably be added as an ingredient for a final craftable food in the future. It's listed under 'Secondary Ingredients', at the same level as stuff like butter and noodles. They probably just haven't gotten around to it yet.

**Comment by Chaosticloki** [comment]
OOooo thank you that makes sense, i dont have the things that tells me whats secondary and stuff bc they havent worked for some reason so i couldnt tell such, thank you very much
