### ISSUE TITLE
Universal crop declaration.

### ISSUE THREAD

**Issue by ShibeTemple** [ExcessiveAmountsOfZombies/Croptopia#302]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

When using other mods like Thermal Cultivation and Farmer's Delight, the items have universal declarations. For instance, you can use a Thermal Cultivation tomato in Farmer's Delight recipes and vice-versa. However, this is not true for Croptopia. This leads to an unnecessary divide between these mods! It would be great to have the crop yields unified.

Version: 1.16.5

**Comment by ExcessiveAmountsOfZombies** [comment]
When I have time to port back to 1.16.5 this will be fixed, as in the 1.18 versions I've gotten a bit better with the item tagging especially with Farmer's Delight
