### ISSUE TITLE
Lack of Coconut trees in Survival Mode

### ISSUE THREAD

**Issue by Vampy-Plays-Minecraft** [ExcessiveAmountsOfZombies/Croptopia#303]
I've been using Croptopia mod for a while and I noticed that coconut trees are extremely hard to find, more so than dragon fruit trees and other Jungle-specific items, so I duplicated my survival world in creative and there were a lot more trees that had coconuts than when I was in survival mode, and after double-checking coordinates that I'd seen the coconuts, they just weren't present in survival mode. I'm reporting this because I'm not sure how the fruit trees spawn in, but there's something off about the coconut trees that isn't occurring in others.

**Comment by ExcessiveAmountsOfZombies** [comment]
In 1.8.3 I'll have them set to spawn more frequently. This will be for 1.18.2 and 1.18.0-.1
