### ISSUE TITLE
Olive trees [turn into trees in 1.19]

### ISSUE THREAD

**Issue by JaisDK** [ExcessiveAmountsOfZombies/Croptopia#304]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Why on earth are olives a crop plant and not a tree?

**Comment by ExcessiveAmountsOfZombies** [comment]
it was a mistake, probably won't fix it because it'd involve wiping out peoples fields of olive bushes maybe 1.19
