### ISSUE TITLE
Please add Korean language to croptopia

### ISSUE THREAD

**Issue by skull7127** [ExcessiveAmountsOfZombies/Croptopia#306]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

I'm enjoying Croptopia, but I'm requesting that Korean be added.
Korean word translation is uploaded to my github

https://github.com/skull7127/croptpia-koran

**Comment by ExcessiveAmountsOfZombies** [comment]
Thank you for the translation!
