### ISSUE TITLE
Patchouli Book won't work

### ISSUE THREAD

**Issue by SomeRandomGuy787** [ExcessiveAmountsOfZombies/Croptopia#307]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.1

### Croptopia version.

1.8.0

### What happened?

I crafted the Patchouli recipe book for some recipes, but when right clicking it makes the using animation but nothing happens, what am i supposed to do

**Comment by ExcessiveAmountsOfZombies** [comment]
Just have to install patchouli for fabric
https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric

**Comment by SomeRandomGuy787** [comment]
i have done that

**Comment by SomeRandomGuy787** [comment]
it doesn't work with the fabric one

**Comment by ExcessiveAmountsOfZombies** [comment]
does the book have a texture?

**Comment by alexascha** [comment]
Hey, I have the same problem:
I'm testing it in a creative world and when I go on the Croptopia page there is a textureless item and when I hover on it I'm getting this: "Croptopia Patchouli is not installed" eventhough it is installed.
