### ISSUE TITLE
pepper crop texture looks buggy

### ISSUE THREAD

**Issue by Synthestra** [ExcessiveAmountsOfZombies/Croptopia#308]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.1

### Croptopia version.

1.8.0

### What happened?

![Screenshot_3](https://user-images.githubusercontent.com/22637135/151081283-bfe796ee-0391-4c67-ac43-2d2640ec2d67.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
what's wrong with it?
