### ISSUE TITLE
Drinkable Water Bottle

### ISSUE THREAD

**Issue by Auuki** [ExcessiveAmountsOfZombies/Croptopia#309]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Can Water Bottles become drinkable? Would make sense as well as allow for compatibility with thirst mods like Tough as Nails. On the contrary to Glass Bottles, they would have to disappear after drinking. As a side note - I don't think Water Bottles are needed. I get it that they are there to use less glass but it's not a big deal imo and there could be a config option instead that would modify Water Bottle recipe to give more bottles.

**Comment by ExcessiveAmountsOfZombies** [comment]
They exist because people asked for a way to craft recipes with stackable items. Vanilla water bottles (or really potions without an effect) don't stack and neither do water buckets. I don't think I'll be making them drinkable just because they're meant for mass crafting.
