### ISSUE TITLE
New food:Ajvar 

### ISSUE THREAD

**Issue by Laurengrif** [ExcessiveAmountsOfZombies/Croptopia#31]
Ajvar is a condiment made principally from red  peppers and sometimes are added eggplants. 
![Domaci-ajvar-kaufland hr_](https://user-images.githubusercontent.com/76576034/103115528-35029380-4663-11eb-8852-69081f0766b9.jpg)

**Comment by Laurengrif** [comment]
![113775336-serbian-ajvar-a-picture-of-the-ajvara-on-the-bread-covered-with-a-white-onion-](https://user-images.githubusercontent.com/76576034/103115669-d558b800-4663-11eb-9c8e-c267c8d73583.jpg)
And it can be put on bread

**Comment by ExcessiveAmountsOfZombies** [comment]
1.7.0 will be releasing soon so this can be closed!
