### ISSUE TITLE
I made Korean Translation

### ISSUE THREAD

**Issue by KaitheBlackCat** [ExcessiveAmountsOfZombies/Croptopia#313]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Here is the file. I hope this file is added next update.
[ko_kr.zip](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/7963758/ko_kr.zip)
I didn't translate recipe book right now, but I'll do that if you want.

**Comment by ExcessiveAmountsOfZombies** [comment]
Thank you for the translation!
