### ISSUE TITLE
Mashed Potatoes

### ISSUE THREAD

**Issue by Juisader** [ExcessiveAmountsOfZombies/Croptopia#318]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Mashed potatoes should be added and made using potato/sweet potato, milk, and a mortar and pestle, salt optional.

Made a GitHub account just to send this because my brother likes mashed potatoes.

**Comment by ExcessiveAmountsOfZombies** [comment]
sure!

**Comment by Juisader** [comment]
also forgot the bowl that it would be in
