### ISSUE TITLE
Garlic Crop does not drop anything

### ISSUE THREAD

**Issue by FlooffyAlpaca** [ExcessiveAmountsOfZombies/Croptopia#322]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.1

### Croptopia version.

1.8.0

### What happened?

Harvesting a mature Garlic Crop does not drop Garlic or Garlic Seeds. Left clicking the "harvested" plant afterwards just breaks the crop, but once again does not drop anything.

### Relevant log.

[10:44:05] [Render thread/ERROR]: Couldn't parse loot table croptopia:blocks/garlic_crop
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'bewitchment:garlic'

**Comment by ExcessiveAmountsOfZombies** [comment]
Looks like the modpack you're using edited the Croptopia loot tables to use betwitchment garlic, and bewitchment isn't in the pack, breaking the table. You'll have to report this to whoever edited the table

**Comment by FlooffyAlpaca** [comment]
Thanks so much for picking that up! Will consult themOn 27 Feb 2022 00:51, Thonk ***@***.***> wrote:
Looks like the modpack you're using edited the Croptopia loot tables to use betwitchment garlic, and bewitchment isn't in the pack, breaking the table. You'll have to report this to whoever edited the table
