### ISSUE TITLE
Forge crop tags

### ISSUE THREAD

**Issue by WenXin20** [ExcessiveAmountsOfZombies/Croptopia#33]
`Minecraft v1.16.4`
`Forge v35.1.28`
`Croptopia v1.1.0`

Several mods are using forge crops tags for recipe compat, such as Simple Farming and Pam's Harvestcraft, as seen [here.](https://github.com/cweckerl/simplefarming/tree/1.16/src/main/resources/data/forge/tags/items)
They use tags such as `forge:fruits/banana`, `forge:fruits/strawberries`, `forge:crops/banana`, or `forge:vegetables/corn`. The `forge:seeds/type` is also used.

Saplings are also missing the `minecraft:saplings` block & item tag. 

Also, the crop tree leaves don't decay when the tree is chopped down, and you can walk through those leaves. Is that intended?

**Comment by ExcessiveAmountsOfZombies** [comment]
> Several mods are using forge crops tags for recipe compat, such as Simple Farming and Pam's Harvestcraft, as seen here.
They use tags such as forge:fruits/banana, forge:fruits/strawberries, forge:crops/banana, or forge:vegetables/corn. The forge:seeds/type is also used.

I'll look into adding the appropriate tags.

> Also, the crop tree leaves don't decay when the tree is chopped down, and you can walk through those leaves. Is that intended?

Walking through leaves isn't intended, for now the not decaying is. I haven't decided how they should decay yet so they just have to be manually broken.

**Comment by WenXin20** [comment]
Alright, thanks! 
For decaying, I believe the way minecraft does it is by checking if the leaf block has a persistent state and is tagged with `minecraft:leaves` and then searches for a log tagged with `minecraft:logs`, and then decaying the leaf block if the log isn't found within 7 blocks.

**Comment by WenXin20** [comment]
There is also the `#minecraft:crops` block tag that I've just discovered, it allows bees to grow the crops.

**Comment by ExcessiveAmountsOfZombies** [comment]
I did some work on this and there are now `forge:<crop>` `forge:<seed>` and then `forge:seeds` `forge:crops` tags. I'll probably add some of the categories in the future too. Leaves also now decay if there are no regular leaves attached to them

**Comment by WenXin20** [comment]
Alright, thanks!

**Comment by ExcessiveAmountsOfZombies** [comment]
finally finished this up, all the items I believe that are worth having common tags for now have them. I may continue adding some more categories (salads, all drinks, deserts etc) but I think most cases have been covered now. 

https://github.com/ExcessiveAmountsOfZombies/Croptopia/commit/4b2c36de5fd5081c8a58657be5d48cfeccf24b27
