### ISSUE TITLE
Farming for Blockheads compatibility?

### ISSUE THREAD

**Issue by Niketats** [ExcessiveAmountsOfZombies/Croptopia#330]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

What about adding compatibility for Market from Farming for Blockheads?

**Comment by ExcessiveAmountsOfZombies** [comment]
I'll add the seeds to the market

**Comment by Niketats** [comment]
thx u so much
