### ISSUE TITLE
Fruit Crop Leaves not interacting with other mods

### ISSUE THREAD

**Issue by FluffyBumblebees** [ExcessiveAmountsOfZombies/Croptopia#331]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.1

### Croptopia version.

1.8.2

### What happened?

The leaves do not get culled by cull leaves and do not wave with shaders. I have tested with other mods and they do work with both cull leaves and waving foliage. If this could be rectified it would be appreciated as it is really annoying having it stand out like that.

### Relevant log.

[Uploading latest.log…]()

### Additional information.

All mods provided on mod pack page https://www.technicpack.net/modpack/the-limit-reborn-1181.1905659

BYG's Holly berry leaves works like all other leaves

**Comment by ExcessiveAmountsOfZombies** [comment]
This probably won't be fixed. It's a lot easier to make the crops mimic leaves than it is to make leaves mimic crops. As for it not waving, I know so little about shaders I have no idea how I could make them work

**Comment by Niketats** [comment]
shaders suppurt can't be configured on mod developer side 
(see https://github.com/sp614x/optifine/issues/2735)

**Comment by Ayutac** [comment]
> This probably won't be fixed. It's a lot easier to make the crops mimic leaves than it is to make leaves mimic crops. As for it not waving, I know so little about shaders I have no idea how I could make them work

are the blocks not tagged as leaves?

**Comment by ExcessiveAmountsOfZombies** [comment]
They are tagged as leaves https://github.com/ExcessiveAmountsOfZombies/Croptopia/tree/master/shared/src/main/resources/data/minecraft/tags/blocks

**Comment by Ayutac** [comment]
urgh, I looked under common tags. My bad
