### ISSUE TITLE
Food cant crafting

### ISSUE THREAD

**Issue by iivci** [ExcessiveAmountsOfZombies/Croptopia#333]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

1.18.2

### What happened?

I wanna creating any food but i didn't cause not add in crafting time.

![image](https://user-images.githubusercontent.com/101996430/159185692-dd49187e-38b2-4e01-bf59-dd87ee359065.png)

### Additional information.

My mods:

![image](https://user-images.githubusercontent.com/101996430/159185652-e915913e-52f0-472c-9fac-c7192f8eb984.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
I'm not sure what I'm looking at here? what is the issue you're experiencing? I don't think there are any Croptopia recipes that are just water and a cooking pot
