### ISSUE TITLE
Add line break to seed tooltips

### ISSUE THREAD

**Issue by Ayutac** [ExcessiveAmountsOfZombies/Croptopia#337]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.2

### Croptopia version.

1.8.1

### What happened?

Seed tooltips are usually to long which leads to the tooltip not being fully displayed on screen.

Solution: Add line break

Proposal: If you agree that this should be done, I will do the work and submit a PR :)

**Comment by ExcessiveAmountsOfZombies** [comment]
I went ahead and did it, but if you there is a better way to do it I'm still open to a PR

**Comment by Ayutac** [comment]
@ExcessiveAmountsOfZombies You forgot to add the else case if there is no "\n" ;)
