### ISSUE TITLE
Drinking jam items or a tea item gives glass bottles back

### ISSUE THREAD

**Issue by hlemont** [ExcessiveAmountsOfZombies/Croptopia#338]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.1

### Croptopia version.

1.8.2

### What happened?

When you drink some 'drink' items like jams or tea, it gives the drinker glass bottle back.
Since those items does not require any bottles when crafting, so I'm quite sure it is not an intended behavior and they should not give glass bottles back.

### Additional information.

Possible solution would be giving recipe remainder items instead of glass bottles. Following modification solved the issue.

```java
// me.thonk.croptopia.items.Drink.java
public class Drink extends Item {
    /* ... */

    @Override
    public ItemStack finishUsing(ItemStack stack, World world, LivingEntity user) {
        PlayerEntity playerEntity = user instanceof PlayerEntity ? (PlayerEntity)user : null;
        if (playerEntity instanceof ServerPlayerEntity) {
            Criteria.CONSUME_ITEM.trigger((ServerPlayerEntity)playerEntity, stack);
        }

        if (playerEntity != null) {
            playerEntity.incrementStat(Stats.USED.getOrCreateStat(this));
            if (!playerEntity.getAbilities().creativeMode) {
                if (isFood()) {
                    DrinkEvent.DRINK.invoker().onDrink(stack, playerEntity);
                    user.eatFood(world, stack);
                }
            }
        }

        if (playerEntity == null || !playerEntity.getAbilities().creativeMode) {
            if (stack.isEmpty()) {
                // here
                return new ItemStack(getRecipeRemainder());
            }

            if (playerEntity != null) {
                // and here
                playerEntity.getInventory().insertStack(new ItemStack(getRecipeRemainder()));
            }
        }

        return stack;
    }
}
```

Before:

https://user-images.githubusercontent.com/76568223/159668527-5bed0012-b130-40ce-b317-7f86b1a0e3c2.mp4

After:

https://user-images.githubusercontent.com/76568223/159668539-930beb2b-e4d7-47f2-bcb9-ad0f0213fcd9.mp4

**Comment by ExcessiveAmountsOfZombies** [comment]
That's a good idea! don't know why I didn't think of that
