### ISSUE TITLE
Fruit saplings just disappearing after growing, without turning into trees

### ISSUE THREAD

**Issue by Niketats** [ExcessiveAmountsOfZombies/Croptopia#339]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.2

### Croptopia version.

1.8.3

### What happened?

Any fruit sapling just disappearing after grow

### Relevant log.

[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/8356493/latest.log)

### Additional information.

https://user-images.githubusercontent.com/68917520/160259913-5e1ca36d-05f9-4a36-b05c-6ec0cd02a7c0.mp4

**Comment by ExcessiveAmountsOfZombies** [comment]
unstructured 0.2+1.18.2 is causing the issue, 

```java.lang.ClassCastException: class net.minecraft.class_3218 cannot be cast to class de.cristelknight999.unstructured.mixin.WorldGenRegionAccessor (net.minecraft.class_3218 and de.cristelknight999.unstructured.mixin.WorldGenRegionAccessor are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @ebaa6cb)
```
