### ISSUE TITLE
[Forge] Duplication Bug With Other Mod?

### ISSUE THREAD

**Issue by BloodshotPico** [ExcessiveAmountsOfZombies/Croptopia#34]
So basically I'm trying out some new mods for 1.16 right? And well I come across this beautiful gem. :)

https://www.youtube.com/watch?v=NXmpF14U_-I&feature=youtu.be

I'm honestly not sure what's causing it but it is something I've got installed alongside this, I've tested it with more than half of the mods listed removed and it worked fine, here's the logs in case anyone smarter than me can figure it out. :)
[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/5758644/latest.log)

~Blood

**Comment by ExcessiveAmountsOfZombies** [comment]
looking at the log i'm seeing a lot of errors with pams
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_271]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_271]
	at pam.pamhc2crops.events.harvest.CropHarvest.onCropHarvest(CropHarvest.java:73) ~[pamhc2crops:1.0.1]

Croptopia might not currently be compatible with Pams.

> 	at net.minecraftforge.eventbus.ASMEventHandler_494_CropHarvest_onCropHarvest_RightClickBlock.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:789) ~[forge:?]

I see there are event handlers for right clicking, so maybe I need to use forges system for handling people clicking on blocks rather than doing it on the block like I am currently.

**Comment by BloodshotPico** [comment]
Ah I see, I thought as much honestly. Since pams does a similar thing with a different style of block.

Also I would like to suggest maybe making it so players collide with the block instead of phasing through it?

**Comment by ExcessiveAmountsOfZombies** [comment]
You'll have to disable pam's right click harvest in a future version if you're still using these mods together. I used the event and it didn't fix the issue. I think it's just the way pam's handles their right clicking of crops. I still moved to using an event for right clicking in croptopia and my method is compatible with pams and doesn't duplicate the trees anymore. I'll have a new version on CF soon.
