### ISSUE TITLE
Cannot craft any foods that require fruits, flour, oils, salts, etc. [Remove Cooking For Blockheads as temp fix]

### ISSUE THREAD

**Issue by UnderscoreMille** [ExcessiveAmountsOfZombies/Croptopia#342]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

1.8.3

### What happened?

I use croptopia for a server with some friends and none of us can craft virtually any items due to many croptopia items showing up in recipes as red signs with the name being the forge tag. This then means that every food that is not base is uncraftable. 

### Additional information.

![image](https://user-images.githubusercontent.com/102619613/160681306-2dfc5417-c258-486b-9b2d-d52442f34a72.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
What other mods do you have installed on the server?

**Comment by ExcessiveAmountsOfZombies** [comment]
![image](https://user-images.githubusercontent.com/30448663/160747063-083219ed-9497-4b13-9595-7e06fcd01dc1.png)
here it is working for me with just Croptopia 1.8.3, patchouli and JEI

**Comment by UnderscoreMille** [comment]
![image](https://user-images.githubusercontent.com/102619613/160763315-1c86d2e6-b97f-4362-a35a-99539de473b7.png)
![image](https://user-images.githubusercontent.com/102619613/160763347-ebd8254d-baa4-4a08-a98e-7f6b9db752e5.png)
This is the current mod list

**Comment by ExcessiveAmountsOfZombies** [comment]
Maybe try and redownload croptopia for the server and clients?
https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric/files/3707657

**Comment by UnderscoreMille** [comment]
could it be a result of the forge port? we are currently using the forge port for everyone

**Comment by ExcessiveAmountsOfZombies** [comment]
The picture I posted last night was me using the forge version of Croptopia

**Comment by UnderscoreMille** [comment]
I tried redownloading it and so far it has not changed anything

**Comment by ExcessiveAmountsOfZombies** [comment]
Might have to do the binary search method, remove half the mods, if the issue persists put the half you took out and put it back and take out the other half. If the issue goes away add half of the mods you took out back and continue until you narrow it down. 

Does the issue happen with these mods present in single player? or just on the server? If it happens only on the server but not single player could you send me your latest.log for the client and the latest.log for the server?

**Comment by jeremiahwinsley** [comment]
Related issue: https://github.com/ModdingForBlockheads/CookingForBlockheads/issues/576

**Comment by TronWoWGamer** [comment]
I have the same problem with All The Mods 7 where sometimes the recipes have the red squares and sometimes they don't.  Usually I reinstall the mod and that sometimes fixes it, but it seems to be missing Forge tags.

**Comment by jeremiahwinsley** [comment]
That's the same issue, latest version of ATM7 removes Cooking For Blockheads to fix it.

**Comment by UnderscoreMille** [comment]
I found that removing cooking for blackheads was the solver for me, similar mods for cooking igSent from my T-Mobile 5G Device
-------- Original message --------From: TronWoWGamer ***@***.***> Date: 4/5/22  19:41  (GMT-08:00) To: ExcessiveAmountsOfZombies/Croptopia ***@***.***> Cc: UnderscoreMille ***@***.***>, Author ***@***.***> Subject: Re: [ExcessiveAmountsOfZombies/Croptopia] Cannot craft any foods that require fruits, flour, oils, salts, etc.  (Issue #342) 
I have the same problem with All The Mods 7 where sometimes the recipes have the red squares and sometimes they don't.  Usually I reinstall the mod and that sometimes fixes it, but it seems to be missing Forge tags.

**Comment by UnderscoreMille** [comment]
I found that removing cooking for blackheads was the solver for me, similar mods for cooking igSent from my T-Mobile 5G Device
-------- Original message --------From: TronWoWGamer ***@***.***> Date: 4/5/22  19:41  (GMT-08:00) To: ExcessiveAmountsOfZombies/Croptopia ***@***.***> Cc: UnderscoreMille ***@***.***>, Author ***@***.***> Subject: Re: [ExcessiveAmountsOfZombies/Croptopia] Cannot craft any foods that require fruits, flour, oils, salts, etc.  (Issue #342) 
I have the same problem with All The Mods 7 where sometimes the recipes have the red squares and sometimes they don't.  Usually I reinstall the mod and that sometimes fixes it, but it seems to be missing Forge tags.
