### ISSUE TITLE
Tree biome tags

### ISSUE THREAD

**Issue by JustFoxx** [ExcessiveAmountsOfZombies/Croptopia#343]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

> 1.18.2
### Add tag for biomes that certain trees generates (would be easier to make compatibilities with your mod)

**Comment by JustFoxx** [comment]
Or put trees into one category and then create tags using that category

**Comment by ExcessiveAmountsOfZombies** [comment]
this ended up not happening in the way that I thought it would
