### ISSUE TITLE
Horchata Uncraftable

### ISSUE THREAD

**Issue by H077y** [ExcessiveAmountsOfZombies/Croptopia#350]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.1

### Croptopia version.

https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric/files/3671479

### What happened?

I tried to craft the Horchata but it just would not accept my materials
Every other craft I've tried has worked (I haven't tried many though)
![image](https://user-images.githubusercontent.com/64114013/163843904-2c5e00a1-96e8-4e1a-b23c-579d2a654f20.png)
![image](https://user-images.githubusercontent.com/64114013/163843962-31932a97-b418-4cc8-a691-42c61856f35c.png)

**Comment by H077y** [comment]
Even after giving it to myself, I cannot seem to drink it

**Comment by H077y** [comment]
same happens with mead
![image](https://user-images.githubusercontent.com/64114013/163845220-b660b931-f401-458a-a39a-5c8fae8f1ef9.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
the vanilla water bottles aren't actually water bottles but potions, you'll have to use water buckets or the Croptopia recipe for water bottles

**Comment by H077y** [comment]
> the vanilla water bottles aren't actually water bottles but potions, you'll have to use water buckets or the Croptopia recipe for water bottles

I realised that after, however that does not explain why it's undrinkable

**Comment by ExcessiveAmountsOfZombies** [comment]
oh, my bad I didn't read it all
