### ISSUE TITLE
Dehydration Compatibility

### ISSUE THREAD

**Issue by haz8989** [ExcessiveAmountsOfZombies/Croptopia#36]
Would be cool if you added compatibility with the mod Dehydration, by adding the tag `dehydration:hydrating_food` to drinks, citrus fruit etc.
https://www.curseforge.com/minecraft/mc-mods/dehydration
And thank you for Nourish compatibility.

**Comment by ExcessiveAmountsOfZombies** [comment]
already done
https://github.com/ExcessiveAmountsOfZombies/Croptopia/tree/master/common/src/main/resources/data/dehydration/tags/items
I guess update to the latest version
