### ISSUE TITLE
latest update crashes in my modpack.

### ISSUE THREAD

**Issue by netcore10** [ExcessiveAmountsOfZombies/Croptopia#366]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.2

### Croptopia version.

2.0.0

### What happened?

Crash on launch. Can you discern anything?

### Relevant logs

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/27/22, 3:07 PM
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "com.tom.cpm.client.CustomPlayerModelsClient.initGui(net.minecraft.class_437)" because "com.tom.cpm.client.CustomPlayerModelsClient.INSTANCE" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.minecraft.client.gui.screen.Screen.handler$cha000$onInit(Screen:3213)
	at net.minecraft.client.gui.screen.Screen.init(Screen:393)
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen:164)
	at net.minecraft.client.gui.screen.Screen.init(Screen:389)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:993)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:637)
	at net.minecraft.client.main.Main.main(Main:197)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.handler$cha000$onInit(class_437.java:3213)
	at net.minecraft.class_437.method_25423(class_437.java:393)
	at net.minecraft.class_442.method_25426(class_442.java:164)
	at net.minecraft.class_437.method_25423(class_437.java:389)
	at net.minecraft.class_310.method_1507(class_310.java:993)
	at net.minecraft.class_310.<init>(class_310.java:637)

-- Initialization --
Details:
	Modules: ~~ERROR~~ LinkageError: loader constraint violation: when resolving interface method 'int com.sun.jna.platform.win32.Version.GetFileVersionInfoSize(java.lang.String, com.sun.jna.ptr.IntByReference)' the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4535b6d5 of the current class, net/minecraft/class_6498, and the class loader 'app' for the method's defining class, com/sun/jna/platform/win32/Version, have different Class objects for the type com/sun/jna/ptr/IntByReference used in the signature (net.minecraft.class_6498 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4535b6d5, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @305a0c5f; com.sun.jna.platform.win32.Version is in unnamed module of loader 'app')
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1028021824 bytes (980 MiB) / 1761607680 bytes (1680 MiB) up to 6710886400 bytes (6400 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1259
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 47817.13
	Virtual memory used (MB): 12834.03
	Swap memory total (MB): 31488.00
	Swap memory used (MB): 362.33
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6400m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
		advanced_reborn: Advanced Reborn 1.0.5
		adventurez: AdventureZ 1.4.10
		ae2: Applied Energistics 2 11.0.0-alpha.5
		ae2things: AE2Things 1.1.0-beta.3
		ae2wtlib: AE2WTLib 11.0.0-alpha.2
		agape_space: Space Dimensions 0.5.8
		akashictomeoftools: Akashic Tome Of Tools Fabric 1.2.1
		alloy_forgery: Alloy Forgery 2.0.13+1.18
		ambientsounds: Ambiend Sounds (Fabric) 5.0.16
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.2
		apoli: Apoli 2.3.3
		appleskin: AppleSkin 2.4.0+mc1.18.2
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		arcanus: Arcanus 1.29
		architectury: Architectury 4.2.50
		archon: Archon 0.2.3
		artifacts: Artifacts 7.0.3+fabric
		autoconfig1u: Auto Config v1 Updated 3.4.0
		badpackets: Bad Packets 0.1.1
		balm-fabric: Balm 3.0.0+0
		bclib: BCLib 1.4.4
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterend: Better End 1.1.0
		betterf3: BetterF3 1.2.4
		betternether: Better Nether 6.1.0
		bewitchment: Bewitchment 1.18-17
		blossom: Blossom 1.18.2-1.0.4
		blue_endless_jankson: jankson 1.2.1
		botania: Botania 1.18.2-431-FABRIC
		bushybusiness: BushyBusiness 1.1.0
		byg: Oh The Biomes You'll Go 1.4-RC-10
		cacao: Croptopia's Chocolaterie 1.0
		calio: Calio 1.5.1
		camsbackpacks: Cammie's Wearable Backpacks 2.11
		capybara: Capybara 1.0.3
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		chunky: Chunky 1.2.164
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		cloth-config-lite: cloth-config-lite 2.0.6
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_llamalad7_mixinextras: MixinExtras 0.0.7
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		controlling: Controlling For Fabric 9.0+19
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		cooldown-coordinator: Cooldown Coordinator 0.3.0
		cosmetic-armor: Cosmetic Armor 1.3.0
		cpm: Customizable Player Models 0.3.1a
		crafttweaker: CraftTweaker 9.1.114
		crawl: Crawl 0.10.6
		creativecore: CreativeCore (Fabric) 2.6.10
		crockpot: Crock Pot 0.8.4+1.18.2
		croptopia: Croptopia 2.0.0
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		culinaire: Culinaire 2.4.0
		cursery: Cursery Mod 1.18.2-3.0
		dawn: Dawn API 3.3.0
		detailab: Detail Armor Bar 2.6.2+1.18-fabric
		dimension_data_fix: Dimension Data Fix 1.0.1
		dragonloot: DragonLoot 1.0.10
		duckling: Duckling 1.0.3
		ductwork: Ductwork 0.2.3
		dynamicfps: Dynamic FPS 2.1.0
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18.2
		ecologics: Ecologics 1.5.4
		edenring: EdenRing 0.5.1
		effective: Effective 1.2.1
		elementalcreepers: Elemental Creepers: Refabricated 1.4.2+1.18.2
		enchantment_force: enchantment_force 0.1.7
		endlessocean: Endless Ocean: Aquatic Adventures 0.2.0-BETA
		entityculling: EntityCulling-Fabric 1.5.1
		equipmentcompare: Equipment Compare 1.2.12
		expandability: ExpandAbility 6.0.0
		expandedstorage: Expanded Storage 7.3.12
		extraalchemy: Extra Alchemy 1.8.1
		fabric: Fabric API 0.51.1+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricenchantments: Fabric Enchantments 0.7.2
		fabricloader: Fabric Loader 0.13.3
		fake-player-api: Fake Player API 0.3.0
		farmingforblockheads: Farming for Blockheads 10.0.0
		faux-custom-entity-data: Faux-Custom-Entity-Data 2.0.1
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		fiber: fiber 0.23.0-2
		fishofthieves: Fish of Thieves 1.0.5
		fixedwaterlogging: Fixed Waterlogging 1.0.2
		fluidtank: Fluid Tank 18.5.0-fabric
		foodplusid: Food+ 1.3.1
		freecam: Freecam 1.0.4
		friendsandfoes: Friends&Foes 1.3.4
		gateofbabylon: Gate Of Babylon 1.7.0-1.18.2
		gearreborn: Gear Reborn 1.18.2-0.1.12
		geckolib3: Geckolib 3.0.38
		go-fish: Go Fish 1.5.0-1.18.2
		graveyard: The Graveyard 1.7
		graveyard_biomes: The Graveyard Biomes 1.1
		harvest-with-ease-fabric: Harvest with ease 1.2.0
		iceberg: Iceberg 1.0.38
		iconicwands: Iconic Wands 1.0.4
		impaled: Impaled 1.1.1
		impersonate: Impersonate 2.4.1
		indium: Indium 1.0.3+mc1.18.2
		ingredient-extension-api: Ingredient Extension API 2.0.5
		inventoryprofilesnext: Inventory Profiles Next 1.3.5
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.4-build.38
		jamfabric: Jamtastic 1.3.4
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.2.0+1.14.4-1.19
		lazydfu: LazyDFU 0.1.2
		leaves_us_in_peace: Leaves Us In Peace 1.0.4
		libblockattributes: LibBlockAttributes 0.10.2
		libblockattributes_core: LibBlockAttributes (Core) 0.10.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.2
		libblockattributes_items: LibBlockAttributes (Items) 0.10.2
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.9
		llamarama: Llamarama 1.6.4
		lovely_snails: Lovely Snails 1.0.4+1.18
		lushforest: Lush Forests 1.3.0
		magna: Magna 1.7.0-1.18-pre1
		mavm: More Axolotl Variants Mod 1.0.7a
		mcda: MC Dungeons Armors 2.0.5
		mcdar: MC Dungeons Artifacts 1.4.6
		mcdw: MC Dungeons Weapons 4.3.1
		mealapi: Meal API 0.3+1.18
		megaparrot: Megaparrot 1.0.4
		minecraft: Minecraft 1.18.2
		miniminer: Miniminer 1.0.0
		mm: Manningham Mills 2.3
		modid: Creatures Of The Snow 1.0.0
		modmenu: Mod Menu 3.2.1
		mythicmetals: Mythic Metals 0.13.1
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nears: Nears 1.1.8
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.3.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		observable: Observable 2.2.3
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_javassist_javassist: javassist 3.28.0-GA
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		org_json_json: json 20211205
		org_reflections_reflections: reflections 0.10.2
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		origins: Origins 1.4.1
		overweight_farming: Overweight Farming 1.18.2-1.2.0-fabric
		owo: oωo 0.7.0+1.18
		patchouli: Patchouli 1.18.2-67-FABRIC
		pehkui: Pehkui 3.2.2+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pickyourpoison: Pick Your Poison 1.0.5
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		plutoscoffee: Pluto's Coffee Mod 1.18.2-1.9
		polymorph: Polymorph 0.0.20-1.18.2
		pugh_lib: Pugh Lib 1.3.0
		qolfixes: QoLFixes 1.4
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.2.0-beta.2
		reinfbarrel: Reinforced Barrels 2.0.0+1.18
		reinfcore: Reinforced Core 2.0.0+1.18
		roughlyenoughitems: Roughly Enough Items 8.1.457
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		runes: Simply Runes 1.1.0
		sandwichmod: Sandwich Mod fabric-1.18.2-v2.0.1
		satin: Satin 1.7.2
		servercore: ServerCore 1.2.9-1.18.2
		sit: Sit 1.18.2-18
		skylorlib: SkyLib 1.3.34
		slotlink: slotlink 4.3.1
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+build.15
		someforgepatchesported: Some Forge Patches Ported 1.0.3
		spark: spark 1.9.1
		spellbound: Spellbound 1.8.0
		sprout: Sprout 1.1.0
		stendhal: Stendhal 1.2.0-1.18
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structures_compass: Structures Compass 1.18.2-1.4.2
		styledchat: Styled Chat 1.2.3+1.18
		sushimod: Sushi Mod fabric-1.18.2-v1.0.1
		team_reborn_energy: Energy 2.2.0
		techreborn: Tech Reborn 5.2.0-beta.2
		terrablender: TerraBlender 1.1.0.99
		terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		the_bumblezone: The Bumblezone - Fabric 5.0.10+1.18.2
		trinkets: Trinkets 3.3.0
		vanilla_degus: Vanilla Degus 1.3.0
		variantbarrels: Variant Barrels 1.4.0
		veggie_way: The Veggie Way 1.2.32
		veinmining: Vein Mining 0.0.12-1.18.2
		villainousfishai: Villainous Fish AI 1.1
		vmp: Very Many Players 0.2.0+beta.3.17
		voicechat: Simple Voice Chat 1.18.2-2.2.37
		voidz: VoidZ 1.0.7
		waystones: Waystones 10.0.0
		wildlife: Wildlife 1.18.2-1.0
		wmitaf: WMITAF 2.2.0
		world_of_food: World of Food 1.0.1
		wthit: wthit 4.9.0
		xaerominimap: Xaero's Minimap 22.6.1
		xaeroworldmap: Xaero's World Map 1.20.7
		yigd: You're in Grave Danger 1.3.1
	Loaded Shaderpack: ComplementaryShaders_v4.4.zip
		Profile: Custom (+9 options changed by user)
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.59, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader)

### Additional information

1.8.3 doesn't crash

**Comment by Ayutac** [comment]
does it also crash when you run only fabric and Croptopia?

**Comment by pewblaze** [comment]
My modpack also crashes after startup.
For me it was the addon croptopia Chocolaterie ;)

**Comment by netcore10** [comment]
> I think you have a mod that is adding `com.sun.jna.platform.win32.Version.GetFileVersionInfoSize(java.lang.String, com.sun.jna.ptr.IntByReference)` to the classpath when mojang's already exists. class_6498 is WinNativeModuleUtil. I don't do anything with either of these classes, and it crashes with an NPE from `cpm: Customizable Player Models 0.3.1a`

The thing i'm confused with, is that it didn't in 1.8.3

**Comment by ExcessiveAmountsOfZombies** [comment]
> > I think you have a mod that is adding `com.sun.jna.platform.win32.Version.GetFileVersionInfoSize(java.lang.String, com.sun.jna.ptr.IntByReference)` to the classpath when mojang's already exists. class_6498 is WinNativeModuleUtil. I don't do anything with either of these classes, and it crashes with an NPE from `cpm: Customizable Player Models 0.3.1a`
> 
> The thing i'm confused with, is that it didn't crash in 1.8.3

did you update the fabric api at the same time as when you updated to 2.0.0?

**Comment by netcore10** [comment]
> > > I think you have a mod that is adding `com.sun.jna.platform.win32.Version.GetFileVersionInfoSize(java.lang.String, com.sun.jna.ptr.IntByReference)` to the classpath when mojang's already exists. class_6498 is WinNativeModuleUtil. I don't do anything with either of these classes, and it crashes with an NPE from `cpm: Customizable Player Models 0.3.1a`
> > 
> > 
> > The thing i'm confused with, is that it didn't crash in 1.8.3
> 
> did you update the fabric api at the same time as when you updated to 2.0.0?

i did.

**Comment by ExcessiveAmountsOfZombies** [comment]
> > > > I think you have a mod that is adding `com.sun.jna.platform.win32.Version.GetFileVersionInfoSize(java.lang.String, com.sun.jna.ptr.IntByReference)` to the classpath when mojang's already exists. class_6498 is WinNativeModuleUtil. I don't do anything with either of these classes, and it crashes with an NPE from `cpm: Customizable Player Models 0.3.1a`
> > > 
> > > 
> > > The thing i'm confused with, is that it didn't crash in 1.8.3
> > 
> > 
> > did you update the fabric api at the same time as when you updated to 2.0.0?
> 
> i did.
I downloaded customplayermodels and used 2.0.0 of croptopia and the recommended fabric api build and it's not crashing for me. You're going to need to binary search your mods and see which one is causing it (remove half if no crash add back and remove other half, if crash add half of those back etc)

**Comment by netcore10** [comment]
> > > > > I think you have a mod that is adding `com.sun.jna.platform.win32.Version.GetFileVersionInfoSize(java.lang.String, com.sun.jna.ptr.IntByReference)` to the classpath when mojang's already exists. class_6498 is WinNativeModuleUtil. I don't do anything with either of these classes, and it crashes with an NPE from `cpm: Customizable Player Models 0.3.1a`
> > > > 
> > > > 
> > > > The thing i'm confused with, is that it didn't crash in 1.8.3
> > > 
> > > 
> > > did you update the fabric api at the same time as when you updated to 2.0.0?
> > 
> > 
> > i did.
> > I downloaded customplayermodels and used 2.0.0 of croptopia and the recommended fabric api build and it's not crashing for me. You're going to need to binary search your mods and see which one is causing it (remove half if no crash add back and remove other half, if crash add half of those back etc)

Damn.

**Comment by netcore10** [comment]
it was an addon i forgot i added with croptopia. Sorry for the trouble (Croptopia chocolaterie)
