### ISSUE TITLE
[Forge's breaking changes] "Empty Tag: ..."

### ISSUE THREAD

**Issue by wasdspace** [ExcessiveAmountsOfZombies/Croptopia#369]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

1.18.2-2.0.0

### What happened?

Forge: 1.18.2-40.1.0
jei: 1.18.2-9.7.0.194
Patchouli: 1.18.2-67

See the screenshots:
![2022-04-30_19 15 41](https://user-images.githubusercontent.com/85009668/166103627-986a1f97-1df1-447b-8b70-d702558c13bf.png)
![2022-04-30_19 16 12](https://user-images.githubusercontent.com/85009668/166103629-2e7e4c29-6ad0-49a8-8d9a-c6f4317a8803.png)

### Additional information.

Seems to be related to this breaking change: https://github.com/MinecraftForge/MinecraftForge/pull/8495
Cooking For Blockheads had a similar issue: https://github.com/ModdingForBlockheads/CookingForBlockheads/issues/583
Hope these can help you.

**Comment by ExcessiveAmountsOfZombies** [comment]
this one is my mistake, missed a few recipes during the 2.0.0 rewrite

**Comment by Peach774** [comment]
Regarding this - the chili pepper is tagged as chile which is the country, when it should be chili which is the pepper
