### ISSUE TITLE
Free glass bottles from jam on toast.

### ISSUE THREAD

**Issue by kabadesu** [ExcessiveAmountsOfZombies/Croptopia#37]
I'm playing All of Fabric 2.5.6 which is running Croptopia-1.16.3-4-FABRIC-1.1.0.

When you create jam and then put it on toast you get a free glass bottle back (which isn't part of the recipe for making jam).

**Comment by ExcessiveAmountsOfZombies** [comment]
thank you, this will be fixed in croptopia in a few days.
