### ISSUE TITLE
[1.18.2] Compatibility with Biomes O Plenty and Terralith?

### ISSUE THREAD

**Issue by mav-8** [ExcessiveAmountsOfZombies/Croptopia#370]
Is this compatible with the two world gen mods up top? I can't find any seeds spawning in those biomes. Is there also a way to just add biomes for Croptopia seeds to spawn?

**Comment by ExcessiveAmountsOfZombies** [comment]
in 2.0.0 I added a datapack way to add crops to biomes https://github.com/ExcessiveAmountsOfZombies/Croptopia/tree/master/shared/src/main/generated/data/croptopia/tags/worldgen/biome/has_crop and in the croptopia config.toml you can see how to add more biomes there for trees

**Comment by mav-8** [comment]
Okay I'll look into it, thanks!
