### ISSUE TITLE
Drinking Animation

### ISSUE THREAD

**Issue by NealSavage** [ExcessiveAmountsOfZombies/Croptopia#377]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Items like tea look like you're eating them. It would be nice if it looked like drinking, not eating.

**Comment by ExcessiveAmountsOfZombies** [comment]
I don't know what version you're using, but I don't think this has ever been the case... it's the same animation and sound as a drink

**Comment by NealSavage** [comment]
I mean, it isn't though.

**Comment by NealSavage** [comment]
I think I saw a tea crop nearby in my new world I'm in, let me make some tea and test it again and get you a video and logs and whatnot.

**Comment by NealSavage** [comment]
Video of it : https://www.youtube.com/watch?v=YO6puulDJUU
MultiMC Console Output: https://bytebin.lucko.me/TmuTj5LaXc
Logs: https://bytebin.lucko.me/ijTb4McvsW

At least, they look the same to me.....?

**Comment by NealSavage** [comment]
Also, sorry for it taking me an hour. I lost my base and had to wander around for a while until I found a tea crop in the wild and then I didn't like the first video I made, so I had to grow another tea crop, and then I didn't like that video because I didn't manage to have food on hand already, so I had to grow more tea and a strawberry and finally was set up. lol

**Comment by ExcessiveAmountsOfZombies** [comment]
I'm sorry you spent so much time on this, but this is just how it looks in the game, if you drink a potion in the game it'll look the same way

**Comment by NealSavage** [comment]
Oh okay. Hm. They need a better drinking animation then lol
