### ISSUE TITLE
[Feature request] French cuisine

### ISSUE THREAD

**Issue by Robinerra** [ExcessiveAmountsOfZombies/Croptopia#378]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

These recipes/the fillings change depending on who you ask, but these are based off of my mom's recipes.

1. Sweet Crêpes
Flour, eggs, milk and a frying pan, and sugar/any jam as a filling.

2. Crêpe farcies (Baked Crêpes)
Flour, eggs, milk, frying pan (as the base Crêpe), then eggs, spinach and cheese as the filling.

3. Quiche
flour, milk, eggs, onion, spinach, tomatos, frying pan

4. Frog legs
To be added in 1.19

5. Pommes dauphine
Potatos, water, butter, flour, milk, oil, frying pan

6. Croque monsieur
Bread, cheese, ham, frying pan, (Butter & flour OR create a new Bechamel Sauce item made with butter, flour and a frying pan)

7. Croque madam
Same thing as 6. but with an egg.

I would also like to express my support for #315's suggestion to add more Italian cuisine like garlic bread, lasanga and spaghetti.

I would also like to see croissants, baguettes etc along with this suggestion but it seems like this mod is more in the direction of including composed dishes and not individual breads and baked goods.

**Comment by ExcessiveAmountsOfZombies** [comment]
this got added a while back actually!
