### ISSUE TITLE
Cinnamon Trees Not Dropped Cinnamon (Forge 1.18.2)

### ISSUE THREAD

**Issue by KosmoKhaos** [ExcessiveAmountsOfZombies/Croptopia#381]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.0.1

### What happened?

So I am on a server running Forge for 1.18.2 and when we installed croptopia, everything works fine except for the cinnamon trees. They generate in Jungle biomes like they are supposed to but they don't drop cinnamon when right clicked with an axe (or empty hand). I tried taking out every single other mod and testing in a vanilla world using only Croptopia and still no luck. Hope this can get fixed soon because cinnamon is used in a lot of the recipes.

### Additional information.

![image](https://user-images.githubusercontent.com/105690399/168718352-15275374-9d90-449e-a469-fb35bbdeec7a.png)

**Comment by JairyJicama** [comment]
I believe we tracked this down to a block being commented out - should be fixed? https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/master/forge/src/main/java/com/epherical/croptopia/events/BlockBreakEvent.java

**Comment by KosmoKhaos** [comment]
> I believe we tracked this down to a block being commented out - should be fixed? https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/master/forge/src/main/java/com/epherical/croptopia/events/BlockBreakEvent.java

😅 I am a noob to mods so I'm not sure what this means. Should I redownload the mod or do I need to change something to make it work?

**Comment by ExcessiveAmountsOfZombies** [comment]
releasing a fix now, this is 2.0.3
