### ISSUE TITLE
Instant decay for crop blocks on trees

### ISSUE THREAD

**Issue by heyjudek** [ExcessiveAmountsOfZombies/Croptopia#383]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

So, if you cut down a tree, some crop blocks always float and take a long time to decay even when all leaves decay instantly. However, if you "harvest" a crop when it is floating, it will stay there seemingly forever.
Any way to make them decay immediately if their tree is cut down?

**Comment by ExcessiveAmountsOfZombies** [comment]
is this an issue on fabric or forge? Not sure if the forge version has this issue, in the modpack i've been playing the croptopia leaves decay at the same time as the regular leaves

**Comment by heyjudek** [comment]
I am using fabric. I noticed that 2 crop blocks stayed on for days (perhaps forever if I hadn't destroyed them) after I "harvested" them. I will make sure to pay attention to this in case it happens again and send my modlist. I am using All of Fabric 5 + some random mods.

**Comment by ExcessiveAmountsOfZombies** [comment]
earlier today I looked to see if the leaves would actually decay and they do. I don't see why something in AOF would prevent their decay so i'll close this for now. if you can get me some steps for reproducing it we can re-open and I can take a deeper look
