### ISSUE TITLE
Nonexistant IntegerProperty causing RFTools Builder to tick

### ISSUE THREAD

**Issue by border999** [ExcessiveAmountsOfZombies/Croptopia#385]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

Croptopia-1.18.2-FORGE-2.0.1

### What happened?

Builder worked well for a long time, then this crash. Now whenever I try to get into the world this crash prevents me.

### Relevant logs

[crash-2022-05-21_19.29.28-server.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/8748575/crash-2022-05-21_19.29.28-server.txt)
[debug.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/8748577/debug.log)
[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/8748578/latest.log)

**Comment by ExcessiveAmountsOfZombies** [comment]
could you possibly remove this mod https://www.curseforge.com/minecraft/mc-mods/unordinary-basics and see if the issue persists? might need a world backup first, not sure what they add

**Comment by border999** [comment]
looks like the issue resolved. Not sure how this helped but it did.

**Comment by ExcessiveAmountsOfZombies** [comment]
yea i'm not sure. seems to think the crop has more ages than it actually does.
