### ISSUE TITLE
Castleblocks mod conflict

### ISSUE THREAD

**Issue by Houndquake** [ExcessiveAmountsOfZombies/Croptopia#388]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.2

### Croptopia version.

2.0.1

### What happened?

The knife in croptopia and the trowel in castleblocks are the same recipe

**Comment by Ayutac** [comment]
sounds like a modpack problem to me. We change the knife recipe and it will conflict with some other mod...

**Comment by ExcessiveAmountsOfZombies** [comment]
if you are playing a pre-made modpack, should make an issue in their repo. Otherwise if you're not making a modpack that you plan on releasing to the wider public (maybe just friends? or yourself) i'd recommend installing polymorph https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric
