### ISSUE TITLE
Fruit trees do not work with Serene Seasons

### ISSUE THREAD

**Issue by Tohricat** [ExcessiveAmountsOfZombies/Croptopia#393]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.0.3

### What happened?

Fruit trees have been setup for Serene Seasons functionality, however, their fruit crop blocks bear fruit during all seasons despite having tags for Serene Seasons.

**Comment by ExcessiveAmountsOfZombies** [comment]
#537
