### ISSUE TITLE
Forge tags implementation into recipes.

### ISSUE THREAD

**Issue by Warhand** [ExcessiveAmountsOfZombies/Croptopia#394]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

I feel like its a missed opportunity for inter-mod compatibility to not use forge tags in the croptopia recipes, especially since the croptopia crops all have the tags already assigned, it should be a fairly simple matter to convert the recipes to use tags instead of item registry names.

To further clarify, I mean making it so the recipe for something like pizza uses the tag "forge:vegetables/tomato" instead of the item ID "croptopia:tomato"

**Comment by ExcessiveAmountsOfZombies** [comment]
this is already the case [you can see it here as an example](https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/master/shared/src/main/generated/data/croptopia/recipes/cabbage_roll.json)
