### ISSUE TITLE
Internal Fabric API class used, causing world creation to fail with latest FAPI

### ISSUE THREAD

**Issue by apple502j** [ExcessiveAmountsOfZombies/Croptopia#396]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.2

### Croptopia version.

2.0.3

### What happened?

Croptopia uses `LootSupplierBuilderHooks` class in `CropLootTableModifier`:

```java
import net.fabricmc.fabric.mixin.loot.table.LootSupplierBuilderHooks;
```

```java
                    case "gameplay/fishing/fish" -> {
                        List<LootPool> pools = ((LootSupplierBuilderHooks) fabricLootSupplierBuilder).getPools();
```

Fabric API 0.54.0, released for 1.18.2 and 1.19, added Fabric Loot API v2 and deprecated the existing Loot Table API v1. This itself is fine. However, this also came with a refactor for internal code, **including removal of LootSupplierBuilderHooks class**. This causes `NoClassDefError` when **creating a new world**.

Mods should not try to use internal Fabric API classes, as they are subject to changes on any version.

### Relevant logs

https://cdn.discordapp.com/attachments/507982463449169932/982166112475181156/latest.log

### Additional information

- Fabric API 0.54.0

**Comment by ExcessiveAmountsOfZombies** [comment]
thank you, my bad this will be uploaded shortly
