### ISSUE TITLE
Origins: Classes crashing with Croptopia Trees

### ISSUE THREAD

**Issue by Ceifeire** [ExcessiveAmountsOfZombies/Croptopia#400]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.1

### Croptopia version.

1.8.3

### What happened?

Using Origins: classes with croptopia, if you have selected the Lumberjack class and use the automatic vein miner perk it crashes the game if chopping down a tree with a croptopia fruit block in it.

### Relevant logs

https://pastebin.com/062GVSb6 - crash log

### Additional information

Origins
Origins: Classes
Croptopia

**Comment by ExcessiveAmountsOfZombies** [comment]
This needs to be fixed on their end, here is the relevant line of code
https://github.com/LimonBlaze/origins-classes-forge/blob/1.18.2/src/main/java/limonblaze/originsclasses/util/MultiMineMode.java#L43
just need to check if it has persistence, which my leaves don't

**Comment by Ceifeire** [comment]
I will reach out to them concerning this.
