### ISSUE TITLE
mod not working for me 

### ISSUE THREAD

**Issue by Katlynnn420** [ExcessiveAmountsOfZombies/Croptopia#401]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

1.18.2

### What happened?

I put this mod on my server with everything I needed to but it’s still not working. I can see it in creative crafting menu  but not survival on the ground. 

### Additional information.

![image](https://user-images.githubusercontent.com/107745542/174426729-4da1ab40-3cf5-4b0d-946d-0fddb9b0f14f.jpg)

**Comment by ExcessiveAmountsOfZombies** [comment]
the mod needs to be installed on the server too. If you can see it in creative but not drop anything into the world it means the server doesn't have the mod installed
