### ISSUE TITLE
A "Crop Marketplace" block.

### ISSUE THREAD

**Issue by DiscoDude96** [ExcessiveAmountsOfZombies/Croptopia#402]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

I would like to suggest a new block called "Crop Marketplace" what this would do is, basically you would place it down and you would trade emeralds for crops you aren't able to find in your current biome. This would normally be obtained by trading with a villager or find it generated in villages (because that makes sense).
I've seen it in other food mods, and I think it would really spice up this one just a bit.
Thanks.

**Comment by Ayutac** [comment]
Against, it takes away the exploring part of Croptopia. A custom villager seems more appropiate.

**Comment by DiscoDude96** [comment]
Yeah, I guess making it craftable takes away the fun…

**Comment by ExcessiveAmountsOfZombies** [comment]
i'll be using a villager in the future, but if you have farming for blockheads installed, there is builtin support for their crop marketplace so you can buy seeds using that mod
