### ISSUE TITLE
Crafting Croptopia items with Farmer's Delight knives breaks them completely instead of using durability

### ISSUE THREAD

**Issue by James103** [ExcessiveAmountsOfZombies/Croptopia#404]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.0.5

### What happened?

When attempting to craft Croptopia recipes using a knife, the knife from Croptopia remains and can be reused, but the knife from Farmer's Delight instantly breaks when used to craft even a single item from Croptopia, even if it has more than one durability left.

I would expect that crafting Croptopia items with Farmer's Delight knives to just deal 1 durability damage to the knife used if it has durability, instead of the knife instantly breaking regardless of durability.

### Relevant log.

https://gist.github.com/James103/f7e9cda2708561816067eb13ab9a05df

### Additional information.

Originally reproduced in the mod pack ATM7 0.4.15, which includes Croptopia 2.0.5 and Farmer's Delight 1.1.2.
However, the same issue occurs when just those two mods are loaded with no other mods.

See also https://github.com/AllTheMods/ATM-7/issues/716

**Comment by ExcessiveAmountsOfZombies** [comment]
bug on my end
