### ISSUE TITLE
Patchouli Guide Book doesn't work

### ISSUE THREAD

**Issue by TeaCows** [ExcessiveAmountsOfZombies/Croptopia#405]
I have installed Patchouli and Croptopia as well as Fabric and the Fabric API. I have tried crafting the book, giving it through commands, and using the creative menu. No clue if I did something wrong, but I am stumped...

**Comment by ExcessiveAmountsOfZombies** [comment]
this is now fixed as of a few days ago for forge/fabric. the version to download is 2.0.6. Thanks!
