### ISSUE TITLE
About New Korean Translation

### ISSUE THREAD

**Issue by KaitheBlackCat** [ExcessiveAmountsOfZombies/Croptopia#406]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

[ko_kr.zip](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/8984254/ko_kr.zip)
This is the file.

I proposed the change(maybe) on github, If it doesn't show to you, then use the file above.

For Korean who are in curious,

cantaloupe : 흔히 마트에서 판매되는 네트 멜론과는 다른 종으로, 그냥 멜론이라 하기에는 모호하기 때문에 '캔털루프 멜론'이라고 결정

currant : '커런트'가 맞는 발음이지만, 공식적으로는 까치밥나무 열매가 맞습니다. '까치밥나무 열매'로 정정했습니다.

elderberry : 사전에서도 공식문서에서도 그리고 청소년 문학 작품에서도 모두 '딱총나무 열매'로 번역됩니다.

honeydew : 감로라는 단어는 익숙하지 않으므로 허니듀로 번역했습니다.

rutabaga : '스웨덴 순무'로 번역을 할 지, 아니면 루타바가로 남길 지 고민했습니다. 고유명사로 두는 것이 나을 것 같아 '루타바가'로 남겼습니다.

squash : squash호박과 애호박은 아예 다른 종입니다. squash는 스콰쉬 호박으로 번역했습니다.

zucchini : 이게 애호박입니다.

kumquat : 이 단어에 대해 '금귤'이 익숙한 지 '낑깡'이 익숙한 지 여러번 수소문을 해봤습니다만, 이 모드를 설치한 마인크래프트 플레이어가 금귤이란 단어에 익숙해지길 하는 마음에 금귤로 남기기로 했습니다. 낑깡은 일본어거든요.

pumpkin_spice_latte : 조리법은 한국에는 없는 것인데, 조리 과정에서 들어가는 pumpkin pie spice는 상당한 단 맛에 약간의 매콤함이 포함됩니다. 계피가루 같은 매움이라 고추 같은 매움과는 다릅니다. 따라서 매콤달콤 호박 라떼로 번역했습니다.

baked_beans : 영국인들이 사랑한다는 그 찐 콩 통조림이 생각난다면 그것이 맞습니다. 요리는 고유명사로 최대한 두려고 합니다.

멕시코 음식 : 대한민국 국립국어원 지정 스페인어 표기법에 의거하여 서술했습니다.

**Comment by ExcessiveAmountsOfZombies** [comment]
thank you and perhaps to [ssolephant](https://github.com/ssolephant) as well if any of their contributions were kept for the updated Korean translation. I'll try and get it added soon

**Comment by KaitheBlackCat** [comment]
I got some errors in my translation

"item.croptopia.raisin_oatmeal_cookie": "건포도 귀리 아이스크림"

This one should be changed to

"item.croptopia.raisin_oatmeal_cookie": "건포도 귀리 쿠키"

If you can change this, That will be very thankful, but if you can't, then I'll upload new version soon

**Comment by ExcessiveAmountsOfZombies** [comment]
yup I can do it, thank you!
