### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by cfpwastaken** [ExcessiveAmountsOfZombies/Croptopia#407]
Would be great if this mod would be on modrinth too.

**Comment by ExcessiveAmountsOfZombies** [comment]
it's a possibility for the future when it becomes a more mature platform. thank you though

**Comment by Sammcb** [comment]
Just curious, any new thoughts on this? I would love to see this on modrinth (I'm developing a modpack management script that relies on the modrinth API)! Thanks!

**Comment by ExcessiveAmountsOfZombies** [comment]
nothing has really changed imo, though I thought of a mod I might share on there if I ever make it.

**Comment by K0-RR** [comment]
Hi, @ExcessiveAmountsOfZombies I wanted to ask if you could reconsider Modrinth. They have since made their own launcher, monetization has been a thing for a while.
This mod is the only one in my 86 mods modpack that comes from the Cursedforge.

**Comment by RealHypnoticOcelot** [comment]
I'd like to see this reconsidered as well

**Comment by RandomlyZay** [comment]
Any chance you’d reconsider putting this mod on Modrinth? It’s come a long way with its own launcher and monetization, and it’d be awesome to have all the mods in my pack in one place. There’s really no downside to putting your mod on there, and it could bring in some extra revenue, so it seems like a no-brainer to me. Thanks!

**Comment by TheSokoL1337** [comment]
The Modrinth website is actively developing, and it would be great to upload a mod to it. This is because users are actively interested in it, and the site itself has become larger compared to 2022.

**Comment by Boden-C** [comment]
Hello, can we get a more specific reason why you are denying Modrinth so we can understand this situation better? Is it a licensing issue, money issue, or something else? The only reason I could find was "not mature enough" 2+ years ago, which seems vague and now outdated.
