### ISSUE TITLE
Compatibility with Serene Seasons

### ISSUE THREAD

**Issue by MMVVMM** [ExcessiveAmountsOfZombies/Croptopia#411]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

**Minecraft Version** 
1.16.5
**Mod Version**
2.0.5
**Description**
It seems that the compatibility with Serene Seasons is missing in the new version of the mod.I have tested that copying tags from the old version can easily fix the problem.

**Comment by ExcessiveAmountsOfZombies** [comment]
#537
