### ISSUE TITLE
How to get shrimp (Add shrimp to aquaculture loot tables)

### ISSUE THREAD

**Issue by DiscoDude96** [ExcessiveAmountsOfZombies/Croptopia#414]
I saw shrimp in the creative inventory but never found a survival recipe for it. I assumed it came from mob drop but no, i tried searching it up on the wiki, but the dumbasses only had the crops listed. 
I then scoured the web looking for somebody with the same issue, found none.
I then proceeded to look into the contents of the jar folder, And when i went into the fishing lootpools and saw shrimp, fished for hours and never got any. Maybe I have brain damage or this is just an issue nobody shares. This isnt an issue for me I just got too curious.

**Comment by DiscoDude96** [comment]
I have Aquaculture too. So maybe the loot tables made it too rare to get.

**Comment by ExcessiveAmountsOfZombies** [comment]
you'll need to use a vanilla fishing rod as the aquaculture rods use their own loot tables.

**Comment by DiscoDude96** [comment]
oh thanks!
