### ISSUE TITLE
Croptopia failed to load correctly with Forge 41.0.64+

### ISSUE THREAD

**Issue by Gamemassa** [ExcessiveAmountsOfZombies/Croptopia#415]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19

### Croptopia version.

2.0.6

### What happened?

I started up Forge with Croptopia and got the following error message:
![image](https://user-images.githubusercontent.com/18667108/178145960-65066845-3eb1-4b09-8c03-e1573956a3a7.png)

### Relevant logs

[crash-2022-07-10_08.58.57-fml.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/9079103/crash-2022-07-10_08.58.57-fml.txt)

**Comment by ExcessiveAmountsOfZombies** [comment]
i'll give it a couple more days and then update again. forge renamed a bunch of stuff again.

**Comment by Gamemassa** [comment]
Yeah, I noticed that as well. IDK why they keep doing that but I'd imagine it's kinda annoying for mod developers.

**Comment by ExcessiveAmountsOfZombies** [comment]
been fixed since the 16th
