### ISSUE TITLE
Croptopia's fish can't be fished up while using 'Fishing Overhaul'.

### ISSUE THREAD

**Issue by TheDerpu0ne** [ExcessiveAmountsOfZombies/Croptopia#417]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.0.5

### What happened?

It seems you can't fish up any of the modded fish this mod adds with the Fishing Overhaul mod, I might be fishing in the wrong places or juts getting stupidly unlucky but I can't fish up any.

### Additional information.

If it is helpful, on the fishing rod I am using I have: mending, unbreaking 3, luck of the sea 3 and lure 3.

**Comment by TheDerpu0ne** [comment]
@ExcessiveAmountsOfZombies ?

**Comment by ExcessiveAmountsOfZombies** [comment]
oh, sorry, I think I targeted the wrong table when I made the fishing changes. I thought I remember it working with fishing rods but I guess not. I noticed this in 1.19 but I'll port it back to 1.18 soon

**Comment by TheDerpu0ne** [comment]
oh thanks!
