### ISSUE TITLE
Pick-block not capable for the modded leaves

### ISSUE THREAD

**Issue by SomeCrbn** [ExcessiveAmountsOfZombies/Croptopia#42]
When I try to use the middle mouse button to grab the leaf block, it doesn't do anything. When going into f3 I can see that it is indeed a block, it just seems that you cant harvest or hold it in any form whether in creative or survival. 
-C_rbn

**Comment by SomeCrbn** [comment]
Ah, it appears that the leaves are registered as a crop, not a leaf block. Therefore you can walk/fall through them. They are like a fully grown wheat plant, you can't grab them, only break them. That is also why you can walk straight through them with no collision. You need to make them into blocks and make it so they will break when wood is not nearby.

**Comment by ExcessiveAmountsOfZombies** [comment]
Intentional that you cant block pick them, falling through them has been fixed and they will also now decay in 1.2.0
