### ISSUE TITLE
Doesn't work on servers

### ISSUE THREAD

**Issue by LonelyBrat** [ExcessiveAmountsOfZombies/Croptopia#420]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.16.5

### Croptopia version.

1.4.0

### What happened?

It doesn't seem to work in multiplayer worlds. I added it to my server so we could have more food options (obviously) and it wouldn't function properly. We cannot eat or drink most of the items, we can't plant the saplings and when we enter chests any of the mod items in our inventories would vanish. It works perfectly on singleplayer worlds.

### Additional information.

The mods we are using in the server alongside it are: Extra Origins, Fabric api, lank, mob origins, optifabric, optifine,  origins, origins classes, origins umbrellas, pehkui, quickhomes, sit, xaero's minimap, croptopia and patchouli

**Comment by Ayutac** [comment]
Is the mod installed on the client side

**Comment by ExcessiveAmountsOfZombies** [comment]
the mod isn't installed on the server
