### ISSUE TITLE
Croptopia plant growth crashing server

### ISSUE THREAD

**Issue by mnfu** [ExcessiveAmountsOfZombies/Croptopia#424]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.0.5

### What happened?

From what I can gather, It seems to be trying to grow Croptopia crops / trees, then crashing

### Relevant logs

https://mclo.gs/PJDhgq9
(Scroll to very bottom, of course)

### Additional information

This is on the latest release of 1.18.2 Magma-Forge
(Forge v40.1.54)

What I am not sure of, is if this is an issue relating to magma, 
or if switching to base 1.18.2 Forge's latest version would resolve the issue. (Since magma is behind)

**Comment by ExcessiveAmountsOfZombies** [comment]
I believe this is going to be an issue with magma, i'm sure you've heard many times in the past that forge/bukkit hybrids just don't work well together (i really wish they could). When I look at the MC code for 1.18.2 I don't even see a setTreeType method so I don't really know what's wrong

**Comment by mnfu** [comment]
Alright, I'll switch to regular forge then.
