### ISSUE TITLE
Can't find fish

### ISSUE THREAD

**Issue by BlackJamesYT** [ExcessiveAmountsOfZombies/Croptopia#425]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.0.1

### What happened?

I can sqee on JEI menu some fishes from Croptopia but in patchouli's book nothing is writen and I can't catch them with fishing rod.

Is there a way to find any fish or they are not yet implemented or supported ?

**Comment by drakray** [comment]
same question, I fished more than 200 items in an Ocean and nothing from Croptopia :(
Minecraft 1.18.2
Forge 40.1.73
Croptopia 2.0.5
buncha other mods

**Comment by ExcessiveAmountsOfZombies** [comment]
I believe this will be fixed in 2.1.0, I was pointed at the wrong table
