### ISSUE TITLE
[1.16.x forge] Thermal Series Phytogenic Insulator recipe for coffee seeds yields fully processed coffee

### ISSUE THREAD

**Issue by NyanMC** [ExcessiveAmountsOfZombies/Croptopia#426]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.16.5

### Croptopia version.

2.0.5

### What happened?

looking at the uses for coffee seeds, there is a phytogenic insulator recipe which takes coffee seeds and results in coffee cups. the expected result is that it would yield coffee *beans* instead.

### Additional information.

relevant image:
![image](https://user-images.githubusercontent.com/44331238/183254505-ca99c88c-ae4d-4127-a6c9-2d1943be87d8.png)
i recreated this issue on a new curseforge modpack instance using the following mods:
Croptopia-1.16.5-FORGE-2.0.5.jar
cofh_core-1.16.5-1.5.0.11.jar
thermal_foundation-1.16.5-1.5.0.14.jar
thermal_expansion-1.16.5-1.5.0.7.jar
jei-1.16.5-7.7.1.152.jar

**Comment by ExcessiveAmountsOfZombies** [comment]
#537
