### ISSUE TITLE
[1.16.5] Tooltip for manual still says Let me know if patchouli is updated....

### ISSUE THREAD

**Issue by ProsperCraft** [ExcessiveAmountsOfZombies/Croptopia#428]
### Make sure you are not opening a duplicate.

- [ X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.16.5

### Croptopia version.

Patchouli-1.16.4-53.3

### What happened?

![image](https://user-images.githubusercontent.com/4427684/184355089-390d3829-3f6f-4c03-a084-a7833e62a3f9.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
#537
