### ISSUE TITLE
[Suggestion] Salt compatibility please!

### ISSUE THREAD

**Issue by adamkad1** [ExcessiveAmountsOfZombies/Croptopia#430]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Most recipes seem to work exclusively with croptopia salts, which is slightly bothersome when you have other mods with salts. Also would be nice if croptopia salt had 'forge:salt' tag too, so its compatible the other way too! (for 1.18.2)

**Comment by ExcessiveAmountsOfZombies** [comment]
I believe this will be fixed in 2.1.0. I'll continue using forge:salts but I'll point forge:salt to it too

**Comment by Sinapsa** [comment]
Hello,
salt is still incompatible with other salts on fabric. They use c:salt_dusts tag.
