### ISSUE TITLE
Empty Tag: forge:cheese

### ISSUE THREAD

**Issue by SugarDaddii** [ExcessiveAmountsOfZombies/Croptopia#435]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.1.0

### What happened?

i think you add a wrong tag to the cheese tag because your cheese has the forge tag cheeses and you need the cheese tag
so many cheese tags XD

### Additional information.

https://imgur.com/a/baFVwxU

**Comment by Arkiln** [comment]
Having the same issue here on 1.20.1 - all Croptopia recipes involving cheese seem to use the "forge:cheeses" tag instead of "forge:cheese".
Mod version is Croptopia 3.0.4.
