### ISSUE TITLE
Collect foliage

### ISSUE THREAD

**Issue by ArtemVayl** [ExcessiveAmountsOfZombies/Croptopia#436]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.16.5

### Croptopia version.

2.0.5

### What happened?

I am trying to extract fruits from the foliage with the right mouse button, but it is not extracted, although the fruit has already grown.I'm playing 1.16.5, by the way, where can I find cinnamon and coffee?

**Comment by ExcessiveAmountsOfZombies** [comment]
You an find cinnamon and coffee in jungles, but otherwise i'm not really maintaining 1.16.5 anymore. There must be a mod incompatibility
