### ISSUE TITLE
Cant put anything in a chest or drop 

### ISSUE THREAD

**Issue by Floatwhimsclal** [ExcessiveAmountsOfZombies/Croptopia#438]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19

### Croptopia version.

2.0.7

### What happened?

when i put food into my inventory from creative to put into a chest it just disappears from my inventory all together and i cant drop anything at all from my hot bar. 

### Additional information.

https://user-images.githubusercontent.com/112532024/187584955-ed4807b3-0b92-4d02-8f8d-d9a3e3afcfee.mov

**Comment by ExcessiveAmountsOfZombies** [comment]
mod isn't installed on the server
