### ISSUE TITLE
Croptopia and biomes o plenty

### ISSUE THREAD

**Issue by Anettei** [ExcessiveAmountsOfZombies/Croptopia#443]
- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

i figured out what i wanted to say. 

I was playing on a new world and I couldnt find any fruit trees anywhere. i was in a vanilla plains biome but never came across and fruit trees or cinnamon. I was wondering if this is a problem on croptopias end 1.18.2 2.1.0 or biome o plenty 1.18.2 16.0.0

**Comment by emanuele246gi** [comment]
I have this issue too, I play mostly with Terraforged, but it shouldn't compromise trees generation

**Comment by ExcessiveAmountsOfZombies** [comment]
#537, fixed in 1.20(.1)
