### ISSUE TITLE
Quilt standard library crashes with croptopia on create new world screen

### ISSUE THREAD

**Issue by offbeat-stuff** [ExcessiveAmountsOfZombies/Croptopia#447]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

2.1.0

### What happened?

I clicked the singleplayer screen, I currently have no worlds and it crashed

### Relevant logs

[crash-2022-09-16_07.43.25-client.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/9580082/crash-2022-09-16_07.43.25-client.txt)

### Additional information

I am using quilt mod loader.
If this wont be supported, please tell that in the description.

**Comment by lospejos** [comment]
Have the same issue with server running on `qfapi-4.0.0-beta.12_qsl-3.0.0-beta.16_fapi-0.61.0_mc-1.19.2`

**Comment by koelle25** [comment]
I can recreate the issue with just the 2 mods `Croptopia-1.19.2-FABRIC-2.1.0` and `qfapi-4.0.0-beta.13_qsl-3.0.0-beta.16_fapi-0.62.0_mc-1.19.2` on **Minecraft 1.19.2** with **Quilt Loader 0.17.5-beta.3**.

Here are my logs:
[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/9692385/latest.log)
[crash-2022-10-02_13.50.34-client.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/9692386/crash-2022-10-02_13.50.34-client.txt)

Some maybe relevant errors:
```
[13:50:31] [Render thread/ERROR]: Parsing error loading recipe croptopia:banana_cream_pie
com.google.gson.JsonSyntaxException: Missing ingredient, expected to find a JsonObject
...
[13:50:32] [Render thread/WARN]: Failed to validate default data-pack.
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException
...
[13:50:34] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
```

@lospejos Your error message is slightly different due to the NotEnoughCrashes mod. Other than that it seems to be the same.

**Comment by KJP12** [comment]
Something that might be useful to note: The following block changes the backing map out for an ImmutableMap with new items:
https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/6e140b000da59b316ba174aae64239ed2903ceac/fabric/src/main/java/com/epherical/croptopia/Croptopia.java#L120-L128

QSL however, expects a mutable map, changing it out here:
https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19/library/block/block_content_registry/src/main/java/org/quiltmc/qsl/block/content/registry/mixin/AxeItemMixin.java#L43

And using it here:
https://github.com/QuiltMC/quilt-standard-libraries/blob/8c80a0e36598efce2ad4e89cb50e6d543a9e66a8/library/block/block_content_registry/src/main/java/org/quiltmc/qsl/block/content/registry/impl/BlockContentRegistriesInitializer.java#L95-L102

*For some reason, the preview doesn't want to work, but they are functional links to the actual code.*

**Comment by qtow** [comment]
On Fabric, strippable blocks should be registered via [`StrippableBlockRegistry#register`](https://github.com/FabricMC/fabric/blob/0ac263625eab530129108eebe8262931b0fbc13e/fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/api/registry/StrippableBlockRegistry.java#L49). QSL supports this as well. I'm not sure if there's an equivalent for Forge.

**Comment by ExcessiveAmountsOfZombies** [comment]
#460
