### ISSUE TITLE
Mod compatibility with Farming for Blockheads

### ISSUE THREAD

**Issue by AngleWyrm10** [ExcessiveAmountsOfZombies/Croptopia#448]
- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.
- Farming for Blockheads has a seeds & saplings salesman that sells for emeralds

**Comment by ExcessiveAmountsOfZombies** [comment]
2.1.1 will include saplings, it already had seeds
