### ISSUE TITLE
Chickens can't be fed or bred with any seeds. 

### ISSUE THREAD

**Issue by DoctorineLisa** [ExcessiveAmountsOfZombies/Croptopia#449]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.18.2 

### Croptopia version.

2.1.0

### What happened?

I'm not sure why, but the chickens cannot be fed or bred with any type of seeds.

**Comment by DoctorineLisa** [comment]
I noticed there was another thread open for a previous version. My apologies. I also just found that the chickens can be bred with croptopia seeds but not regular seeds.

**Comment by ExcessiveAmountsOfZombies** [comment]
This might be fixed in 2.1.1 from Siphalor's PR
