### ISSUE TITLE
The Frying Pan is Still to Op

### ISSUE THREAD

**Issue by EnvyEnfys** [ExcessiveAmountsOfZombies/Croptopia#45]
**1.20**
Which version of Croptopia are you using?

**fabric**
Which platform are you using Croptopia on?
(Fabric, Forge)

**The frying pan still has a crazy swing speed, it being 2 makes its the quickest weapon with attack dmg of 8, id suggest making the dmg MUCH lower and Attack speed to 0.8 or something Maybe like 6Dmg with a attack of 0.8**
A clear and concise description of what the issue is.

**Comment by ExcessiveAmountsOfZombies** [comment]
i've gone ahead and just given it the same attack speed and damage as an iron sword now, will be released sometime soon
