### ISSUE TITLE
Sea Lettuce

### ISSUE THREAD

**Issue by DQuinn97** [ExcessiveAmountsOfZombies/Croptopia#450]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.1.0

### What happened?

Not sure where to put this because I'm not sure it's a bug..

How do we obtain sea lettuce? I can't find any seed or recipe for it, there is nothing about it on any wiki yet I do have some in my storage so I know we **can** get it, just don't know where from.

**Comment by ExcessiveAmountsOfZombies** [comment]
You can get it from fishing
