### ISSUE TITLE
Villagers not replanting Croptopia seeds

### ISSUE THREAD

**Issue by Gamemassa** [ExcessiveAmountsOfZombies/Croptopia#451]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

2.1.0

### What happened?

I'm not actually sure if this is a bug or if this behavior is intended, but I tried making automated farms of some of the crops in Croptopia (using villagers and hoppers, as can be done with the vanilla crops like potatoes and carrots), and the villagers don't seem to be replanting the seeds for Croptopia Plants.

**Comment by Gamemassa** [comment]
@ExcessiveAmountsOfZombies Hi, just wondering if I could get an update on this?

**Comment by ExcessiveAmountsOfZombies** [comment]
after my semester is over in a couple months, im going rewrite the mod again to fix these features for fabric and forge and make sure there is parity.

**Comment by Gamemassa** [comment]
> after my semester is over in a couple months, im going rewrite the mod again to fix these features for fabric and forge and make sure there is parity.

Oh cool. Thanks for confirming. Also, good luck with your classes!

**Comment by Gamemassa** [comment]
@ExcessiveAmountsOfZombies Hi, just curious if you've been able to look at this at all since last time.

Also, how are your classes going?
