### ISSUE TITLE
Editing config file "croptopia-common" doesnt affect Tree´s biomes

### ISSUE THREAD

**Issue by jnsn98** [ExcessiveAmountsOfZombies/Croptopia#455]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19.2

### Croptopia version.

2.1.0

### What happened?

For example, if I want Orange trees to only generate in Jungle biomes and not in forests, I delete all biomes from "orange_tree_configured"-list and replace "minecraft:forest" with "minecraft:jungle" but this doenst do anything.

Is this even intended to be edited like that or is it a bug?

Im Currently Using Croptopia-1.19.2-FORGE-2.1.0

![orange trees](https://user-images.githubusercontent.com/115877474/195985843-09c57975-29e2-477f-901a-3310ab9fad2b.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
This will be fixed in the next version, but in an even later version it'll probably be removed and placed into a datapack
