### ISSUE TITLE
Saturation is broken

### ISSUE THREAD

**Issue by Jadarda** [ExcessiveAmountsOfZombies/Croptopia#456]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.1.0

### What happened?

The saturation is broken. Doesnt work as intended. like for example the pie is setted on 28 full saturation hams. but only refills 10.

**Comment by Ryan-pelo** [comment]
I came here also wondering about this. I don't understand why some foods give over 10 saturation bars if saturation maxes out at 10. Am I missing something or can someone can shed some light on this?

**Comment by Jadarda** [comment]
> I came here also wondering about this. I don't understand why some foods give over 10 saturation bars if saturation maxes out at 10. Am I missing something or can someone can shed some light on this?

For sure it does not work like that, ive tested it and it does not.

**Comment by ExcessiveAmountsOfZombies** [comment]
I'll rebalance things this winter
