### ISSUE TITLE
Nerf the amount of saturation you get from food

### ISSUE THREAD

**Issue by FnigePython** [ExcessiveAmountsOfZombies/Croptopia#458]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

![image](https://user-images.githubusercontent.com/35159947/197386781-cd43a2f7-aee8-4a3a-826a-0e50903081db.png)

Ima be honest stuff like this is way too much saturation

At max 2.5x compared to the food value would be best, of course being less saturating the simpler the meal is

**Comment by ExcessiveAmountsOfZombies** [comment]
There shouldn't be any foods that provide more than 20 saturation anymore.
