### ISSUE TITLE
Quilt crash on world load or new 

### ISSUE THREAD

**Issue by EightBlade** [ExcessiveAmountsOfZombies/Croptopia#460]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

2.1.2

### What happened?

I installed croptopia and attempted to both create a new world and open an existing one. Both resulted in crashes.

### Relevant logs

https://pastebin.com/qvkReR9z

**Comment by ItsKipz** [comment]
Experiencing the same issue, happens across Croptopia versions 2.0.8 to 2.1.2 and Quilt versions 0.17.6 and the latest beta 8 for 0.18.1.

**Comment by EightBlade** [comment]
I tried 2.0.5 on quilt and it crashed. Here's the log: https://pastebin.com/p5S5bU3Z

**Comment by Cazcez** [comment]
I have same issue on 1.19.2, 2.1.12

**Comment by ArcheCraft** [comment]
Issue seems to be that Quilt makes the AxeItem#STRIPPABLES mutable, and Croptopia overrides it with an immutable Map here:
https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/6e140b000da59b316ba174aae64239ed2903ceac/fabric/src/main/java/com/epherical/croptopia/Croptopia.java#LL120C24-L120C24
There is a Fabric-API way to do this, which would also be compatible with Quilt. Maybe consider using that?

**Comment by ExcessiveAmountsOfZombies** [comment]
when I wrote this bit of code I don't think the Fabric-API had a way to add blocks to the register, so now that it does, when I rewrite the mod again in a few weeks this might be fixed.

**Comment by ExcessiveAmountsOfZombies** [comment]
Probably fixed? I'm using the fabric API now but I don't test with quilt

**Comment by koelle25** [comment]
I can confirm it works flawlessly now (on Quilt 1.19.2).
