### ISSUE TITLE
Pepper & Tea Seeds aren't treated the same as other seeds.

### ISSUE THREAD

**Issue by CypherHyena** [ExcessiveAmountsOfZombies/Croptopia#462]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.1.0

### What happened?

I'm playing on an ATM7 1.18.2 server that I host.

I grow most of my crops in Phytogenic Insolators from Thermal, or Garden Cloches. Every Croptopia seed I've tried has worked perfectly in those machines, except Tea and Pepper.

Pepper seeds are not a valid input into the machines. Pepper also doesn't have a JEI Recipe to create. Clicking Pepper in JEI doesn't pop anything up saying you can get it by growing the seeds in anything. Seems it only works with traditional farming methods.

Is this something that can be fixed?

Thanks!

Chris Vogel

**Comment by James103** [comment]
Same issue occurs in ATM8 (tested in pack version 1.0.4, but also happens in pack version 1.0.5)

Minecraft 1.19.2
Croptopia 2.1.0
