### ISSUE TITLE
Croque Monsieur and Croque Madame recipes need fixing

### ISSUE THREAD

**Issue by Guinaro** [ExcessiveAmountsOfZombies/Croptopia#463]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.1.0

### What happened?

Croque Monsieur and Croque Madame recipe reference the tag forge:cheese
While actually the tag in the recipe should be forge:cheeses (last s missing)
Or you made a typo when creating the forge:cheeses tag, where it should have been forge:cheese instead.

I currently use my own datapack to fix the recipe to use cheeses instead of cheese.

This probably is related to issue #435 aswell.

**Comment by ExcessiveAmountsOfZombies** [comment]
Recipes fixed in 2.2.0
