### ISSUE TITLE
Grafting the Tree of 40 Fruits

### ISSUE THREAD

**Issue by yamitami** [ExcessiveAmountsOfZombies/Croptopia#465]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

I definitely understand if this would interfere with what you're going for and/or be too much of a hassle to implement, but it would be neat to have an immersive grafting mechanic since [fruit trees can be grafted to ridiculous extremes](https://en.wikipedia.org/wiki/Tree_of_40_Fruit).

Instead of regular silk touching the leaves a grafting blade or kit could be crafted and that would be the only tool that could drop the crop leaves, with a limited durability so it is still something you have to work for. Moss can be used IRL to keep things hydrated, string to bind the graft to the host, a water bottle maybe. The elements that would be easiest to control the difficulty with would be the cutting implement and a grafting serum.

If you wanted durability ranges for the tool then swords would make sense for the cutting implement, but probably just a standard set of shears makes the most sense. The serum could be made of anything that vaguely makes sense and can easily involve more or less expensive/hard to find items, from milk and wheat to the likes of slime, honey/wax, moss/glowberries/etc. or even lock it behind the nether by requiring warped mushrooms or nether wart.

Then the crop leaves can be left with persistence off so they have to be grafted to a log to 'live', allowing for custom shaped trees, forming them into hedges along walls, or multiple crops on one tree without making it super easy.

**Comment by Ayutac** [comment]
You can already put different fruits on the same tree. I see no point in this, besides making trees a lot harder for Croptopia regulars

**Comment by yamitami** [comment]
Wait, how can you do that?

**Comment by yamitami** [comment]
I must've only been finding old info since the best option I found was to bonemeal a tree under remaining leaves and hope for the best. Disregard!
