### ISSUE TITLE
Crafting recipe oddities

### ISSUE THREAD

**Issue by AdipemDragon** [ExcessiveAmountsOfZombies/Croptopia#47]
**Version**
1.2.0 - within All of Fabric, version 2.6.1

**Platform**
Fabric

**Describe the issue**
Some crafting recipes are kinda wonky: 
- Salsa requires a glass bottle in its recipe but it isn't refunded, is the glass just shattered between the 4 resulting salsas?
- Only some items that contain a bottle in their recipe return the bottle when they're crafted into other things: for example, making Rum Raisin Ice Cream with Soy Milk returns the bottle for the Soy Milk item but not for the Rum item, which Does return the bottle when eating it normally.
- 2 of the pizzas don't need a skillet in their recipe, while the rest do: the weirdest is how you swap the skillet for More Cheese in the Cheese Pizza recipe, compared to the regular Pizza.
- Saucy chips only need a salsa/artichoke dip _and an empty bowl_, nothing else. Don't even get the bowl back when it's eaten.
- Actually, harping back on the saucy chips, None of the items that have a bowl in their recipe give it back after it's been eaten. All of these just eat the bowl.
![image](https://user-images.githubusercontent.com/76874615/107043846-34b1f800-67cc-11eb-9069-8675394a8a87.png)
- Tuna Sandwiches, Cheese Cakes, Snicker Doodles and Banana Nut Breads don't have a recipe, as also mentioned in [this issue](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/20).
> That issue also mentions the overlap between Banana, Strawberry and Fruit Smoothies, but the AoF3 modpack seems to have a method of solving overlapped recipes with multiple outcomes, it's still an issue but it's somewhat solved in that context.
- Speaking of missing recipes: Pecan Pie doesn't have a recipe, but Cherry Pie has 2 recipes, one of which is the Pecan Pie one.

**To Reproduce**
Play the mod? This took no preparation, just load the modpack and it just is Like That.

**Other Mods**
Just straight up [version 2.6.1 of All of Fabric 3.](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/3189815)

**Comment by FewerFlaws** [comment]
Also, putting Jam on toast doesn't make it any more filling >_<

**Comment by ExcessiveAmountsOfZombies** [comment]
most of these have been fixed now in either 1.3.0 or 1.3.1
