### ISSUE TITLE
Game crashes whenever I right click any crop

### ISSUE THREAD

**Issue by XeroXavion** [ExcessiveAmountsOfZombies/Croptopia#470]
**If anyone else is recieving this issue. The cause is that the mod is incompatible with the latest version of spectrum, go down a version (in spectrum) and the issue should be resolved.**

### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

1.19.2-FABRIC-2.1.2 

### What happened?

Whenever I right click any crop from this mod, my client crashes. 

I've got a server up and only the client appears to crash from this, the server does not crash.

I don't get any crash logs when this happens, My client just leaves the world and closes the game by itself. Checking the aternos server log, I get this error whenever a player right clicks a crop or tree crop: (check relevant logs)

### Relevant logs

<html><body>

[03:27:59] [Netty Epoll Server IO #2/ERROR]: Exception occurred in netty pipeline
--
 

<span class="level level-error multiline">io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer</span>
</body>
</html>

### Additional information

I have 76 mods total but this issue is new as it was not happening a week or two ago. My guess is that it could be another mod as I have updated a few but I am not completely sure about this and just wanted to put this up incase it is a standalone issue since the mod has no dependancies apart from the fabric API.

**Comment by DarkCrystalll** [comment]
I have the same problem
Whenever I right click any crop from this mod, my client crashes.
[minecraft-exported-crash-info-2022-11-24T17-01-03.zip](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/10082474/minecraft-exported-crash-info-2022-11-24T17-01-03.zip)

**Comment by DarkCrystalll** [comment]
another player's crash log
[minecraft-exported-crash-info-2022-11-24T17-15-40.zip](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/10082935/minecraft-exported-crash-info-2022-11-24T17-15-40.zip)

**Comment by Ayutac** [comment]
> I have 76 mods total but this issue is new as it was not happening a week or two ago. My guess is that it could be another mod as I have updated a few but I am not completely sure about this and just wanted to put this up incase it is a standalone issue since the mod has no dependancies apart from the fabric API.

Well have you TRIED it with only Croptopia? Would resolve it really quick if this is a Croptopia bug...

Also we would need a complete error log

> minecraft-exported-crash-info-2022-11-24T17-01-03.zip
Who tf is writing the 1's in the console log??? Anyway, there are many errors in your log, have you tried with Croptopia Standalone?

**Comment by DarkCrystalll** [comment]
I am not familiar with the log of the crash environment. I use the crash information that comes with the Chinese initiator called HMCL. This paragraph is also a machine translation in English.I'm sorry about this

**Comment by XeroXavion** [comment]
> Well have you TRIED it with only Croptopia? Would resolve it really quick if this is a Croptopia bug...

I didn't think of doing that since it was working a week or two ago, must've been a mod update causing it then since it works as normal by itself.

Luckily I have the list of mods that were updated so I can just go over them one at a time to see which mod is causing the issue

I'll close the issue once said mod is identified to show a possible incompatibillity

**Comment by DarkCrystalll** [comment]
I'm checking mod conflicts one by one

**Comment by XeroXavion** [comment]
List & result:
Fabric API - safe
GeckoLib - safe
Jade - safe
Journey map - safe
Mod menu - safe
Relic EX - safe
Spectrum - Crashes
Piercing Paxels - safe

Croptopia appears to be incompatible with the latest version of **Spectrum.**

**Comment by Ayutac** [comment]
> I don't know how to pull out a crash log if my client just closes after interacting with the crop (with no notice, so I don't get like a crash report or anything. the client just closes itself)

If you don't use the Minecraft Launcher but something like MultiMC, the crash log will be accessible even after the client closes. The log is probably somewhere present with the OG Launcher too, but I wouldn't know where.

**Comment by DarkCrystalll** [comment]
[minecraft.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/10083837/minecraft.log)
yes,is spectrum

**Comment by XeroXavion** [comment]
Right, Strangely enough, re-opening the ORIGINAL client after the modded client crashes gives me the crash report, weird.

Anyway, this should be the log: 
[Crash report 001.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/10083869/Crash.report.001.txt)

**Comment by DarkCrystalll** [comment]
In local world testing, it seems to cause archive corruption

**Comment by XeroXavion** [comment]
Sorry if solved cases aren't meant to be posted here. But I contacted spectrum's devs and I'm pretty sure the issue was Identified code wise.

Going off what they said, The afterBlockBroken() method should only be run serversided

https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/8bb89cf46d971d1bc079e41f401578d8aa46c3e2/shared/src/main/java/com/epherical/croptopia/blocks/CroptopiaCropBlock.java#L76

I don't know much about java so I can't give a second mark but I hope this helps

**Comment by Landon-9999** [comment]
Thonk already knows about this bug in #467. I think there is a workaround for this until he works on Croptopia again. He told another user to use this mod until then: (https://www.curseforge.com/minecraft/mc-mods/rightclickharvest)
