### ISSUE TITLE
1.19.2 Fabric Crash on Placing Croptopia Seed for First Time

### ISSUE THREAD

**Issue by valkyrienyanko** [ExcessiveAmountsOfZombies/Croptopia#471]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

2.1.2

### What happened?

Placed a artichoke seed on farmland and game crashed.

### Relevant logs

[crash-2022-11-25_20.02.26-client.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/10095482/crash-2022-11-25_20.02.26-client.txt)

[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/10095483/latest.log)

### Additional information

Reproduce by playing [The Energy Race](https://www.curseforge.com/minecraft/modpacks/the-energy-race) (ver. 11)

**Comment by ExcessiveAmountsOfZombies** [comment]
nothing else causes this? just croptopia seeds being placed for the first time?

**Comment by valkyrienyanko** [comment]
The croptopia peach / orange / walnut trees work fine. Just placing the croptopia seeds makes the game crash to desktop.
