### ISSUE TITLE
Croptopia failed to load correctly - "java.lang.reflect.InvocationTargetException"

### ISSUE THREAD

**Issue by AyUpItsAli** [ExcessiveAmountsOfZombies/Croptopia#473]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19.2

### Croptopia version.

2.1.0

### What happened?

I've setup a new modding project, completely blank with no content added yet. I added Croptopia as a dependency for my mod but it failed to load when launching. The dependency is pointing to this file in my build.gradle: https://www.curseforge.com/minecraft/mc-mods/croptopia/files/3947784

I don't know anything about mixins, but the error seems to be to do with them in some way. Something about LootTableAccessor and MixinTransformer.

### Relevant logs

[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/10125717/latest.log)
[crash-2022-11-30_17.14.49-fml.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/10125718/crash-2022-11-30_17.14.49-fml.txt)

### Additional information

For reference in the logs, my mod is "Ali's Bean Mod" but it should (hopefully) not be effecting anything as I've not actually added anything yet; it just consists of a blank mod class at the moment.

**Comment by ExcessiveAmountsOfZombies** [comment]
i'm not sure, i guess make sure you've followed all this? https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge

**Comment by AyUpItsAli** [comment]
> i'm not sure, i guess make sure you've followed all this? https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge

Oh, so you have to have mixin setup if you have any dependencies that use it?

**Comment by ExcessiveAmountsOfZombies** [comment]
I think that's a requirement, yes. the other option would be to clone the repo, and build it locally into your mavenlocal but I think that method above would fix your issue.

**Comment by AyUpItsAli** [comment]
> I think that's a requirement, yes. the other option would be to clone the repo, and build it locally into your mavenlocal but I think that method above would fix your issue.

Yes that seems to have fixed it! Thank you!

For anyone wondering, this is what was added to my build.gradle to fix the issue. Just sets up the mixin plugin so croptopia loads correctly:
```
buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath group: 'org.spongepowered', name: 'mixingradle', version: '0.7-SNAPSHOT'
    }
}

apply plugin: 'org.spongepowered.mixin'
```
