### ISSUE TITLE
"Not A JSON object" on Multiplayer Modpack Server

### ISSUE THREAD

**Issue by bumblebwee** [ExcessiveAmountsOfZombies/Croptopia#474]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19.2

### Croptopia version.

2.1.0

### What happened?

Me and another person had recently updated BetterMC (I plan on writing this out to that github too) and somewhere between the last update and this most recent update, something broke. Whenever I open the server, the message I get looks like this; it will say this about a randomly generated fruit/veggie/etc if i reopen it. 
![Screenshot 2022-11-30 152956](https://user-images.githubusercontent.com/119540580/204912233-40a21db6-ef77-4fe1-ae95-227a4bd26482.png)

 I've ensured it's downloaded on both client and server, tried to even restart my entire world with no luck.

### Relevant logs

The game doesn't crash per say? It just prevents me from getting into my game but I decided to drop the respective logs just in case! https://pastebin.com/iJDsQAd2

### Additional information

any and all "fixes" to the problem that I've seen are just resetting the usercache or deleting config. I posted this here and in the Better MC github to hopefully get some sort of result, thank you!

**Comment by ExcessiveAmountsOfZombies** [comment]
uhh, betterMC doesn't include Croptopia anymore, no idea why. I think this error is caused by only one party having the mod installed, make sure it's on both the client and the server
