### ISSUE TITLE
Request for botany tree support

### ISSUE THREAD

**Issue by Clonephaze** [ExcessiveAmountsOfZombies/Croptopia#475]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

The addon mod for botany pots, botany trees, allows you to grow saplings in the botany pots. Croptopia's seeds work just fine, but none of Croptopia's saplings will go into the pot. Looking at the botany github pages shows that mods can add their own support so I figured I'd ask for the compatibility here, but if it should go on the botany trees github please let me know.

**Comment by ExcessiveAmountsOfZombies** [comment]
2.2.0 has this in place, thank you!
