### ISSUE TITLE
1.19.2版本无法被quilt加载

### ISSUE THREAD

**Issue by txs1234** [ExcessiveAmountsOfZombies/Croptopia#479]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

2.1.2

### What happened?

在quilt启动器(fabric分支)启动时,进入地图会导致游戏崩溃

### Relevant logs

[crash-2022-12-08_22.13.47-client.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/10186798/crash-2022-12-08_22.13.47-client.txt)

**Comment by IgiariValkyr** [comment]
Same issue with Quilt.

**Comment by Sammcb** [comment]
Also seeing this issue.

**Comment by ExcessiveAmountsOfZombies** [comment]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/460
