### ISSUE TITLE
1.16.4 FORGE 1.2.0 prevents bonemeal of vanilla crops

### ISSUE THREAD

**Issue by kreezxil** [ExcessiveAmountsOfZombies/Croptopia#48]
I just did a youtube livestream showing how to find a problem mod and well croptopia forge 1.2.0 was the culprit.

https://youtu.be/15h3FltcHjM

What was happening is the normal crops couldn't be bonemealed. Would be nice if this mod had a config that allowed us to control what happened.

rolled the mod back to 1.1.0 and the problem went away.

**Comment by ExcessiveAmountsOfZombies** [comment]
this should be fixed in 1.2.1, added a config option to disable right click harvesting also. You can find it in croptopia-common.toml
https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric/files/3199566
