### ISSUE TITLE
Empty tags and broken recipes

### ISSUE THREAD

**Issue by kasaiiru** [ExcessiveAmountsOfZombies/Croptopia#482]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19.2

### Croptopia version.

2.1.0

### What happened?

There is a few recipes that dont have a proper tag and show an invalid item. There is also problems with substitution with other mods, sometimes I can only use croptopia ingredients, sometimes its only stuck on another mods like the ad astra cheese picture. Other than that everything works pretty well for me and i enjoy the mod. I dont think the saturation works with my mods, but ill have to look into that. 

![2022-12-16_13 07 03](https://user-images.githubusercontent.com/120753743/208189252-d561812e-1d56-413a-97e7-aade6e6e811b.png)
![2022-12-16_13 07 38](https://user-images.githubusercontent.com/120753743/208189290-4d8cc2e9-e7d0-4967-86e4-8ce9e3a8afc6.png)
![2022-12-16_13 08 02](https://user-images.githubusercontent.com/120753743/208189333-32f0ee42-027a-4ae0-b9a0-b9a2ea874a61.png)
![2022-12-16_13 09 05](https://user-images.githubusercontent.com/120753743/208189369-7d149af9-41d4-433e-99ab-61477fcd85a8.png)

### Additional information.

![Capture](https://user-images.githubusercontent.com/120753743/208190424-13d54aa9-1fdb-4ec4-8f5f-e5934fc4f352.PNG)

**Comment by ExcessiveAmountsOfZombies** [comment]
looks like you're having issue with CroptopiaAdditions. the cheese one will be fixed in my next version though.

**Comment by Yolwoocle** [comment]
Same issue. I cannot craft Croque-monsieur and Croque-Madame, or any food with cheese. The recipe does not yield anything. Using Just Enough Items shows "Empty Tag: forge:cheese". 
I have the Create mod, Croptopia and Croptopia Additions.

![2022-12-20_22 05 04](https://user-images.githubusercontent.com/54135715/208767229-b8aa8950-7ef0-492a-97e3-28e3a264e881.png)
![2022-12-20_22 12 27](https://user-images.githubusercontent.com/54135715/208767690-8533b7d1-b9eb-4569-9cd7-531bdf01914d.png)
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/54135715/208767935-db5c9ce8-792d-4aa7-aadb-ac529f2beabe.png">
