### ISSUE TITLE
[1.19.2] Startup crash with Kotlin for forge - org.jetbrains.annotations

### ISSUE THREAD

**Issue by Peca21** [ExcessiveAmountsOfZombies/Croptopia#487]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19.2

### Croptopia version.

2.2.0

### What happened?

Game crashed on startup

### Relevant logs

https://paste.ee/p/mMjgl

### Additional information

Looks like a compatibility problem between Kotlin for forge and croptopia

**Comment by thedarkcolour** [comment]
@ExcessiveAmountsOfZombies Why do you bundle Jetbrains annotations? Does the mod crash if you don't? I'm trying to decide if I should even have them bundled in Kotlin for Forge

**Comment by ExcessiveAmountsOfZombies** [comment]
i'm not sure why I bundle the annotations, I think I couldn't figure out how to get them present only for compiling and not put them into the jar now that it's causing a crash though I might see again how I can avoid bundling them

**Comment by thedarkcolour** [comment]
It looks like you shade your root project which has the annotations?

**Comment by starixed** [comment]
is there gonna be a build for 1.19.2 FORGE? all i see is 1.19.3

**Comment by ExcessiveAmountsOfZombies** [comment]
tomorrow i'll upload one

**Comment by starixed** [comment]
ok tomorrow it is then. thank you for everything

**Comment by ExcessiveAmountsOfZombies** [comment]
2.2.1 for 1.19.2 is being uploaded
