### ISSUE TITLE
Quilt 0.18.1-beta.27 crash on startup

### ISSUE THREAD

**Issue by MageInBlack** [ExcessiveAmountsOfZombies/Croptopia#488]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

2.2.0

### What happened?

Minecraft crashes on startup. Previous issue was different. Now it just crashes immediately for some reason. Version 0.18.1-beta.26 had the same issue. This happens with all current versions of Croptopia (2.1.2 2.1.0 2.0.8) with, it seems, the same crash message

### Relevant logs

latest.log: https://pastebin.com/4ce33BBs
crash log: https://pastebin.com/NP1RJjn9

### Additional information

I am using as well
ATLauncher as launcher
[1.19.2] QFAPI 4.0.0-beta.26 and QSL 3.0.0-beta.25 (Beta)

**Comment by ExcessiveAmountsOfZombies** [comment]
See if deleting the config file croptopia.conf fixes the issue. If you've changed it you may want to move it elsewhere instead.

**Comment by ahribellah** [comment]
I see yours corrupted at the same place mine did, the cashew tree config, line 104. Specifically, halfway through writing out `minecraft:dark_forest`.

**Comment by ExcessiveAmountsOfZombies** [comment]
#537
