### ISSUE TITLE
Croptopia Forge Not Working With  Terralith

### ISSUE THREAD

**Issue by KowalskiXCIX** [ExcessiveAmountsOfZombies/Croptopia#490]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19.2

### Croptopia version.

2.2.1

### What happened?

Upon further testing and investigation, Croptopia is compatible with Terralith ONLY on the Fabric version, and not on the forge version, the fabric version generated a data file with the crop biome settings and displays all biomes correctly, the Forge version is failing to generate the data file and after hours of testing was unable to locate any crops in Terralith on Forge, but worked just fine on Fabric.

### Additional information.

Mods List:
Croptopia
Terra Blender
Terralith

**Comment by ExcessiveAmountsOfZombies** [comment]
fix is being uploaded, thank you
