### ISSUE TITLE
Missing cinnamon roll

### ISSUE THREAD

**Issue by ZeroMiki** [ExcessiveAmountsOfZombies/Croptopia#492]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

2.2.1

### What happened?

I can't get cinnamon roll after stripping a cinnamon log. I thought it's a bug or the way gets cinnamon roll has changed?

**Comment by Ayutac** [comment]
will be fixed in 2.2.2

**Comment by ExcessiveAmountsOfZombies** [comment]
uploading fix
