### ISSUE TITLE
Croptopia tree's don't spawn unless they're oranges/apples?

### ISSUE THREAD

**Issue by Vlogcksz** [ExcessiveAmountsOfZombies/Croptopia#495]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

None

### Minecraft version.

1.16.5

### Croptopia version.

2.0.5

### What happened?

Basically i was trying to find some trees in a dark forest biome, though i realised there aren't any tree crops anywhere, I looked on creative worlds none spawned. I expected tree crops to grow on trees like in 1.18 but they don't, Am i doing anything wrong?

**Comment by ExcessiveAmountsOfZombies** [comment]
#537
