### ISSUE TITLE
Suggestion: Allow crops to be in multiple biomes

### ISSUE THREAD

**Issue by Seiklus** [ExcessiveAmountsOfZombies/Croptopia#5]
If possible, could you make it so you have the choice to add plants to any amount of different biomes?
Example: Change the configs as such:
```
    "artichoke_seed": {
      "biome-category": "plains",
      "drop-chance": 0.0125
    },
```
to
  ```
  "artichoke_seed": {
      "biome-category": "taiga, extreme_hills, jungle, mesa, plains, savanna, icy, the_end, beach, forest, ocean, desert, river, swamp, mushroom, nether",
      "drop-chance": 0.0125
    },
```
or

 ```
   "artichoke_seed": {
      "biome-category": "any",
      "drop-chance": 0.0125
    },
```

**Comment by ExcessiveAmountsOfZombies** [comment]
eventually I do plan on making it so you can list multiple categories, but for now what i've done is if you set it to "none" it will drop in any biome.

**Comment by ZenithAstralis** [comment]
When you do this rework could you add support for modded biomes as well? Looking at Biomes You'll Go in particular

**Comment by ExcessiveAmountsOfZombies** [comment]
https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/82 going to close this. 1.7.0 will allow you to define multiple categories and in 1.8.0 you'll be able to define biomes instead of categories. This will determine where the wild crops will spawn rather than where seeds will drop
