### ISSUE TITLE
Missing texture for Patchouli recipe book, but the book still functions.

### ISSUE THREAD

**Issue by blue-bluesky** [ExcessiveAmountsOfZombies/Croptopia#503]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.3

### Croptopia version.

2.2.2

### What happened?

The recipe book works but has a pink and black square icon like a missing texture. 
![pink and black square](https://user-images.githubusercontent.com/125172486/218294252-3ce231c2-dc81-47ac-93fd-b74937192928.png)
Everything functions except for the icons for the Croptopia recipe book and "Entry Index". 
If I place it on a lectern it shows up as an open book, but then as a pink and black checkered square in an item frame.

I recently reinstalled all the mods I'm using to resolve some issues and the recipe book finally works but is still pink and black.

### Additional information.

![2023-02-11_23 45 35](https://user-images.githubusercontent.com/125172486/218294109-238a784a-3697-4701-bcb1-bca58f2df542.png)
![2023-02-11_23 44 22](https://user-images.githubusercontent.com/125172486/218294100-cb1c8531-7582-4898-9ee9-57a268f45792.png)

The list of mods I'm using: 
![mc mods list](https://user-images.githubusercontent.com/125172486/218294157-e95476d9-8af8-4e29-9014-5b408eed7bc8.png)

**Comment by DCYT1974** [comment]
I'm also experiencing this

**Comment by koragh** [comment]
has anyone found it , i saw a youtube video from 23 years ago and it showed the texture maybe its a recent bug?

**Comment by ExcessiveAmountsOfZombies** [comment]
#537
