### ISSUE TITLE
Recipe book not working

### ISSUE THREAD

**Issue by captaincobweb63** [ExcessiveAmountsOfZombies/Croptopia#51]
1.16.5

Fabric

when i craft a recipe book, it has no texture and as soon as i open it it crashes the game. the same happens if i get it with /give or creative.

other mods are: byg, youngs better caves, origins, and mo structures

This happens on both single and multiplayer
![2021-02-24_10 14 07](https://user-images.githubusercontent.com/60394270/108985570-1af82800-7689-11eb-9c5c-da9a847b7fe1.png)

thanks. everything else works great mod

**Comment by ExcessiveAmountsOfZombies** [comment]
Install patchouli for fabric 
https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric
In the next version I upload to CF it won't crash the client if it's not installed

**Comment by captaincobweb63** [comment]
Thankyou

**Comment by ExcessiveAmountsOfZombies** [comment]
1.3.0 is live now, should no longer crash.
