### ISSUE TITLE
[1.19.2 Server Fabric] Incompatible with Create mod

### ISSUE THREAD

**Issue by ocram9** [ExcessiveAmountsOfZombies/Croptopia#514]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

2.2.2

### What happened?

The server hangs on startup. When I remove Croptopia it fixes the issue.

### Relevant log.

https://gist.github.com/ocram9/f5a18152bcecd9bc9ace330dee3c3895

**Comment by ocram9** [comment]
Update: I found the problem. Croptopia is incompatible with Create 0.5.0i

**Comment by ExcessiveAmountsOfZombies** [comment]
is it? I think it's armor_statues?
