### ISSUE TITLE
Bug with Botany Pots support

### ISSUE THREAD

**Issue by chimericdream** [ExcessiveAmountsOfZombies/Croptopia#519]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

2.2.2

### What happened?

In my modpack, we have both Botany Pots and Botany Trees. However, the cinnamon sapling from Croptopia only produces the cinnamon crop and sapling, no wood. After a fair bit of digging, I discovered that the [cherry recipe provided by Croptopia for Botany Pots](https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/master/src/main/resources/data/croptopia/recipes/botanypots/cherry.json) is actually cinnamon.

### Relevant log.

n/a

### Additional information.

n/a

**Comment by ExcessiveAmountsOfZombies** [comment]
#537, but fixed in 1.20(.1)
