### ISSUE TITLE
Crafting Seed priority

### ISSUE THREAD

**Issue by WanderBoi** [ExcessiveAmountsOfZombies/Croptopia#521]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.18.2

### Croptopia version.

2.1.0.

### What happened?

Farmer delight produce to seed recipes always default to croptopia, even polymorph fails to load when introducing croptopia produce.
![image](https://user-images.githubusercontent.com/29160030/231546525-533ec8f0-4bc0-436b-861c-39ef7006e662.png)
![image](https://user-images.githubusercontent.com/29160030/231546559-59520fee-2edf-46ea-9a68-9cf0a4526b04.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
i'm not sure why polymorph would fail, but i also don't have time to go back to 1.18.2 to fix this right now. i'll put it in #537
