### ISSUE TITLE
Sprite Redundancy and Quality

### ISSUE THREAD

**Issue by itsdeadfrosty** [ExcessiveAmountsOfZombies/Croptopia#522]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

While the bulk of the mod seems pretty cool, the sprites look terrible. All of the seeds look almost identical. Wandering Bags or Farmers Delight have nice looking sprites, maybe collab or something

**Comment by ExcessiveAmountsOfZombies** [comment]
yup im not an artist so all the seeds look the same lol they'll get replaced eventually
