### ISSUE TITLE
Milk Bottle tag

### ISSUE THREAD

**Issue by persath** [ExcessiveAmountsOfZombies/Croptopia#526]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19.2

### Croptopia version.

2.2.2

### What happened?

In ATM8 your milk bottles are tagged as forge:milks and not forge:milk and recipes from other cooking mods don't recognize it. Same goes for soy milk. Not sure if its a typo or a tag you use on your own mod.

**Comment by ExcessiveAmountsOfZombies** [comment]
#537, fixed in 1.20(.1)
