### ISSUE TITLE
glowing calamari lacking #minecraft:fishes tag

### ISSUE THREAD

**Issue by Anomalocaridid** [ExcessiveAmountsOfZombies/Croptopia#532]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.2

### Croptopia version.

2.2.2

### What happened?

Glowing calamari is not in `#minecraft:fishes`, while normal calamari is. I expected that glowing calamari would have that tag so it can be used in crafting recipes that require fish.

### Relevant log.

N/A

### Additional information.

I was able to work around this problem by simply creating a datapack that adds the `#minecraft:fishes` tag to glowing calamari.

**Comment by ExcessiveAmountsOfZombies** [comment]
#537, fixed in 1.20(.1)

**Comment by Anomalocaridid** [comment]
Thank you!
