### ISSUE TITLE
Can't pick up fruits from trees by right clicking

### ISSUE THREAD

**Issue by ZincSinc** [ExcessiveAmountsOfZombies/Croptopia#534]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

None

### Minecraft version.

1.20

### Croptopia version.

2.2.2

### What happened?

Can't pick up fruits from trees by right clicking but it still works for vegetables that can be grown on the ground

Also if you dont have a bare hand when trying to pick up a fruit, the block disappears from your hand

(I also have the latest Forge version and no other mods in use)

**Comment by ExcessiveAmountsOfZombies** [comment]
thanks should be fixed today in 2.2.3

**Comment by Jackose** [comment]
I'm having the exact same issue for this version but on 1.19.2. A few can be harvested but most do nothing. I hope this can be fixed for 1.19.2 as well. Also RIP kumquat trees. I hope the charcoal from their logs can forever light my house.
