### ISSUE TITLE
lack of texture

### ISSUE THREAD

**Issue by xXRinzlerrXx** [ExcessiveAmountsOfZombies/Croptopia#535]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.4

### Croptopia version.

2.2.2

### What happened?

the texture of this item is missing

### Relevant log.

not needed

### Additional information.

tested without them

![2023-06-15_20 34 19](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/135618265/8a4036a3-0f95-473a-8208-386ef3c43ebc)
![2023-06-15_20 34 22](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/135618265/655853ba-bf47-4f77-9822-a7caa8c1b62a)
![2023-06-15_20 28 01](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/135618265/54a79698-4c7d-41d2-a978-b574d0c016c2)
![2023-06-15_20 34 12](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/135618265/fa83749d-fb6b-4e22-823c-ba716d2b8f74)

**Comment by ExcessiveAmountsOfZombies** [comment]
#537, fixed in 1.20(.1)
