### ISSUE TITLE
Cinnamon logs are fireproof

### ISSUE THREAD

**Issue by limelier** [ExcessiveAmountsOfZombies/Croptopia#536]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.19.4

### Croptopia version.

2.2.2

### What happened?

I can't burn cinnamon logs. I was hoping I could use them to create Supplementaries ash, since they're not useful for much else once I get the cinnamon (no planks), but they seem to be fireproof.

**Comment by ExcessiveAmountsOfZombies** [comment]
#537, fixed in 1.20(.1)
