### ISSUE TITLE
Crash due to nuts with bountiful

### ISSUE THREAD

**Issue by Tecohg** [ExcessiveAmountsOfZombies/Croptopia#538]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.20.1

### Croptopia version.

2.3.0

### What happened?

So i was testing bountiful on my server (bounty block, gives you sorta quests) and upon placing one, server crash, apparently its due to the usage of croptopia items in the reward or requirements pool?

### Relevant logs

[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/11893115/latest.log)
[crash-2023-06-28_12.33.02-server.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/11893116/crash-2023-06-28_12.33.02-server.txt)

### Additional information

Thank you even if you can't fix it!

**Comment by Shadowpudding** [comment]
[crash-2023-06-27_15.21.19-server.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/11906593/crash-2023-06-27_15.21.19-server.txt)
I have the same issue, but in single player (I am aware that the report says server). It only happed when i got in range of a bounty block of a village that i wasn't even in.

**Comment by Shadowpudding** [comment]
i just looked on the bountiful page. It seems to be an issue on bountifuls end. ejektaflex said that he would look into fixing it soon.

Here is the link to the thread on his github:
https://github.com/ejektaflex/Bountiful/issues/234

**Comment by ExcessiveAmountsOfZombies** [comment]
not my bug it seems, ty for reporting it though!
