### ISSUE TITLE
Stackable liquid crafting

### ISSUE THREAD

**Issue by ProjectET** [ExcessiveAmountsOfZombies/Croptopia#54]
Would it be possible to add a stackable water and milk item that substitutes milk buckets and water buckets similar to pam's harvestcraft so that mass crafting things like tofu isn't so tedious?

**Comment by ExcessiveAmountsOfZombies** [comment]
First iteration is in 1.4.0, the next version I release will likely have the rest of the recipes converted to the new liquid crafting.
