### ISSUE TITLE
drinking tea kicks me from my server, ticking player

### ISSUE THREAD

**Issue by milkembers** [ExcessiveAmountsOfZombies/Croptopia#540]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

2.3.0

### What happened?

drinking tea (haven't tried it with other drinks from the mod yet) kicks me from the server with ticking player. possibly related to #38, as i'm using the mod [Tough as Nails](https://github.com/Glitchfiend/ToughAsNails) which adds a thirst meter.
thank you!

### Relevant logs

no crash report applicable. server's latest.log snippet:
https://gist.github.com/milkembers/534f47915390c356821c1e4ac2ca9ed7

**Comment by ExcessiveAmountsOfZombies** [comment]
Should be fixed in 2.3.1
