### ISSUE TITLE
Crops not spawning

### ISSUE THREAD

**Issue by amazonprimeee** [ExcessiveAmountsOfZombies/Croptopia#542]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.20.1

### Croptopia version.

2.3.0

### What happened?

TLDR: Crops aren't spawning in specifically jungles and savannas after we've been playing for a bit. (Set seed used if that means anything)

I have this mod on a server along with some other mods that will be down below and it started off good and we were able to find a lot of seeds and fruit trees especially in forests and plains. But we're looking for the few we are missing in jungles and savannas specifically and none are spawning. I don't know if this has to do with the seasons because I am not sure how the seasons work, but we just wanna find the crops we're missing. We used a set seed if that has anything to do with but I'm not sure. There was another post that said the issue was a right click harvesting mod but I do not have one on the server. Please help, thank you.

### Additional information.

Mods along with Croptopia:
Adorn
Better Villages
Origins (ExtraOrigins, ToomanyOrigins, & Origins Classes as well)
Library Ferret
Moonlight Library
Owo lib
Pehkui
Sniffer+
Supplementaries
Fabric Waystones

**Comment by ExcessiveAmountsOfZombies** [comment]
crop spawn rates will be increased in 3.0, but you can also join my discord and in the #croptopia channel there is a pinned datapack that raises them too (not that it'd help for already generated chunks)

**Comment by Sobecott** [comment]
Could you give the link to the datapack that forces the crops to spawn as i have the same issue but i do not know how to access your discord. :(

**Comment by ExcessiveAmountsOfZombies** [comment]
[Easy_Higher_Crop_Spawn_Rates_-_Croptopia_Datapack.zip](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/12686145/Easy_Higher_Crop_Spawn_Rates_-_Croptopia_Datapack.zip)

**Comment by Sobecott** [comment]
Thanks! >:DDD
