### ISSUE TITLE
Croptopia Book no recipe in JEI

### ISSUE THREAD

**Issue by michaelortnerit** [ExcessiveAmountsOfZombies/Croptopia#547]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

2.3.2

### What happened?

The book has no recipe, try it with JEI. no recipe is coming

**Comment by ExcessiveAmountsOfZombies** [comment]
maybee patchouli wasn't installed? if this is broken it'll be fixed in v3

**Comment by michaelortnerit** [comment]
Hello,

is fixed but thanks for your help!
