### ISSUE TITLE
Patchouli Book Doesn't Work

### ISSUE THREAD

**Issue by LordOfTheWeebs** [ExcessiveAmountsOfZombies/Croptopia#549]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.20.1

### Croptopia version.

2.3.0

### What happened?

The guidebook enabled via Patchouli doesn't function. It can be crafted and given via commands and the creative mode menu, and right-clicking to open the book produces the animation when opening a book, but the guide menu doesn't load.

### Additional information.

Patchouli version is v1.20.1-81 (the latest from June 10th up to the time of making this bug report).

**Comment by ExcessiveAmountsOfZombies** [comment]
need to use 2.3.2 i fixed it there 😄

**Comment by KruzardWiz** [comment]
> need to use 2.3.2 i fixed it there 😄

My world has started in version 3.0.4, a lot of content is lost if I switch to version 2.3.2?
