### ISSUE TITLE
Add the mod on Modrinth

### ISSUE THREAD

**Issue by AmibeSkyfy16** [ExcessiveAmountsOfZombies/Croptopia#551]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

I think it would be great to see this mod on https://modrinth.com

Last year you considered modrinth not mature enough, is that still the case now?
I think with what's happening with curseforge, that should soon change.

Thank you for this cool project !

**Comment by KatoNamus** [comment]
Yes, please do

**Comment by ExcessiveAmountsOfZombies** [comment]
#407
