### ISSUE TITLE
Randomised items on server

### ISSUE THREAD

**Issue by JackLiberson** [ExcessiveAmountsOfZombies/Croptopia#553]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.20.1

### Croptopia version.

2.3.2

### What happened?

im playing on modded server and every item (_i guess_) has been randomised 
its only triggers me for some reason because for everyone else its fine
![2023-08-13_01 32 42](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/133762120/cc6d21f8-f8b9-4264-aec8-b36845d5dee6)
![2023-08-13_01 34 40](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/133762120/2b6ffaf3-244c-49ed-ba1a-a0870c778781)
![2023-08-13_01 34 54](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/133762120/ee3ee20c-69c7-4301-ab2a-5c0ddce8afa7)
![2023-08-13_01 35 07](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/133762120/82a7a91f-169c-4f86-a694-171140df2318)
but on singleplayer world everything is okay
so i dont know is it my problem or server

note: i redownloaded it and rebooted my pc and problem still the same

### Additional information.

im playing on Quilt 1.20.1
here the mods im using:
![image](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/133762120/a0d476a5-5ed4-4a71-b016-10c209f144e1)
i have really old pc

**Comment by ExcessiveAmountsOfZombies** [comment]
there is a mismatch of mods between the server and the client, everything internally is represented with number identifiers, so if the server/client has a longer/shorter list of numbers it can map what exists on the server to something different on the client.

you'll have to figure out the mismatch but this isn't a bug with croptopia
