### ISSUE TITLE
Opening title crashes

### ISSUE THREAD

**Issue by 73-o** [ExcessiveAmountsOfZombies/Croptopia#556]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

2.3.2, 2.3.1

### What happened?

I've been putting a modpack together and it worked for the past 2 days but now I've run into some issues. Im not a code or file reader, all I know to do is where to put the files. Anyway, just yesterday after logging off at one point I wasn't able to get back on. I don't fully remember if I've changed something, but any help would be appreciated. 

### Relevant logs

[crash-2023-08-20_10.39.14-client.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/12388678/crash-2023-08-20_10.39.14-client.txt)

[latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/12388680/latest.log)

### Additional information

![image](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/127689588/e7e9801c-56dc-44bb-ad62-f2a061f5c1b8)

**Comment by ExcessiveAmountsOfZombies** [comment]
`Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid character '
' after key [persimmon_tree_configured]`


does deleting the config fix the issue? or deleting the invalid character

**Comment by 73-o** [comment]
> `Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid character ' ' after key [persimmon_tree_configured]`
> 
> does deleting the config fix the issue? or deleting the invalid character

Sorry I don't know what those are, where would I delete this?

**Comment by ExcessiveAmountsOfZombies** [comment]
idk, search for persimmon_tree_configured and compare it to other x_tree_configureds and see if there is any difference, or just delete the config and let it regenerate

it's in the croptopia config file `Failed loading config file croptopia-common.toml of type COMMON for modid croptopia`

**Comment by 73-o** [comment]
I figured it out a different way but still the explanation doesn't make sense to me. 
I deleted every Croptopia in my PC and just redownloaded it, which ended up working. 
Thanks anyway though!
