### ISSUE TITLE
Recipe book

### ISSUE THREAD

**Issue by Miyu42** [ExcessiveAmountsOfZombies/Croptopia#557]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

1.20.1

### What happened?

when I enter everything works fine but when I wanted to open the recipe book to discover more food items it wouldn't let me open the book try on server in individual world installing and uninstalling the mod and the dependency (patchuoli) and it won't let me access the recipe book recipes

### Additional information.

https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/142747598/9644bead-a257-475b-bc86-d37bb5719415

In this video it is indicated that I try to open the book and it is not possible for me

**Comment by ExcessiveAmountsOfZombies** [comment]
use version 2.3.2 and make sure patchouli is installed
