### ISSUE TITLE
Empty tag for cheese in some recipes

### ISSUE THREAD

**Issue by Julianna91** [ExcessiveAmountsOfZombies/Croptopia#561]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

None

### Minecraft version.

1.18.2

### Croptopia version.

2.1.0

### What happened?

There is an empty tag: forge:cheese for the croque madame and croque monsieur recipes.

![Screenshot 2023-08-26 154854](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/120489274/2372e668-08d4-465f-a686-44e93f3f6380)

Also, there is no information on how to obtain the frog legs.

**Comment by ExcessiveAmountsOfZombies** [comment]
might revisit if i do anything with 1.18,2
