### ISSUE TITLE
[1.20.1] Olives are still a plant and not a tree

### ISSUE THREAD

**Issue by JaisDK** [ExcessiveAmountsOfZombies/Croptopia#563]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

2.3.2

### What happened?

https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/304

**Comment by ExcessiveAmountsOfZombies** [comment]
can't change it, goes against my design philosophy for how I mod.
