### ISSUE TITLE
Patchouli book saying error and not showing the recipies.

### ISSUE THREAD

**Issue by alefblue** [ExcessiveAmountsOfZombies/Croptopia#565]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

PC

### Minecraft version.

1.20.1

### Croptopia version.

1.20.1

### What happened?

Everything works apart from the patchouli book. When I open it, instead of showing me the recipies it comes up with a character in path error. I have tried everything from reinstalling it to reinstalling the minecraft launcher.

The crash log doesn't identify it as a crash for some reason.

This issue is happening on 1.20.1 fabric.

Please help.

**Comment by ExcessiveAmountsOfZombies** [comment]
can't replicate this in 3.0.4, maybe i fixed it!
