### ISSUE TITLE
[Fabric 1.20.1] Mod-Item Recipe Remainders crash the game

### ISSUE THREAD

**Issue by Quasi-Detective** [ExcessiveAmountsOfZombies/Croptopia#569]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.19.4 & 1.20.1

### Croptopia version.

2.2.2 & 2.3.2

### What happened?

Crafting recipes that use the cooking pot, frying pan, or knife crash the game upon trying to "return" them once the recipe is made. I assume this is a compatibility issue or item ID conflict, having to do with another mod? Please help, I'd like to be able to make these recipes.

This issue occurs on both 1.19.4 and 1.20.1, with the same error message.

### Relevant logs

[crash-2023-10-07_20.55.06-client.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/12842078/crash-2023-10-07_20.55.06-client.txt) (1.19.4 crash log)
[crash-2023-10-18_17.11.58-client.txt](https://pastebin.com/JW4sJ0iP) (1.20.1 crash log)

### Additional information

I have a lot of mods installed. The list is in the crash report file.

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed in 3.0.2+ but 1.19.4 probably won't get it
