### ISSUE TITLE
cherries go on cherry trees

### ISSUE THREAD

**Issue by greatestdelilah** [ExcessiveAmountsOfZombies/Croptopia#570]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

now that minecraft actually has cherry trees in the game, the cherry sapling should grow a cherry tree instead of an oak tree.

**Comment by ExcessiveAmountsOfZombies** [comment]
i'm going to be keeping them separate from vanilla
