### ISSUE TITLE
Crashes on start 1.20.4

### ISSUE THREAD

**Issue by makumaku1974** [ExcessiveAmountsOfZombies/Croptopia#579]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

None

### Minecraft version.

1.20.4

### Croptopia version.

3.0.1

### What happened?

Game crashed at start.

### Relevant logs

[2023-12-14-4.log.gz](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/13668404/2023-12-14-4.log.gz)

**Comment by Rikys** [comment]
The log you sent doesn't contain any errors related to croptopia, however it does show that your game is unable to connect to yggdrasil, minecraft authentication service, and it looks like that's causing your game to crash.

**Comment by makumaku1974** [comment]
is there a way to fix that problem?

**Comment by Skullians** [comment]
make sure your ports are open so the server can connect to yggradsil

**Comment by ExcessiveAmountsOfZombies** [comment]
yea this doesn't... seem to be related to croptopia?

**Comment by makumaku1974** [comment]
do i need epherolib now???

**Comment by ExcessiveAmountsOfZombies** [comment]
yes that is also something you need
