### ISSUE TITLE
Book not working

### ISSUE THREAD

**Issue by TacWithGames** [ExcessiveAmountsOfZombies/Croptopia#58]
I craft the book and it just doesnt open. I the mod installed plus the other mod for the book yet it just doesnt open. Its a multiplayer server and we have origins installedd as well

**Comment by Shoes4Clues** [comment]
Make sure you have the PatchOuli mod installed, otherwise it will not work.

**Comment by ExcessiveAmountsOfZombies** [comment]
Patchouli needs to be installed on both the client and the server for it to work.
