### ISSUE TITLE
Utensils disappear after crafting

### ISSUE THREAD

**Issue by Deadramas** [ExcessiveAmountsOfZombies/Croptopia#580]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

None

### Minecraft version.

1.20.2

### Croptopia version.

Croptopia-1.20.2-FORGE-3.0.1.jar

### What happened?

Crafting Recipies with Utensils working but without getting them back. Thats not supposed to happen and i just seen that this "bug" was reported in an older version. So i am not sure why it happening. I could not try out a other version for 1.20.2, because there was only this one. I tried it on a server and in singleplayer.

Other Mods installed:
Appleskin
Balm
epherolib
gravestone
jade
JEI
NatureCompass
TravelersBackpack
Waystone
Xaeros_Minimap

**Comment by Fidulus** [comment]
got the same issue

**Comment by ExcessiveAmountsOfZombies** [comment]
uploading 3.0.4 to fix
