### ISSUE TITLE
Croptopia

### ISSUE THREAD

**Issue by lunalunalunaluna1** [ExcessiveAmountsOfZombies/Croptopia#582]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

3.0.2

### What happened?

At first the mod wouldnt even load. then I found out i needed epherolib. then it loaded in, but now i move maybe 15 20 blocks and the game crashes every single time.

### Relevant logs

[crash-2023-12-18_17.26.15-server.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/13709145/crash-2023-12-18_17.26.15-server.txt)

**Comment by Poopooracoocoo** [comment]
Looks like you've got the wrong version of Terralith

**Comment by ExcessiveAmountsOfZombies** [comment]
i'll close this one in favor of #577
