### ISSUE TITLE
Patchouil book don't open and show message that patchouli isn't available for 1.20.2

### ISSUE THREAD

**Issue by Mattsingen** [ExcessiveAmountsOfZombies/Croptopia#585]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

3.0.2

### What happened?

When opening the guide book the message "The code is disabled, whenever this build was published patchouli 1.20.2 did not exist." is displayed. 
I'm guessing that the changes to solve the problem with patchouli not being available for version after 1.20.1 yet, was also pushed to 1.20.1.
I guess that it's this change that did this: https://github.com/ExcessiveAmountsOfZombies/Croptopia/commit/e467534db322436e3dcf48373fc0e8fe907aae24

I understand if you don't like to maintain a seperate branch just for 1.20.1 if it's not needed, so just close this issue if that is the case.

**Comment by ExcessiveAmountsOfZombies** [comment]
yup i messed up, uploading 3.0.4 to fix it right now

**Comment by MrHimera** [comment]
It's running 3.0.4 and the book still won't open

**Comment by ExcessiveAmountsOfZombies** [comment]
> It's running 3.0.4 and the book still won't open

share logs?

**Comment by MrHimera** [comment]
> > It's running 3.0.4 and the book still won't open
> 
> share logs?

It doesn't show an error in the log. Just write in chat "The code is disabled, whenever this build was published patchouli 1.20.2 did not exist."

**Comment by ExcessiveAmountsOfZombies** [comment]
> 
> It doesn't show an error in the log. Just write in chat "The code is disabled, whenever this build was published patchouli 1.20.2 did not exist."

well I don't know what MC version you're running, croptopia version, or patchouli version.

**Comment by MrHimera** [comment]
> > It doesn't show an error in the log. Just write in chat "The code is disabled, whenever this build was published patchouli 1.20.2 did not exist."
> 
> well I don't know what MC version you're running, croptopia version, or patchouli version.

MC 1.20.1
Forge 1.20.1 47.2.1
Croptopia 3.0.4
Patchouli 1.20.1-84-FORGE

**Comment by LykwidFire** [comment]
Reaching out on this. New server stood up and getting this error:
MC Version: 1.20.1
Forge Version: 47.2.19
Croptopia Version: 3.0.4
Patchouti Version: Patchouli-1.20.1-84-FORGE

Server logs can be DM'ed to you if you wish
![2024-01-12_22 13 04](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/156100502/e9778eb6-f734-4902-8a0f-79aa798324ac)
