### ISSUE TITLE
All utensils (for example: all purpose food press) gets consumed with the recipe

### ISSUE THREAD

**Issue by Fidulus** [ExcessiveAmountsOfZombies/Croptopia#586]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.2

### Croptopia version.

3.0.1

### What happened?

i am not really sure if its a bug or intended, but it seems to me that the "all purpose food press" should not be consumed when i use it in any recipe like "olive oil".
Because i couldn't find anything related to this issue i just wanted you to know.
Also please tell me if it´s only some special bug on my end because i´m using lots of other mods on the same server.
Thank you very much for this great mod. loving it.

**Comment by Deadramas** [comment]
i have the same problem. https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues/580 

For every utensil.

**Comment by ExcessiveAmountsOfZombies** [comment]
uploading 3.0.4 to fix
