### ISSUE TITLE
Patchouil book don't open and show message that patchouli isn't available for 1.20.2 Still outstanding issue

### ISSUE THREAD

**Issue by LykwidFire** [ExcessiveAmountsOfZombies/Croptopia#588]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

None

### Minecraft version.

1.20.1

### Croptopia version.

3.0.4

### What happened?

Following up on Issue 585 which is closed. 
After updating  to 3.0.4 as the thread suggests, issue is still occurring when trying to open the Croptopia Recipes Book (see attached Screenshot) Server info is as follows:
MC Version: 1.20.1
Forge Version: 47.2.19
Croptopia Version: 3.0.4
Patchouti Version: Patchouli-1.20.1-84-FORGE

![2024-01-12_22 13 04](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/156100502/70e76a7b-41fb-4ff5-9860-124454ec0c17)
[01_12_24latest.log](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/13929099/01_12_24latest.log)

### Relevant log.

See attached Server Log

### Additional information.

In total 110 mods are running. Can provide a Curseforge profile if required.

**Comment by AsheX1** [comment]
have this same problem on neoforge 1.20.1 
Croptopia Version: 3.0.4
Patchouti Version: Patchouli-1.20.1-84-FORGE

**Comment by Diedntgo** [comment]
Having the same issue as well

MC Version: 1.20.1
Forge Version: 47.2.20
Croptopia Version: 3.0.4
Patchouli Version: 1.20.1-84-FORGE

**Comment by MrHimera** [comment]
same problem

**Comment by Angellight36** [comment]
Same issue in ATM no frills version 0.1.9 which uses:

MC 1.20.1
Forge 47.2.20
Croptopia-1.20.1-FORGE-3.0.4
Patchouli-1.20.2-84-FORGE

**Comment by BMedinaASC** [comment]
Same here.
MC 1.20.1
Forge 47.2.30
Croptopia 3.0.4
Patchouli 1.20.1-84

**Comment by cabyll-ushtey** [comment]
Had the same issue, the solution for me was to use an older version of Croptopia. 

What worked:
MC 1.20.1
Forge 47.2.0
Croptopia 2.3.2 (beta)
Patchouli 1.20.1-84

[Credit goes to Conkuerr on this reddit thread.](https://www.reddit.com/r/ModdedMinecraft/comments/193bvlu/croptopiafarmers_delightpatchouli_help/)
