### ISSUE TITLE
A list somewhere with information on where to find (what biome) all the trees and seeds

### ISSUE THREAD

**Issue by EnviGames** [ExcessiveAmountsOfZombies/Croptopia#59]
**Version**
1.2.1

**Platform**
Forge

**Describe the issue**
I was wondering if it would be possible to have a link somewhere to a full list of where to find all the trees and crops, i have guessed a few and found a few comments online but it would be nice to see a page that lists the crops and what biomes to find them. 

**Additional context**
Great mod thanks!

**Comment by ExcessiveAmountsOfZombies** [comment]
I made a wiki page with all the current locations of crops and trees.
https://github.com/ExcessiveAmountsOfZombies/Croptopia/wiki
