### ISSUE TITLE
Server Crashing on startup with mod

### ISSUE THREAD

**Issue by titustitus98** [ExcessiveAmountsOfZombies/Croptopia#591]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

3.0.4

### What happened?

I'm trying to start my server up with the mod on but it crashes every time

### Relevant logs

https://hastebin.com/share/tuyehomepi.php

**Comment by ExcessiveAmountsOfZombies** [comment]
add epherolib 
Caused by 0: java.lang.NoClassDefFoundError: com/epherical/epherolib/libs/org/spongepowered/configurate/loader/AbstractConfigurationLoader$Builder
