### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Gamemassa** [ExcessiveAmountsOfZombies/Croptopia#598]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.20.4

### Croptopia version.

3.0.1

### What happened?

Crash on startup. Possible mod conflict, though I'm not sure what caused it.

### Relevant logs

https://gist.github.com/Gamemassa/cecf183f3cd4e11fa93523b8f637eac6

**Comment by Aquariax1** [comment]
Epherolib is a **required** library, more info here : https://www.curseforge.com/minecraft/mc-mods/croptopia/relations/dependencies

**Comment by Gamemassa** [comment]
Yup, that missing library appears to have been the issue. Thanks for the headsup.
