### ISSUE TITLE
TODO: Villagers can trade crops

### ISSUE THREAD

**Issue by ExcessiveAmountsOfZombies** [ExcessiveAmountsOfZombies/Croptopia#6]

**Comment by cryxli** [comment]
Depending on WorldGen finding a Jungle may be... challenging. This holds true for other bioms, too. Therefore, having another source of seeds would be greatly appreciated.

One idea: Have a "gardener villager" specifically dedicated to Croptopia seeds.

**Comment by ExcessiveAmountsOfZombies** [comment]
as a first iteration this is going to be the regular farmers but in the future they might get their own villager type. So for now this is complete and will be in the next build I release
