### ISSUE TITLE
Using croptopia:guide crashes the game. Also it doesn't have a texture.

### ISSUE THREAD

**Issue by RDKRACZ** [ExcessiveAmountsOfZombies/Croptopia#60]
**Version**
Fabric - 1.2.0
https://gist.githubusercontent.com/natanfudge/9005f3fb6911701e2c2149bcf621236b/raw/21af9fd2507e78690e0a7b3423e04d05d4acb8b9/crash.txt

**Comment by RDKRACZ** [comment]
Checked on v.1.3.0 - it's not crashing anymore but still lacks the texture.

**Comment by ExcessiveAmountsOfZombies** [comment]
i'm going to leave this one as is, i want it to be obvious for people that the guide won't work if they don't have patchouli installed.
