### ISSUE TITLE
[1.20.4] Minecraft crashes when trying to open Croptopicon

### ISSUE THREAD

**Issue by darwon23** [ExcessiveAmountsOfZombies/Croptopia#603]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.20.4

### Croptopia version.

3.0.1

### What happened?

when trying to use the book, the game crashes

### Relevant logs

[crash-2024-03-14_09.34.06-client.txt](https://github.com/ExcessiveAmountsOfZombies/Croptopia/files/14598637/crash-2024-03-14_09.34.06-client.txt)

**Comment by ChudoMorkov** [comment]
Hi!, i have the same issue, The problem is because of "Patchouli" mod.
