### ISSUE TITLE
Upload to Modrinth?

### ISSUE THREAD

**Issue by nellePoint** [ExcessiveAmountsOfZombies/Croptopia#604]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Hi, I was wondering if you would consider uploading this mod to modrinth?

It would greatly improve visibility and ease of access of the mod.

:heart:

**Comment by B1BU** [comment]
I would also like that
