### ISSUE TITLE
Coffee Crafting Recipe

### ISSUE THREAD

**Issue by xXxBlowMeAwayxXx** [ExcessiveAmountsOfZombies/Croptopia#611]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.16.5

### Croptopia version.

2.0.5 (latest)

### What happened?

There is no crafting recipe for Coffee, making Coffee Beans useless. I've looked in the book as well and clicked on it, and it comes up blank. JEI also reports nothing as far as a recipe goes. Just in case, I've restarted my game, tried with only this mod present in a test world, still nothing.

**Comment by Nahyack** [comment]
Hello were you able to fix it? I’m having the same issue on my server for some recipes

**Comment by xXxBlowMeAwayxXx** [comment]
> Hello were you able to fix it? I’m having the same issue on my server for some recipes

Nope, sadly not. The mod simply doesn't have the crafting recipe.

**Comment by thomwoosley** [comment]
I had the same problem, but was able to fix it.  I had the mod "Croptopia Delight" installed, and it was causing the problem.  Croptopia Delight assumes you have Farmer's Respite installed.  I could either remove Croptopia Delight (which is what I did) or I could have installed Farmer's Respite.  Removing it fixed the issue.
