### ISSUE TITLE
Support for Fabric 1.20.6

### ISSUE THREAD

**Issue by kingstairs** [ExcessiveAmountsOfZombies/Croptopia#614]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Are there plans and/or a timeline to add support for Fabric 1.20.6? Thank you.

**Comment by ExcessiveAmountsOfZombies** [comment]
yep, 1.20.6 will be next
