### ISSUE TITLE
Fruit trees but no crops

### ISSUE THREAD

**Issue by Auvshi** [ExcessiveAmountsOfZombies/Croptopia#616]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.20.4

### Croptopia version.

3.0.1

### What happened?

I created a server for some of my friends and added Croptopia. My friends and I are able to find a lot of fruit trees but there doesn't seem to be any crops at all spawning. I've checked multiple biomes and created new chunks but it's still not spawning. I read some other similar issues that were closed to see if I could find a fix without making my own issue report but they're older versions where you get crops and seeds through tall grass and stuff. (I also tried this just in case hoe and no hoe but didn't work). I've also added that datapack where it would increase the spawn rate of the crops but that didn't seem to work either. Can't think of anything else besides maybe one of my mods having a compatibility issue.

### Additional information.

![image_2024-06-07_012514834](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/172011953/b44c45d5-5950-4212-b2f5-7ae1be66dc9b)

Server Side mods

![Screenshot 2024-06-07 012903](https://github.com/ExcessiveAmountsOfZombies/Croptopia/assets/172011953/1a42e70b-2c27-411f-9098-2f4d67d242fd)

Client Side mods

**Comment by Zintrox** [comment]
Hii, let me tell you that i noticed the same today too, also on fabric 1.20.4, we share some mods, but when i was taking away some to figure out which one was giving the problem, after putting all again i saw the crops, idk if it was a problem to begin, but im kind of sure that the crops just appear less often, i sugess you explore a little more and try to find them

**Comment by destructor2040** [comment]
the issue is with terralith and has already been made #590

**Comment by freanux** [comment]
I have exactly the same problem. I'm trying to get Croptopia to work with "Oh The Biomes We've Gone".
Trees are only created in vanilla biomes. Adjustments in the "croptopia-v3.conf" file are ignored.

mc: 1.21.1 fabric
croptopia: Croptopia-1.21-FABRIC-3.0.9
bwg: Oh-The-Biomes-Weve-Gone-Fabric-2.1.5
fabric: fabric-api-0.106.0+1.21.1
