### ISSUE TITLE
Salt~~~~~~~~~~~~~~~!!!!!!!!!!

### ISSUE THREAD

**Issue by Udawdaw** [ExcessiveAmountsOfZombies/Croptopia#617]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

fabric

### Minecraft version.

1.20.6

### Croptopia version.

3.0.4

### What happened?

When mining salt ore, only raw ore will be dropped but not salt.

**Comment by kechsin** [comment]
Oh same!! Also fabric, but minecraft version 1.21 and croptopia version 3.0.5

**Comment by C-LeDu** [comment]
Same here: 
- Platform : fabric
- Minecraft version: 1.21
- Croptopia version: 3.0.5

**Comment by Nevodev** [comment]
this bug still exists

**Comment by Twaras** [comment]
I think there's a problem with the salt_ore.json file in the src/main/resources/data/croptopia/loot_table folder. It seems like there were changes in the format for checking the silk touch enchantment case in each version from 1.20.4 to 1.21.

Or at least that's what I found when comparing it with the loot table generator page

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed neoforge 4.0.0
