### ISSUE TITLE
Nothing dropping

### ISSUE THREAD

**Issue by KittyJevs** [ExcessiveAmountsOfZombies/Croptopia#618]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

None

### Minecraft version.

1.21

### Croptopia version.

Croptopia-1.21-Fabric-3.0.4.jar

### What happened?

When breaking or harvesting crops from this mod nothing will drop, only seeds and crops can be acquired from chests

**Comment by TbaDay** [comment]
I'm having the same issue.
I'm using fabric*

**Comment by krispyzaza** [comment]
Im having the same issue on my server.

**Comment by N0rdicDwarf** [comment]
i'm also having the same issue

**Comment by Z0NKO** [comment]
Same here, nothing dropped from the crops and trees :(
Ver. 1.21 Fabric

**Comment by Yazxi** [comment]
I'm also having the same issue, hope it gets fixed soon

**Comment by diconix4k** [comment]
Same error here: Destroying the block under the crop doesn't help either.

**Comment by Matheuws58** [comment]
Looks like everyone is having the same problem

**Comment by KittyJevs** [comment]
Creator said today he will be dropping a fix real soon, so hopefully all will be resolved

**Comment by ExcessiveAmountsOfZombies** [comment]
3.0.5 is being uploaded on cf right now

**Comment by TbaDay** [comment]
Thank you!

**Comment by AnyaDarling03** [comment]
I used the update and they still won't drop.

**Comment by diconix4k** [comment]
@AnyaDarling03, it works, make sure you are using version 3.0.5

**Comment by AnyaDarling03** [comment]
I made sure I'm using version 3.0.5. I even made a new world just to make sure. Updated curse forge as well before all of this. The crops still won't drop.

**Comment by diconix4k** [comment]
Hmm, are you playing in survival mode? You could also check if your Fabric and the library that Croptopia uses are up to date.

Edit: You could also test whether it helps if you delete the config file from Croptopia
