### ISSUE TITLE
1.21 Bug [ ACHIEVEMENTS ]

### ISSUE THREAD

**Issue by makumaku1974** [ExcessiveAmountsOfZombies/Croptopia#619]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.21

### Croptopia version.

3.0.5

### What happened?

Random achievement received when receiving any item

**Comment by SabsRat** [comment]
is also happening with me

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed this now too ty
