### ISSUE TITLE
Cinnamon Trees not giving Cinnamon

### ISSUE THREAD

**Issue by CuddleBear1812** [ExcessiveAmountsOfZombies/Croptopia#620]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.4

### Croptopia version.

Forge 3.0.4

### What happened?

I've been using this mod for awhile now and have updated it every time a new update has been released however I have never been able to harvest the cinnamon tree. I have looked at the closed tickets where it shows that a fix had been made but it still hasn't worked for me. Any assistance would be great. Thank you for your time

**Comment by queso-gato1355** [comment]
Do you have any other mods you've installed? I'll be appreciated if you list it out.

**Comment by CuddleBear1812** [comment]
Here is a list of mods currently loaded on my account.

Best Regards,
Daniel

**Comment by queso-gato1355** [comment]
I'm sorry, but I could not find any mod list that you might give to me. Please send it again, so that I can resolve your problem.

**Comment by queso-gato1355** [comment]
I found out that if you try to harvest cinnamon in creative mod, this problem is occurred. So for now, playing in survival mod is recommended.

**Comment by CuddleBear1812** [comment]
- Blackwolf Library (by 00theblackwolf00)
   <https://www.curseforge.com/minecraft/mc-mods/blackwolf-library>
   - Packed Up (Backpacks) (by SuperMartijn642)
   <https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks>
   - More Beautiful Walls [FORGE & FABRIC] (by 00theblackwolf00)
   <https://www.curseforge.com/minecraft/mc-mods/more-beautiful-walls>
   - Balm (Forge Edition) (by BlayTheNinth)
   <https://www.curseforge.com/minecraft/mc-mods/balm>
   - Runelic (by DarkhaxDev)
   <https://www.curseforge.com/minecraft/mc-mods/runelic>
   - YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons>
   - Rubble Ray (by Nicusha)
   <https://www.curseforge.com/minecraft/mc-mods/rubble-ray>
   - Macaw's Bridges (by sketch_macaw)
   <https://www.curseforge.com/minecraft/mc-mods/macaws-bridges>
   - Trash Cans (by SuperMartijn642)
   <https://www.curseforge.com/minecraft/mc-mods/trash-cans>
   - YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments>
   - Vein Mining (Fabric/Forge/Quilt) (by TheIllusiveC4)
   <https://www.curseforge.com/minecraft/mc-mods/vein-mining>
   - YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts>
   - TerraBlender (Forge) (by TheAdubbz)
   <https://www.curseforge.com/minecraft/mc-mods/terrablender>
   - EpheroLib (by thethonk)
   <https://www.curseforge.com/minecraft/mc-mods/epherolib>
   - Formations (Structure Library) (by SuperMartijn642)
   <https://www.curseforge.com/minecraft/mc-mods/formations>
   - YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island>
   - YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses>
   - libIPN (by mirinimi)
   <https://www.curseforge.com/minecraft/mc-mods/libipn>
   - YUNG's Extras (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-extras>
   - Unified Storage (by Astero)
   <https://www.curseforge.com/minecraft/mc-mods/unified-storage>
   - Botany Trees (by DarkhaxDev)
   <https://www.curseforge.com/minecraft/mc-mods/botany-trees>
   - Clumps (by Jaredlll08)
   <https://www.curseforge.com/minecraft/mc-mods/clumps>
   - Tree Harvester (by Serilum)
   <https://www.curseforge.com/minecraft/mc-mods/tree-harvester>
   - Botany Pots (by DarkhaxDev)
   <https://www.curseforge.com/minecraft/mc-mods/botany-pots>
   - Additional Lanterns (by SuperMartijn642)
   <https://www.curseforge.com/minecraft/mc-mods/additional-lanterns>
   - Macaw's Fences and Walls (by sketch_macaw)
   <https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls>
   - Nature's Compass (by Chaosyr)
   <https://www.curseforge.com/minecraft/mc-mods/natures-compass>
   - Macaw's Paths and Pavings (by sketch_macaw)
   <https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings>
   - YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge>
   - Just Enough Items (JEI) (by mezz)
   <https://www.curseforge.com/minecraft/mc-mods/jei>
   - Formations Nether (by SuperMartijn642)
   <https://www.curseforge.com/minecraft/mc-mods/formations-nether>
   - Goblin Traders (by MrCrayfish)
   <https://www.curseforge.com/minecraft/mc-mods/goblin-traders>
   - JustHammers (by ErrorMikey)
   <https://www.curseforge.com/minecraft/mc-mods/justhammers>
   - YUNG's Menu Tweaks (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-menu-tweaks>
   - More Buttons [FORGE & FABRIC] (by 00theblackwolf00)
   <https://www.curseforge.com/minecraft/mc-mods/more-buttons>
   - SuperMartijn642's Config Lib (by SuperMartijn642)
   <https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib>
   - More Beautiful Slabs [FORGE & FABRIC] (by 00theblackwolf00)
   <https://www.curseforge.com/minecraft/mc-mods/more-beautiful-slabs>
   - Item Collectors (by SuperMartijn642)
   <https://www.curseforge.com/minecraft/mc-mods/item-collectors>
   - Better Treasure Map (by Raycoms)
   <https://www.curseforge.com/minecraft/mc-mods/treasuredistance>
   - YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples>
   - More Carpets [FORGE & FABRIC] (by 00theblackwolf00)
   <https://www.curseforge.com/minecraft/mc-mods/more-carpets>
   - More Beautiful Doors [FORGE & FABRIC] (by 00theblackwolf00)
   <https://www.curseforge.com/minecraft/mc-mods/more-beautiful-doors>
   - Additional Structures (by XxRexRaptorxX)
   <https://www.curseforge.com/minecraft/mc-mods/additional-structures>
   - Macaw's Lights and Lamps (by sketch_macaw)
   <https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps>
   - Explorer's Compass (by Chaosyr)
   <https://www.curseforge.com/minecraft/mc-mods/explorers-compass>
   - Macaw's Windows (by sketch_macaw)
   <https://www.curseforge.com/minecraft/mc-mods/macaws-windows>
   - Collective (by Serilum)
   <https://www.curseforge.com/minecraft/mc-mods/collective>
   - Macaw's Furniture (by sketch_macaw)
   <https://www.curseforge.com/minecraft/mc-mods/macaws-furniture>
   - Inventory Profiles Next (by mirinimi)
   <https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next>
   - More Beautiful Stairs [FORGE & FABRIC] (by 00theblackwolf00)
   <https://www.curseforge.com/minecraft/mc-mods/more-several-stairs>
   - Croptopia (by thethonk)
   <https://www.curseforge.com/minecraft/mc-mods/croptopia>
   - YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples>
   - YUNG's Bridges (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-bridges>
   - Pig Pen Cipher (by DarkhaxDev)
   <https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher>
   - JourneyMap (by techbrew)
   <https://www.curseforge.com/minecraft/mc-mods/journeymap>
   - Cooking for Blockheads (by BlayTheNinth)
   <https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads>
   - More Beautiful Trapdoors [FORGE & FABRIC] (by 00theblackwolf00)
   <https://www.curseforge.com/minecraft/mc-mods/more-beautiful-trapdoors>
   - CompactStorage (by witchica)
   <https://www.curseforge.com/minecraft/mc-mods/compactstorage>
   - Farming for Blockheads (by BlayTheNinth)
   <https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads>
   - Advancement Plaques [Forge] (by Grend_G)
   <https://www.curseforge.com/minecraft/mc-mods/advancement-plaques>
   - Kotlin for Forge (by thedarkcolour)
   <https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge>
   - Colds: Easy Paxel (Lite) (FORGE) (by Coldspell_Games)
   <https://www.curseforge.com/minecraft/mc-mods/colds-easy-paxel-lite>
   - Macaw's Trapdoors (by sketch_macaw)
   <https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors>
   - YUNG's API (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-api>
   - Better Archeology (by Pandarix)
   <https://www.curseforge.com/minecraft/mc-mods/better-archeology>
   - Cristel Lib (by Cristelknight)
   <https://www.curseforge.com/minecraft/mc-mods/cristel-lib>
   - Bookshelf (by DarkhaxDev)
   <https://www.curseforge.com/minecraft/mc-mods/bookshelf>
   - SuperMartijn642's Core Lib (by SuperMartijn642)
   <https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib>
   - Towns and Towers (by Biban_Auriu)
   <https://www.curseforge.com/minecraft/mc-mods/towns-and-towers>
   - GlitchCore (by TheAdubbz)
   <https://www.curseforge.com/minecraft/mc-mods/glitchcore>
   - More Beautiful Pressure Plates [FORGE & FABRIC] (by 00theblackwolf00)
   <https://www.curseforge.com/minecraft/mc-mods/more-beautiful-pressure-plates>
   - Macaw's Doors (by sketch_macaw)
   <https://www.curseforge.com/minecraft/mc-mods/macaws-doors>
   - Golden Hopper (by MrCrayfish)
   <https://www.curseforge.com/minecraft/mc-mods/golden-hopper>
   - Dark Utilities (by DarkhaxDev)
   <https://www.curseforge.com/minecraft/mc-mods/dark-utilities>
   - Framework (by MrCrayfish)
   <https://www.curseforge.com/minecraft/mc-mods/framework>
   - XP Health (by boterop)
   <https://www.curseforge.com/minecraft/mc-mods/xp-health>
   - Macaw's Roofs (by sketch_macaw)
   <https://www.curseforge.com/minecraft/mc-mods/macaws-roofs>
   - More Beautiful Fences & Gates [FORGE & FABRIC] (by 00theblackwolf00)
   <https://www.curseforge.com/minecraft/mc-mods/more-beautiful-fences-gates>
   - Advanced XRay (Neoforge Edition) (by ErrorMikey)
   <https://www.curseforge.com/minecraft/mc-mods/advanced-xray>
   - OpenBlocks Elevator (by vsngarcia)
   <https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator>
   - Iceberg [Forge] (by Grend_G)
   <https://www.curseforge.com/minecraft/mc-mods/iceberg>
   - YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
   <https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds>
   - MVS - Moog's Voyager Structures (by finndog_123)
   <https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures>
   - Architectury API (Fabric/Forge/NeoForge) (by shedaniel)
   <https://www.curseforge.com/minecraft/mc-mods/architectury-api>

**Comment by queso-gato1355** [comment]
I found the issue that was not related to your mod list. This is currently the condition that is related to the stripping event on a cinnamon log.

We'll discuss this that the condition is necessary, and I'll talk to you about the progress later.

And could you tell me this error is occurred in survival?

**Comment by CuddleBear1812** [comment]
Hello,
I just found that your mod is indeed working correctly for the cinnamon
tree. I just discovered that the issue was I was using a paxel from the mod

   - Colds: Easy Paxel (Lite) (FORGE) (by Coldspell_Games)
   <https://www.curseforge.com/minecraft/mc-mods/colds-easy-paxel-lite> when I
   just used a regular axe it worked correctly and gave me cinnamon
