### ISSUE TITLE
Tweak to Player Made Crop Leaves

### ISSUE THREAD

**Issue by RKDeviancy** [ExcessiveAmountsOfZombies/Croptopia#622]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

For reference: I am on the most recent file for 1.21 on fabric.

I would suggest that player made crop leaves made from using the fruit saplings on a placed leaf block do *not* decay so easily. 

I tried to make custom trees that had apples on them, for a custom orchard, for example. I built the tree like usual, it looked nice, and then I went to add the apples using the fruit saplings to turn the leaves into crop leaves. Immediately, the crop leaves started to decay despite having several regular oak leaves all around them.

Only the leaves that were tightly packed together like vanilla trees would not decay. 

I don't know if this is intended or not, but if it is, could you consider changing it so they function the same as vanilla player placed leaves? I think the ability to create custom trees that utilize the tree fruit would be cute.

Thank you, that's all the suggestion is!

**Comment by ExcessiveAmountsOfZombies** [comment]
You can get close, they don't have to be packed, they just have to be connected to an oak log within 7 blocks
