### ISSUE TITLE
[bug] double items when fishing

### ISSUE THREAD

**Issue by Synqatron** [ExcessiveAmountsOfZombies/Croptopia#625]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.21

### Croptopia version.

3.0.5

### What happened?

Every time we fish two items get reeled up.

**Comment by ExcessiveAmountsOfZombies** [comment]
this is ok because theres so much fishing loot as it is
