### ISSUE TITLE
Support for NeoForge

### ISSUE THREAD

**Issue by Shadowglitchjpg** [ExcessiveAmountsOfZombies/Croptopia#626]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Is the mod Fabric-only starting with 1.20.4 or is NeoForge support planned?

**Comment by devingDev** [comment]
I'd also like to see a neoforge port of this amazing mod!

**Comment by ExcessiveAmountsOfZombies** [comment]
on the way
