### ISSUE TITLE
Cinnamon Leaves drop jungle leaves

### ISSUE THREAD

**Issue by RC-Barry** [ExcessiveAmountsOfZombies/Croptopia#631]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.21

### Croptopia version.

3.0.6

### What happened?

I can't get cinnamon saplings, because every time i break the leaves, they drop jungle leaves as opposed to sticks and saplings. 

Because of this, cinnamon leaves, and cinnamon saplings are unobtainable in my survival world.

**Comment by ExcessiveAmountsOfZombies** [comment]
this is fixed now in 3.0.9
