### ISSUE TITLE
Creating butter consumes the "Cooking Pot" and the Metal "Food Press" and "Glass Bottles"?

### ISSUE THREAD

**Issue by SirTwsted** [ExcessiveAmountsOfZombies/Croptopia#632]
### Make sure you are not opening a duplicate.

- [ ] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.21

### Croptopia version.

3.0.9

### What happened?

Like the title says,
Creating 1 butter consumes the "Cooking Pot" and the Metal "Food Press" and "Glass Bottles"?
Just to create (1) butter?  😳🤔

I know this is a game, but come on...  When has anyone eaten a metal cooking pot, a metal food press and glass bottles?
🤷‍♀️  It just seems very weird.
If someone wanted to create Buttered Toast at the start of the game, it becomes extremely expensive for them,
because all the metal items to create 1 butter gets consumed.  It also seems unfair to the player that they have to
continuously create pistons, metal food press, glass bottles and metal pots just to create 1 butter.  👀💀

**Comment by WasatyCiastek** [comment]
I have the same issue. I feel so scammed.

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed in 4.0.0
