### ISSUE TITLE
Advancements bug 1.21

### ISSUE THREAD

**Issue by makumaku1974** [ExcessiveAmountsOfZombies/Croptopia#634]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

None

### Minecraft version.

1.21

### Croptopia version.

3.0.9

### What happened?

After eating food, I receive three bugged advancements.

1. Fancy Water - Craft any kind of drink 
2. Hearty Meal - Eat anything crafted - [Even though I ate rotten flesh lol]
3. Fully Stuffed - Eat anything with five or more ingredients [Rotten flesh is not an ingredient. This is also speaking by 5 ingredients should be eaten and not only 1.]

### Additional information.

![image](https://github.com/user-attachments/assets/0443b714-7e13-4416-b075-7d14dac11f5b)

**Comment by YocyCraft** [comment]
Oh no. This mod has stopped update. An issue a month ago and no any response now.

**Comment by makumaku1974** [comment]
> Oh no. This mod has stopped update. An issue a month ago and no any response now.

I got a respond last week about the glass bottle bugs ive reported. The problem with this one is just advancements and yes it's been a month already. Taking their sweet time i suppose.

**Comment by ExcessiveAmountsOfZombies** [comment]
i fixed in 4.0.0 i think
