### ISSUE TITLE
Issues with Contagion 1.21

### ISSUE THREAD

**Issue by makumaku1974** [ExcessiveAmountsOfZombies/Croptopia#639]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.21

### Croptopia version.

3.0.9

### What happened?

Croptopia conflicts with Contagion. How? Croptopia seems to override the Contagious Flesh from Zombies which is kinda important from Contagion.

**Comment by ExcessiveAmountsOfZombies** [comment]
I'd need more information than this as far as i know croptopia doesn't touch vanilla foods in any way
