### ISSUE TITLE
How to get salt from saltore?

### ISSUE THREAD

**Issue by Just1C3-2** [ExcessiveAmountsOfZombies/Croptopia#641]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Fabric

### Minecraft version.

1.21

### Croptopia version.

3.0.9

### What happened?

Title

### Relevant log.

Title

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed in 4.0.0
