### ISSUE TITLE
Add Foods Tag to Food

### ISSUE THREAD

**Issue by TheBedrockMaster** [ExcessiveAmountsOfZombies/Croptopia#642]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Add the `c:foods` item tag to edible items.

**Comment by ExcessiveAmountsOfZombies** [comment]
whenever i upload 4.0.1 this'll be added

**Comment by TheBedrockMaster** [comment]
Nice.
