### ISSUE TITLE
croptopia version 3.0.4 crashes (not 2.3.2) on forge mc 1.20.1

### ISSUE THREAD

**Issue by masuch** [ExcessiveAmountsOfZombies/Croptopia#643]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

3.0.4

### What happened?

Version 3.0.4 crashed on any instance (linux/windows) as client as server. Version 2.3.2 is working fine.
The following crash file:

[crash-2024-09-11_15.31.47-fml.txt](https://github.com/user-attachments/files/16964496/crash-2024-09-11_15.31.47-fml.txt)

### Relevant logs

[crash-2024-09-11_15.31.47-fml.txt](https://github.com/user-attachments/files/16964518/crash-2024-09-11_15.31.47-fml.txt)

### Additional information

list of mods is in the crash log file.

**Comment by ExcessiveAmountsOfZombies** [comment]
Looks like you were missing epherolib
