### ISSUE TITLE
Upload to Modrinth

### ISSUE THREAD

**Issue by vaporvee** [ExcessiveAmountsOfZombies/Croptopia#644]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Could you maybe upload this mod to Modrinth, so i can use it in my Modrinth modpack? Modrinth also has a higher ad revenue as Curseforge i think.

**Comment by ExcessiveAmountsOfZombies** [comment]
it dont but that's also not the entire reason why i won't upload on there (even if its a big one)

**Comment by nellePoint** [comment]
it definitely do

and i mean, you would only earn more money by putting it up there.,

**Comment by OshDubh** [comment]
Modrinth definitely does give you more revenue per download, see: https://blog.modrinth.com/p/creator-revenue-update

Also it's just a a way more creator-friendly platform than curseforge (which is an awful platform). It would mean a lot if it was available on Modrinth! This mod is the last mod in my modpack not on Modrinth so I would love it was uploaded there.
