### ISSUE TITLE
Consumption of pot (and not the good kind) when making cheese

### ISSUE THREAD

**Issue by McKitten** [ExcessiveAmountsOfZombies/Croptopia#645]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.21

### Croptopia version.

(Neoforge) 3.0.7

### What happened?

I made a single cheese because my pot was consumed in the process.

Using Cooking for blockheads  (21.1.1) cooking table (also cow in jar not recognised without bucket). Yet bucket not consumed.

### Additional information.

Parent pack is ATM 10 currently .53

**Comment by McKitten** [comment]
Confirmed that the same thing happens without the cooking table.

**Comment by THEdarkkman** [comment]
### All recipe consume the mod's tools:
When using a recipe from this mod that use a tool like the "All Purpose Press", it consume the tool in question.
This happened in any crafting table

**All the tool consumed:**
_All Purpose Press, Cooking Pot, Frying Pan, Cooking Knife, Mortar and Pestle_

This is on version 3.0.9 (file is 3.0.9 but in-game indicate 3.0.7)

**Comment by iHarukaa** [comment]
I have the same problem, maybe it's time to fix it? Please?

**Comment by DatrixTheHybridShadowWolf** [comment]
Confirmed as well with the All Purpose Food Press. While I do use Pam's in conjuction with this mod. I'd rather not get rid of this mod and leave Pam's on it's own...For now I will unfortunately have to disable this mod and will wait for a fix or update to this mod for 1.21.1 or whatever version it is fixed for. (Croptopia 3.0.9, Minecraft 1.21.1, NeoForged 21.1.72) (Though in game mod version is 3.0.7 like @THEdarkkman mentiioned earlier.)

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed in 4.0.0!!
