### ISSUE TITLE
[Fabric] Common tag support

### ISSUE THREAD

**Issue by Noaaan** [ExcessiveAmountsOfZombies/Croptopia#65]
It does not make a lot of sense to use the `#forge` tagspace when using the Fabric mod. It should be replaced with the common `#c` directory so that it is easier to add crossmod-compat. It would also be awesome to see the recipes supporting tags for ingredients as well! 
This is on latest Croptopia (1.3.0) for Fabric. 
![image](https://user-images.githubusercontent.com/4163353/111313028-2c1ccf00-8660-11eb-9ce0-bd6928ff19c6.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
I thought I was doing that, the forge tags must've been cached when I was building the jars for 1.3.0. This will be fixed in the next version I release as I re-did my build system again.

**Comment by Noaaan** [comment]
Awesome! It has been annoying using KubeJS in order to actually be able to use the same ingredients across mods.

**Comment by ExcessiveAmountsOfZombies** [comment]
took a few hours messing with gradle yesterday, but now all the recipes will properly have #c or #forge depending on which jar they are in.
