### ISSUE TITLE
Wrong version of croptopia

### ISSUE THREAD

**Issue by THEdarkkman** [ExcessiveAmountsOfZombies/Croptopia#650]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.21.1

### Croptopia version.

3.0.9

### Wrong verison:
The downloaded version of croptopia is 3.0.9 but in-game indicate it is 3.0.7

**Comment by ExcessiveAmountsOfZombies** [comment]
uhhh well 4.0.0 exists now, or is being uploaded so should be good
