### ISSUE TITLE
Croptopia X Dynamic Trees Compat Port to 1.16.5?

### ISSUE THREAD

**Issue by JasminWesson25** [ExcessiveAmountsOfZombies/Croptopia#651]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Description of your suggestion.

Hi, I'm not sure if you've been asked this before, but have you ever thought of porting the Croptopia Dynamic Trees Compat to 1.16.5? I love both mods, but Croptopia trees look weird if they're not like Vanilla Dynamic Trees. Sorry for being a bother. Have a nice day. :)

**Comment by ExcessiveAmountsOfZombies** [comment]
wrong repo but i won't be porting it either sorry fam
