### ISSUE TITLE
Guide Book refuses to open 

### ISSUE THREAD

**Issue by Devilswarchild** [ExcessiveAmountsOfZombies/Croptopia#652]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

Forge

### Minecraft version.

1.20.1

### Croptopia version.

1.20.1-FORGE-3.0.4.jar

### What happened?

trying to open the guide book for your mod and am presented with the following text in game chat

![image](https://github.com/user-attachments/assets/7c180786-3ae6-4cdc-96c0-f1c7caaf1b7c)

**Comment by ExcessiveAmountsOfZombies** [comment]
fixed in 4.0.0, not sure if i'll be backporting stuff yet but if i do this'll be fixed
