### ISSUE TITLE
Recipe Missing Errors

### ISSUE THREAD

**Issue by itsdeadfrosty** [ExcessiveAmountsOfZombies/Croptopia#654]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=) and did not find an issue describing my bug.

### Platform.

None

### Minecraft version.

1.20.1

### Croptopia version.

e

### What happened?

Error: Recipe not found warnings for multiple items (e.g., amethyst_ingot_smithing, stuffed_poblanos).
Impact: Incomplete or missing recipes for crafting items, possibly affecting gameplay progression.
Potential Conflict: Croptopia’s recipe issues appear frequently, which might indicate broader compatibility or registration issues.

### Relevant log.

[latest.log](https://github.com/user-attachments/files/17606472/latest.log)

**Comment by ExcessiveAmountsOfZombies** [comment]
This looks like some other mod removed the minecraft:shaped recipe type or something, not an issue with croptopia
