### ISSUE TITLE
[1.21.1] Mod error preventing the game to launch

### ISSUE THREAD

**Issue by Periam** [ExcessiveAmountsOfZombies/Croptopia#656]
After installing the latest version of the mod the game does not launch.

MC 1.21.1
neoforge-21.174
croptopia_1.21.1_NEO-FORGE-4.0.0
jei-1.21.1-neoforge-19.21.0.247

Attached screen shot
![image](https://github.com/user-attachments/assets/ff6612e6-313c-486f-9044-12d0e8777ecd)

Attached logs

[latest.log](https://github.com/user-attachments/files/17621251/latest.log)

**Comment by DatrixTheHybridShadowWolf** [comment]
Comment deleted

**Comment by ExcessiveAmountsOfZombies** [comment]
Add epherolib
