### ISSUE TITLE
Croptopia doesn't have recipes for Cheese and Flour

### ISSUE THREAD

**Issue by GonB42** [ExcessiveAmountsOfZombies/Croptopia#659]
Modpack version 1.7.0
Was not able to craft either cheese or flour, went into the discord found out from a user named Linguardium states that the flourable tag appears empty. Was su
<img width="344" alt="tag" src="https://github.com/user-attachments/assets/21f045d0-d1a7-4b57-ab75-6615adf0eb36">
![cheese](https://github.com/user-attachments/assets/b4183429-5d26-46f2-87eb-c91ed14c3218)
![flour](https://github.com/user-attachments/assets/bc4b15e2-9bcc-4504-a9dd-a8160b460c21)
ggested to submit a bug repor

**Comment by ExcessiveAmountsOfZombies** [comment]
uploading 4.0.1 rn should be up soon
