### ISSUE TITLE
Frying Pan damage broken

### ISSUE THREAD

**Issue by JustAWOIII** [ExcessiveAmountsOfZombies/Croptopia#66]
The only thing that I'm reporting is that the Frying Pan item is literally better than a Netherite Sword in terms of damage and attack speed, this item is absolutely broken, and I'm wondering if you can just make it do much, much less damage, and release an update as a fix.

**Comment by ExcessiveAmountsOfZombies** [comment]
i've just removed it from being a sword

**Comment by JustAWOIII** [comment]
Thank you so much, appreciate it man

I only requested this because people were abusing it on my multiplayer server, thanks for coming through for me
