### ISSUE TITLE
Missing 'forge:barley' tag referenced in 'crops.json'

### ISSUE THREAD

**Issue by Wabbit0101** [ExcessiveAmountsOfZombies/Croptopia#69]
**Version**
**Croptopia-1.16.4-FORGE-1.3.1**

**Platform**
FORGE

**Describe the issue**
Broken data tag file: 'forge:crops'. A bit of jar sniffing reveals that there is a file 'forge/barlies.json' that contains a reference to croptopia's barley item...seems the crops.json file just needs updating. (forge:cataloupe is also broken...may be others)

**To Reproduce**
Load the mod under Forge. 

**Screenshots**
`[17:33:35] [Server thread/ERROR] [minecraft/TagCollectionReader]: Couldn't load item tag forge:crops as it is missing following references: #forge:barley (from Croptopia-1.16.4-FORGE-1.3.1.jar),#forge:cantaloupe (from Croptopia-1.16.4-FORGE-1.3.1.jar)`

**Other Mods**
None needed

**Comment by ExcessiveAmountsOfZombies** [comment]
I believe this is fixed now
