### ISSUE TITLE
Potential bug.

### ISSUE THREAD

**Issue by Slydragon05** [ExcessiveAmountsOfZombies/Croptopia#7]
Ok, so I'm not entirely sure if this is a bug or not, but in the modpack I've been playing, this mod has been recently added to it.
It seemed to be working well at first but we've found a few issues now, one being that the 'all purpose food press' item doesn't have a recipe and that one of the items used for making food is used up on making a recipe, I think it's the baking pan, not entirely sure as I don't have the game open at current. I'll leave a small clip in the attachments to show what I mean. Again, I'm unsure if this is intentional or not but I don't believe it is, hence reporting this.
![ezgif-3-746d10ebefff](https://user-images.githubusercontent.com/72750637/97996531-c847e700-1ddf-11eb-9129-ac1145f013a9.gif)

This is a link to the Discord server we use to talk to each other about issues and things on https://discord.gg/PVZKSaJ7Pn Please join us there if you have some information in response as I don't use this site often. Thanks for your time, have a nice day.

**Comment by ExcessiveAmountsOfZombies** [comment]
This will be fixed in the next version we publish
