### ISSUE TITLE
Where do I find these items?

### ISSUE THREAD

**Issue by quickwitch** [ExcessiveAmountsOfZombies/Croptopia#70]
**Version**
1.16.4
**Platform**
Forge

**Describe the issue**
I'm having trouble making recipes, as I can't find some ingredients. Vanilla, Cinnamon, etc

Is there a guide where I can see where to find these ingredients?

In the Wiki tab they don't talk about them.

Excuse my bad English, I don't speak the language

**Comment by ExcessiveAmountsOfZombies** [comment]
I'm assuming you're on 1.3.0 or 1.3.1, previous versions don't have those items. You can find vanilla seeds in jungle biomes and cinnamon trees also spawn in jungle biomes, you can get the cinnamon by right clicking the tree with an axe.

**Comment by ExcessiveAmountsOfZombies** [comment]
also edited the wiki to reflect these changes

**Comment by quickwitch** [comment]
If I'm on 1.3.1 excuse me, where is the latest version? In Forge this is the latest version, thank you very much.

**Comment by ExcessiveAmountsOfZombies** [comment]
I meant versions before 1.3.0

**Comment by quickwitch** [comment]
Hello again, sorry for being so tiresome. Paprika is also not on the wiki. Not available yet? .

**Comment by quickwitch** [comment]
Sorry for being so heavy.
Can you get cinnamon by right clicking on the trunk of any jungle tree?

Orque I didn't get after hours searching.

**Comment by ExcessiveAmountsOfZombies** [comment]
only by right clicking the cinnamon log trees. they spawn in any of the vanilla jungle biomes though
