### ISSUE TITLE
Items Disappear/can’t place them

### ISSUE THREAD

**Issue by pppants420** [ExcessiveAmountsOfZombies/Croptopia#71]
**Version**
Which version of Croptopia are you using?
1.16.5 FABRIC 1.3.1
**Platform**
Which platform are you using Croptopia on?
(Fabric, Forge)
Fabric 
**Describe the issue**
A clear and concise description of what the issue is. I can see all the items in the creative menu, but when I try to place anything or read the guide the item just disappears from my hand

**To Reproduce**
How can I reproduce the issue?

**Screenshots**

**Other Mods**
What other mods are you using? Having a list might be helpful for me.
![image](https://user-images.githubusercontent.com/81257857/112196366-35f68300-8bc8-11eb-86cc-71ce58a64c50.jpg)

**Additional context**

**Comment by ExcessiveAmountsOfZombies** [comment]
The only thing I can think of is you're on a server without croptopia installed. Otherwise everything would be working.
