### ISSUE TITLE
[Feature request] Support for Phytogenic Insulator from Thermal Series

### ISSUE THREAD

**Issue by AbacusOperator** [ExcessiveAmountsOfZombies/Croptopia#72]
Thermal Series allows artificial farming of plants in the machine known as Phytogenic Insulator. If input planting material, it produces copy of planting material and common drops in reasonable proportions. Example:
oak sapling -> oak sapling + 6 oak logs + apple
I seen several agricultural mod implementing support for it (Farmer's Delight, Pam's Harvestcraft Series). Can you, please, implement this for Croptopia's seeds and saplings?

**Comment by ExcessiveAmountsOfZombies** [comment]
1.4.0 added the thermal recipes
