### ISSUE TITLE
How can I plant vanilla?

### ISSUE THREAD

**Issue by lumbercat** [ExcessiveAmountsOfZombies/Croptopia#73]
**Version**
I don't know if its possible to plant vanilla, and if it is can u explain me how? u.u

**Comment by BrekiTomasson** [comment]
Place Vanilla in a crafting table to get seeds:

![image](https://user-images.githubusercontent.com/7026735/112745619-1a192580-8faa-11eb-8350-8f8046827377.png)

Then place the seeds into farmland just like with any other seed:

![image](https://user-images.githubusercontent.com/7026735/112745637-4765d380-8faa-11eb-8f60-c35f8f760596.png)
