### ISSUE TITLE
Can't seem to find a way to get "pepper".

### ISSUE THREAD

**Issue by xevira** [ExcessiveAmountsOfZombies/Croptopia#75]
I've looked at the code and json files, but I can't seem to find out how you get the "pepper" item (croptopia:pepper) that is used in four recipes.  There's no recipe for it, nor does it appear that anything drops it that I can tell.

Please advise, thank you.

**Comment by cryxli** [comment]
Pepper should drop in plains. See https://github.com/ExcessiveAmountsOfZombies/Croptopia/wiki/Crops

**Comment by xevira** [comment]
That is the chili pepper seeds and needs to be corrected in the wiki.  The Pepper *item* (that looks like black salt) does not appear to have any source.

**Comment by cryxli** [comment]
Oh, you're talking about the ground black **Pepper** (croptopia:pepper) and not the plant **Chile Pepper** (croptopia:chile_pepper).

Agreed, that recipe is missing as of version [Croptopia-1.16.4-5-FABRIC-1.3.2](https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric/files/3253112).

**Comment by xevira** [comment]
Well, there are four food recipes that require that item, so they can't be made.  Either the source for croptopia:pepper should be put back/updated, or those four recipes should be changed if croptopia:pepper is getting discontinued, whichever is easier to deal with/fits in the goal of the mod author.

**Comment by Daviel2** [comment]
I'm having the same issue too, It doesn't appear to have a recipe at all, 
Though I've figured out how to make Paprika, Ground-Black Pepper is a problem as there is no recipe for it in the book.

**Comment by ExcessiveAmountsOfZombies** [comment]
Pepper plants have been added in 1.4.0
