### ISSUE TITLE
Serene seasons?

### ISSUE THREAD

**Issue by JoeltCola734** [ExcessiveAmountsOfZombies/Croptopia#78]
Is there any way to make this compatible with this seasons mod? Only make things grow a certain time of year?

**Comment by ExcessiveAmountsOfZombies** [comment]
I can look into adding support for it, I'll have to look through their repo to see how they do it to vanilla crops

**Comment by ExcessiveAmountsOfZombies** [comment]
Looking at it, you can add the seeds to their sereneseasons config and it will be applied to the seeds and crops, maybe I'll make a PR on their repo to try and get them added by default.

**Comment by ExcessiveAmountsOfZombies** [comment]
Pull Request made, I'll close this as it's up to them if they're going to accept it or not and you can also add it to the config on your end if you want.
