### ISSUE TITLE
Issue: Crops when grown fully disappear

### ISSUE THREAD

**Issue by VortexEyes** [ExcessiveAmountsOfZombies/Croptopia#8]
Like soy beans; chile peppers, barly, mustard, oat and potentioly others.

**Comment by ExcessiveAmountsOfZombies** [comment]
What version of the mod is this one?

**Comment by VortexEyes** [comment]
It's 1.0.3

2020-11-08, sk 03:08, Thonk <notifications@github.com> rašė:

**Comment by VortexEyes** [comment]
All good for now updated the aof pack and it was updated :)

**Comment by ExcessiveAmountsOfZombies** [comment]
Awesome, yea it was an issue in 1.0.3 but now fixed in 1.0.4
