### ISSUE TITLE
Config option to ignore biomes / generate seeds based on biome climate

### ISSUE THREAD

**Issue by lol123123987** [ExcessiveAmountsOfZombies/Croptopia#82]
Playing this mod together with a biome mod can make the seeds unusually rare, as they are set to only generate in certain types of biomes. It would be nice to have an option that makes all grass have a chance of dropping a random seed, no matter where it is. 

It would be even nicer if seeds dropped based on a biome's climate values, such as humidity and temperature, so the drops make some sense

**Comment by ExcessiveAmountsOfZombies** [comment]
I think in 1.8.0 what I'll do is just let anyone specify which biomes they want instead of it being done based on category.
