### ISSUE TITLE
1 petition and 1 issue haha

### ISSUE THREAD

**Issue by K0KE11** [ExcessiveAmountsOfZombies/Croptopia#83]
**Version**
Latest 1.16.5

**Platform**
Fabric

**Describe the issue**
Can u please add the leaves blocks like the oak one with apple in it so it can be also decorative? I really thing this willl make a nice addition to the game and or mod, also when u try to move the leaf block it crashes and ¿makes everything slow and my minecraft skin it's all black now hahahaha also apparently u can´t mine the leaf block in survival like their are bedrock or sth haha

**To Reproduce**
A piston pushing the block 

**Other Mods**
Well I have a ton of them but  the one that crashes everyhing is Sodium according to the NotEnoughCrashes mod

**Additional context**
I just wantes to use the block to decor ;( hahaha i hope u add them

**Comment by ExcessiveAmountsOfZombies** [comment]
I went and tested this out and they didn't crash my game. I also don't want to add them as a decorative block because then people could have apple bushes instead of apple trees.
