### ISSUE TITLE
Croptopia vs Vanilla - seed vs seeds.

### ISSUE THREAD

**Issue by RDKRACZ** [ExcessiveAmountsOfZombies/Croptopia#84]
All Croptopia plantable items other than saplings are singular instead of plural. In Vanilla `Wheat` grows from `Wheat Seeds` whereas in this mod e.g. `Turnip` grows from `Turnip Seed`.

**Comment by ExcessiveAmountsOfZombies** [comment]
Changed in 1.3.6, thanks
