### ISSUE TITLE
Dehydration compat not working.

### ISSUE THREAD

**Issue by RDKRACZ** [ExcessiveAmountsOfZombies/Croptopia#85]
v.1.3.1
@Globox1997

Funny thing there was more info here but I lost internet connection when submitting and it vanished.

**Comment by ExcessiveAmountsOfZombies** [comment]
globox will need to add the compatibility back on their end. I couldn't get my gradle buildscript to work anymore with their setup. I did add an event https://github.com/ExcessiveAmountsOfZombies/Croptopia/blob/master/fabric/src/main/java/me/thonk/croptopia/event/DrinkEvent.java so it's easier to listen for it now though, and I have the tags still in place.
