### ISSUE TITLE
How do i get salt

### ISSUE THREAD

**Issue by bore24** [ExcessiveAmountsOfZombies/Croptopia#87]
How do i get salt

**Comment by RDKRACZ** [comment]
What is wrong with people?
https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues?q=Salt

**Comment by ExcessiveAmountsOfZombies** [comment]
please check the wiki before asking where things generate https://github.com/ExcessiveAmountsOfZombies/Croptopia/wiki/World-Generation#salt
