### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by lilfattcat** [ExcessiveAmountsOfZombies/Croptopia#89]
**Version**
1.16.5

**Platform**
Which platform are you using Croptopia on?
Fabric curse forge

**Describe the issue**
can't find wiki online and can't use mod without recipes. I cannot make the book every time i try it shows a texture that is pink and black. I do not own the mod is there a wiki that shows me recipes?

**To Reproduce**
make book

**Screenshots**

**Other Mods**
i have a modpack on https://www.curseforge.com/minecraft/modpacks/berbembem-fabric

**Additional context**

**Comment by RDKRACZ** [comment]
>can't use mod without recipes

Just use REI?

>every time i try it shows a texture that is pink and black. / i have a modpack

Report to them that they forgot to add Patchouli.
> I do not own the mod

Yeah, we know.

>Version

Gonna quote here "Which version of Croptopia are you using?".


Also bad title.

**Comment by lilfattcat** [comment]
> > can't use mod without recipes
> 
> Just use REI?
> 
> > every time i try it shows a texture that is pink and black. / i have a modpack
> 
> Report to them that they forgot to add Patchouli.
> 
> > I do not own the mod
> 
> Yeah, we know.
> 
> > Version
> 
> Gonna quote here "Which version of Croptopia are you using?".
> 
> Also bad title.

thanks i told him he forgot a mod
