### ISSUE TITLE
[Bug] Recipe collision

### ISSUE THREAD

**Issue by cryxli** [ExcessiveAmountsOfZombies/Croptopia#9]
### Setup
- Minecraft 1.16.3
- Fabric API 0.10.6+build.415
- Croptopia 1.0.4-1.16.3-FABRIC

### Observation
- **Soy Sauce** and **Tofu** have the same recipe. Shapeless: **Cooking Pot**, **Water Bucket**, **Soy Beans**. That results in one item being not craftable.

### Suggestion
- Change shapeless recipes to shaped ones. E.g. stack bottom to top: Pot, Water, Beans vs. Pot, Beans, Water

Thanks for a great mod!
Cheers, cryxli

**Comment by ExcessiveAmountsOfZombies** [comment]
this will be fixed in the next update
