### ISSUE TITLE
Flour and Corn Husk Recipe

### ISSUE THREAD

**Issue by 0alyson0** [ExcessiveAmountsOfZombies/Croptopia#91]
**Version**
1.16.5

**Platform**
Fabric

**Describe the issue**
"Flour" and "Corn Husk" have the same recipe and it makes me Unable to Craft the "Corn Husk"

**To Reproduce**
Look in the Crafting recipe in the Book, Also When you put Two "Corn" in the Crafting table It only Crafts "Flour"

**Screenshots**
![2021-04-10_16 35 51](https://user-images.githubusercontent.com/72140055/114284045-30e46100-9a1b-11eb-88ed-adcee8537611.png)
![2021-04-10_16 36 02](https://user-images.githubusercontent.com/72140055/114284047-30e46100-9a1b-11eb-8185-90d4e2d003bd.png)
![2021-04-10_16 36 56](https://user-images.githubusercontent.com/72140055/114284048-30e46100-9a1b-11eb-8c7c-2a5bce3f8e00.png)

**Other Mods**
Haema, Inmis, InventorySorter, Mermod, MobOrigins, OkZoomer, OrderlyMod, Origins (Classes, Plus, Umbrellas Slime, Wiicustom), Pehkui, Requiem, Wolves with Armor, Compressium Mod, Compressed Blocks and Roughtly Enough Items.

**Additional context**
I Think you Might need to remove that Corn is a Possible Flour Craft.

**Comment by RDKRACZ** [comment]
This may not be an issue, you can use [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric), maybe Croptopia was supposed to have it as a dependency.

**Comment by ExcessiveAmountsOfZombies** [comment]
This will also be fixed in 1.3.4.  Polymorph can be useful for when I miss recipe conflicts but hopefully this will happen less in the future.

**Comment by ExcessiveAmountsOfZombies** [comment]
This is actually fixed in 1.3.6 now. Thank you!

**Comment by Shadowlord69** [comment]
How was it fixed.  I still have the same issue...
