### ISSUE TITLE
Change the recipes that need water

### ISSUE THREAD

**Issue by Hookat** [ExcessiveAmountsOfZombies/Croptopia#93]
**Version**
1.3.1

**Platform**
Forge

**Describe the issue**
The recipes that use water need a bucket of water, I think it would be cooler if it used a bottle with water so we could use a cauldron instead

**To Reproduce**
Craft any recipe that uses water

**Additional context**
Not an issue but a feature request.

**Comment by ExcessiveAmountsOfZombies** [comment]
duplicate of #54
