### ISSUE TITLE
Can't find all ingredients on the ingredients section of the book

### ISSUE THREAD

**Issue by Hookat** [ExcessiveAmountsOfZombies/Croptopia#94]
**Version**
1.3.1

**Platform**
Forge

**Describe the issue**
There is no way to know how to make salt or paprika. It's missing from the book and also the ingredient under the recipes that use them have no option to Shift+Click to know the crafting recipe.

**To Reproduce**
Search for the salt or paprika on the ingredients

**Comment by ExcessiveAmountsOfZombies** [comment]
This is now fixed in 1.3.6, it adds a salt page explaining where you can get salt and it gives you the recipe for paprika. Thank you!
