### ISSUE TITLE
Cannot Seem to Harvest Trees 

### ISSUE THREAD

**Issue by Daviel2** [ExcessiveAmountsOfZombies/Croptopia#95]
**Version**
Which version of Croptopia are you using?
1.16.5
**Platform**
Which platform are you using Croptopia on?
(Fabric, Forge)
Fabric
**Describe the issue**
A clear and concise description of what the issue is.
When I am right clicking on the fruit on the trees, I cannot seem to harvest
**To Reproduce**
How can I reproduce the issue?
I am able to go to any tree, and right clicking does not seem to work
**Screenshots**
Unable to send any screenshots.
**Other Mods**
What other mods are you using? Having a list might be helpful for me.
Specifically, I am using Fabric, Fabric-API, Origins, croptopia, and Patchouli Fabric.
**Additional context**
N/A

**Comment by ExcessiveAmountsOfZombies** [comment]
The crops on the trees need to be fully grown. You can check the age in F3 and if they're age:3 they're fully grown. You can also install something like HYWLA I believe and see the current percentage growth.
