### ISSUE TITLE
Vanilla Pods unable to find

### ISSUE THREAD

**Issue by fluffydumpster** [ExcessiveAmountsOfZombies/Croptopia#96]
Hello! Is vanilla pod a rare seed to find? We've been looking for it in the jungle for a long time and can't find it. Help! Thanks!:)

**Comment by Albeion** [comment]
Might be RNG or something, but some seed crops are just very hard to get sometimes, like how it was very hard for me to get the Saguaro desert seed, and considering how many seed options you can get in the jungle. Just keep trying and you will get it eventually.

**Comment by ExcessiveAmountsOfZombies** [comment]
You didn't specify which version you're on. I just tested to make sure but they generate in jungles in 1.3.3. They have the same drop chance as any other jungle dropping seed.
