### ISSUE TITLE
Bottle Dupe

### ISSUE THREAD

**Issue by Albeion** [ExcessiveAmountsOfZombies/Croptopia#97]
**Version**
The latest version dated on 14/4/21. Croptopia-1.16.4-5-FABRIC-1.3.3

**Platform**
I am playing using fabric.

**Describe the issue**
When making mead with a bottle of honey, you get the bottle from the honey back, however drinking the mead also gives you a bottle back. Duping the bottles.

**To Reproduce**
Make the mead using a bottle of honey, a bucket of water and all purpose food processor.

**Screenshots**

**Other Mods**
Chest Cavity mod and fabric waystones.

**Comment by ExcessiveAmountsOfZombies** [comment]
This is fixed in 1.3.6, thank you!
