### ISSUE TITLE
Vanilla seed  inquiry

### ISSUE THREAD

**Issue by fluffydumpster** [ExcessiveAmountsOfZombies/Croptopia#98]
Version: Croptopia-1.16.4-5-FABRIC-1.2.0.jar
![Screenshot 2021-04-15 000022](https://user-images.githubusercontent.com/82495953/114816379-9f0f8780-9d7d-11eb-8db8-45caa3304061.jpg)
](url)
Hello! I did an inquiry about the vanilla seeds yesterday and we're unable to find vanilla "seeds" in the inventory too, so we are wondering if they just drop as vanilla pods or they are actual seeds.

**Comment by ExcessiveAmountsOfZombies** [comment]
you can still comment on issues I close, they don't drop in 1.2.0 you'll need to update to the latest version
