### ISSUE TITLE
May I make an introduction to https://www.mcbbs.net/ 

### ISSUE THREAD

**Issue by Thesea-233** [ExcessiveAmountsOfZombies/Croptopia#99]
**Version**
-

**Platform**
-

**Describe the issue**
Nice mod ! May I make an introduction to https://www.mcbbs.net/ ？I hope more Chinese player will use it! I will write your username ,the license and your curseforge website in the introduction.I will use the curseforge download link for the download!

**To Reproduce**
-

**Screenshots**
-

**Other Mods**
-

**Additional context**
-

**Comment by ExcessiveAmountsOfZombies** [comment]
Sure, seems fine to me!
